import { currentLeaveEntitlements } from './currentLeaveEntitlements';
import { MedicalTracking } from './MedicalTracking';
import type { MedicalTrackingSummary } from './MedicalTracking';
import { policyVersionLabel } from './policyVersionLabel';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiClient } from '../../lib/api';
import { formatDate } from '../../lib/date';
import { AustralianDateInput } from '../../components/AustralianDateInput';
import { Button, LoadingState } from '../../components/Ui';
import { ActionDialog, Field, inputClass } from './ManagementFields';
import { value } from './managementForm';
import { EmployeeDetails } from './EmployeeDetails';
import { EmployeeOnboarding } from './EmployeeOnboarding';
import { GovernmentFoundation } from './GovernmentFoundation';
import { GovernmentWorkflowManagement } from './GovernmentWorkflowManagement';
import { reviewRecordLabel } from './reviewRecordNames';
import type { EmployeeProfile, WorkPattern } from './managementTypes';
import type { OrgDepartment } from './types';

type LegacyPolicy = {id:string;name:string;default_days:number;is_accruable:boolean;accrual_days_per_fortnight:string;max_balance:string|null;reset_period:string;is_active:boolean};
type Summary = {
    regime:string;account_type:string|null;restricted:boolean;as_of:string;reporting_manager:{name:string|null;description:string};
    legacy:null|{operational:boolean;leave_entitled:boolean;ineligible_reason:string|null;study_leave_start:string|null;study_leave_end:string|null;eligibility_note:string|null;join_date:string|null;daily_rate?:number|string|null;
        effective_balances:{leave_type_id:string;leave_type_name:string;year:number;balance:string;pending:string;source:string}[];
        balances:{id:string;leave_type_name:string;year:number;balance:string;pending:string}[];policies:LegacyPolicy[];settings:{accrual_anchor_date:string|null};application_counts:{status:string;count:number}[]};
    government:null|{medical_tracking:MedicalTrackingSummary;policy:null|{label:string;effective_from:string;effective_to:string};operational_status:string;
        activation:{status:string;enabled_codes:string[]};entitlements:{id:string;code:string;as_of:string;period_start:string;period_end:string;balance:string;held:string;available:string}[];
        application_counts:{status:string;count:number}[];applicability:{code:string;enabled:boolean;opening_certified:boolean;detail:string}[];
        route:{stages:{level:string;label?:string|null;approver_name:string|null;issue:string|null;conditional:boolean;applies_to:string[]}[]}};
    preparation:{key:string;label:string;status:string;detail:string}[];
};
export type EmployeeSection = 'arrangements'|'details'|'applications'|'prepare';
export type PreparationStep = 'identity'|'login'|'balances'|'activation';
const stages:Record<string,string>={division:'Divisional approver',parent_division:'Treasury / parent unit approver',department:'Head of Department',hr_verifier:'HR evidence verifier',relevant_secretary:'Relevant Secretary',minister:'Minister',chief_secretary:'Chief Secretary'};
const leaveName=(code:string)=>code.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
const steps: [PreparationStep, string][] = [['balances', 'Service & balances'], ['login', 'Account access'], ['activation', 'Leave access & schedules']];

export function EmployeeLeaveWorkspace({profile,departments,patterns,central,section,step,onNavigate,onClose,onChanged}:{profile:EmployeeProfile;departments:OrgDepartment[];patterns:WorkPattern[];central:boolean;section:EmployeeSection;step:PreparationStep;onNavigate:(section:EmployeeSection,step?:PreparationStep)=>void;onClose:()=>void;onChanged:()=>Promise<void>}) {
    const id=profile.employee.id;
    const [summary,setSummary]=useState<Summary|null>(null),[error,setError]=useState(''),[version,setVersion]=useState(0),[dialog,setDialog]=useState<'adjust'|'eligibility'|null>(null);
    useEffect(()=>{let live=true;void apiClient.get<Summary>(`/hr/directory/${id}/leave-arrangements`).then(data=>{if(live){setSummary(data);setError('');}}).catch((err:Error)=>{if(live)setError(err.message);});return()=>{live=false;};},[id,version,profile,section,step]);
    async function refresh(){await onChanged();setVersion(v=>v+1);}
    const legacy=summary?.legacy,government=summary?.government;
    const currentEntitlements=currentLeaveEntitlements(government?.entitlements||[]);
    const state = summary?.regime === 'government' ? (summary.restricted ? 'Access restricted' : government?.activation.status === 'active' ? 'Leave access active' : government?.activation.status === 'paused' ? 'Leave access paused' : 'Setup incomplete') : summary ? 'Employee record' : 'Loading…';
    return <div className="space-y-5">
        <div className="flex flex-wrap items-center justify-between gap-3"><div className="min-w-0"><Button variant="ghost" onClick={onClose}>← Employees</Button><h2 className="mt-2 break-words text-xl font-semibold text-gray-900">{reviewRecordLabel(profile.employee.display_name)}</h2><p className="break-words text-sm text-gray-600">{reviewRecordLabel(profile.employee.department_code||'Department unverified')} / {reviewRecordLabel(profile.employee.division_code||'Division unverified')} · {profile.employee.status}</p></div><span className="rounded-lg bg-blue-50 px-3 py-2 text-sm font-medium text-blue-900">{state}</span></div>
        <nav aria-label="Employee management" className="flex flex-wrap gap-2 border-b border-gray-200 pb-3">{([['arrangements','Overview'],['details','Details & appointment'],['applications','Applications'],...(central?[['prepare','Leave setup']]:[])] as [EmployeeSection,string][]).map(([key,label])=><Button key={key} variant={section===key?'primary':'secondary'} aria-current={section === key ? 'page' : undefined} onClick={()=>onNavigate(key, key === 'prepare' ? 'balances' : undefined)}>{label}</Button>)}</nav>
        {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
        {!summary&&!error&&<LoadingState label="Loading current leave arrangements…"/>}
        {section==='arrangements'&&summary&&<>
            <div className="app-panel space-y-3 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">Leave summary</h3><Button variant="secondary" onClick={()=>void refresh()}>Refresh</Button></div>
                {summary.regime === 'government' && government?.activation.status !== 'active' && <p className="text-sm text-gray-600">Review this employee’s appointment, certified balances and leave access before they apply.</p>}
                {government?.policy && summary.regime === 'government' && <p className="text-sm text-gray-600">Policy: <strong>{reviewRecordLabel(policyVersionLabel(government.policy.label,'published'))}</strong> · {formatDate(government.policy.effective_from)} to {formatDate(government.policy.effective_to)}.</p>}
                {summary.regime !== 'government' && <p className="text-sm text-gray-600">Reporting manager: <strong>{reviewRecordLabel(summary.reporting_manager.name || 'Not assigned')}</strong>.</p>}
            </div>

            {government&&(summary?.regime==='government'||government.entitlements.length>0)&&<section className="app-panel space-y-4 p-5"><h3 className="font-semibold">Leave balances</h3>{!government.entitlements.length&&<p className="text-sm text-gray-600">No current balance is recorded. Review Service & balances in Leave setup.</p>}<div className="grid gap-4 sm:grid-cols-3">{currentEntitlements.map(e=><div key={e.id} className="rounded-xl border border-blue-100 bg-blue-50/50 p-4"><h4 className="text-sm font-semibold text-gray-900">{leaveName(e.code)}</h4><p className="mt-2 text-3xl font-semibold tabular-nums text-brand">{Number(e.available)}</p><p className="mt-1 text-sm text-gray-600">days available</p><p className="mt-3 text-xs leading-5 text-gray-500">{Number(e.held)} awaiting approval · {Number(e.balance)} total<br/>{formatDate(e.period_start)} – {formatDate(e.period_end)}</p></div>)}</div><details className="space-y-2"><summary className="cursor-pointer text-sm text-gray-600">Leave type setup</summary>{government.applicability.map(a=><p key={a.code} className="text-sm text-gray-600"><strong>{leaveName(a.code)}</strong>: {a.enabled?'Enabled':'Not enabled'} · {a.opening_certified?'Balance certified':'Balance not certified'}. {a.detail}</p>)}</details></section>}
            {government?.medical_tracking&&<MedicalTracking tracking={government.medical_tracking} legacy={summary.regime==='legacy'}/>}
            {government&&<details open={summary.regime==='government'} className="app-panel space-y-3 p-4"><summary className="cursor-pointer text-sm font-semibold">Leave approvers · {formatDate(summary.as_of)}</summary><p className="text-sm text-gray-600">Each application follows the approval route recorded when it is submitted.</p><ol className="space-y-2">{government.route.stages.filter(s=>s.applies_to.some(code=>['recreation','medical','special'].includes(code))).map(s=><li key={s.level} className="rounded-lg border border-gray-200 p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{s.label||stages[s.level]||leaveName(s.level)}</strong><span>{reviewRecordLabel(s.approver_name||'Unassigned')}</span></div>{s.conditional&&<p className="mt-1 text-xs text-gray-500">Required for: {s.applies_to.map(leaveName).join(', ')}</p>}{s.issue&&<p className="mt-1 text-xs text-amber-800">{s.issue}</p>}</li>)}</ol><Link className="text-sm text-brand underline" to="/leave/settings?view=organisation">Manage organisation and approvers</Link></details>}
            {legacy&&<details open={summary.regime==='legacy'} className="app-panel space-y-3 p-4"><summary className="cursor-pointer font-semibold">{summary.regime==='government'?'Balance history':'Leave balances'}</summary><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{summary.regime==='government'?'Recorded balances':'Current balances'} · {summary.as_of.slice(0,4)}</h3>{central&&summary.regime==='legacy'&&<div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>setDialog('eligibility')}>Edit eligibility</Button>{legacy.operational&&<Button variant="secondary" onClick={()=>setDialog('adjust')}>Adjust balance</Button>}</div>}</div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="py-2 pr-4">Leave</th><th className="pr-4">Balance</th><th className="pr-4">Pending</th><th>Record</th></tr></thead><tbody>{legacy.effective_balances.map(b=><tr key={b.leave_type_id} className="border-b border-gray-100"><td className="py-3 pr-4">{b.leave_type_name}</td><td className="pr-4">{b.balance}</td><td className="pr-4">{b.pending}</td><td className="text-xs text-gray-500">{b.source==='stored'?'Stored balance':'Policy allowance — no stored balance'}</td></tr>)}</tbody></table></div>{!legacy.effective_balances.length&&<p className="text-sm text-gray-500">No recorded balances are available.</p>}<details className="text-sm"><summary className="cursor-pointer text-gray-600">Stored balance history ({legacy.balances.length})</summary><div className="mt-3 space-y-2">{legacy.balances.map(b=><p key={b.id}>{b.year} · {b.leave_type_name}: {b.balance} · pending {b.pending}</p>)}</div></details></details>}
        </>}
        {section==='details'&&<EmployeeDetails embedded profile={profile} central={central} departments={departments} patterns={patterns} onClose={onClose} onChanged={refresh}/>}
        {section==='applications'&&<>{legacy&&<p className="text-sm text-gray-600">Recorded application history: {legacy.application_counts.length?legacy.application_counts.map(c=>`${c.count} ${c.status}`).join(' · '):'none'}. View these records in Reports.</p>}{central?<GovernmentWorkflowManagement key={id} selectedEmployeeId={id} view="applications"/>:<p className="text-sm text-gray-600">Application review follows your assigned HR permissions. Open Approvals or Reports to view the records available to you.</p>}</>}
        {section==='prepare'&&central&&<>
            <div className="app-panel space-y-4 p-5"><div><h3 className="font-semibold">Complete this employee’s leave setup</h3><p className="mt-1 text-sm leading-6 text-gray-600">First record the appointment and work schedule in Details &amp; appointment. Then confirm service and balances, account access, and the leave types this employee can use.</p></div><nav aria-label="Employee leave setup" className="flex flex-wrap gap-2">{steps.map(([key,label])=><Button key={key} variant={(step==='identity'?'balances':step)===key?'primary':'secondary'} aria-current={step===key?'page':undefined} onClick={()=>onNavigate('prepare',key)}>{label}</Button>)}</nav></div>
            {(step==='balances'||step==='identity')&&<GovernmentFoundation key={id} selectedEmployeeId={id}/>}
            {step==='login'&&<EmployeeOnboarding key={id} departments={departments} selectedEmployeeId={id}/>}
            {step==='activation'&&<GovernmentWorkflowManagement key={id} selectedEmployeeId={id} view="activation"/>}
        </>}
        {dialog&&legacy&&<ActionDialog title={dialog==='adjust'?'Adjust balance':'Edit leave eligibility'} description={profile.employee.display_name} onClose={()=>setDialog(null)} onSave={async data=>{
            if(dialog==='adjust'){const amount=Number(value(data,'amount'));if(!amount)throw new Error('Enter a non-zero adjustment.');await apiClient.post('/hr/adjustments',{employee_id:id,leave_type_id:value(data,'leave_type_id'),amount,reason:value(data,'reason')});}
            else {const entitled=value(data,'leave_entitled')==='true',studying=!entitled&&value(data,'ineligible_reason')==='study_leave';await apiClient.put(`/hr/employees/${id}`,{leave_entitled:entitled,ineligible_reason:entitled?null:value(data,'ineligible_reason'),study_leave_start:studying?value(data,'study_leave_start')||null:null,study_leave_end:studying?value(data,'study_leave_end')||null:null,eligibility_note:entitled?null:value(data,'eligibility_note')||null});}
            setDialog(null);await refresh();
        }}>{dialog==='adjust'?<><Field label="Leave type"><select name="leave_type_id" className={inputClass}>{legacy.policies.filter(p=>p.is_active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Days to add or subtract"><input name="amount" type="number" step="0.5" required className={inputClass}/></Field><p className="text-sm text-gray-600">The adjustment and your reason are saved in the balance history. Pending applications remain protected.</p></>:<><Field label="Leave entitlement"><select name="leave_entitled" className={inputClass} defaultValue={String(legacy.leave_entitled)}><option value="true">Entitled</option><option value="false">Restricted</option></select></Field><Field label="Restriction reason"><select name="ineligible_reason" className={inputClass} defaultValue={legacy.ineligible_reason||'temporary'}><option value="study_leave">Study leave</option><option value="temporary">Temporary</option><option value="intern">Intern</option></select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Study leave from"><AustralianDateInput name="study_leave_start" className={inputClass} defaultValue={legacy.study_leave_start?.slice(0,10)||''}/></Field><Field label="Study leave through"><AustralianDateInput name="study_leave_end" className={inputClass} defaultValue={legacy.study_leave_end?.slice(0,10)||''}/></Field></div><Field label="Eligibility note"><input name="eligibility_note" className={inputClass} maxLength={300} defaultValue={legacy.eligibility_note||''}/></Field><p className="text-sm text-gray-600">This changes the recorded eligibility for this employee. Appointment facts and the policy effective on requested dates also determine whether an application is allowed.</p></>}</ActionDialog>}
    </div>;
}
