import { formatDateTime } from '../../lib/date';
import { useEffect, useState } from 'react';
import { useAuth } from '../../contexts/useAuth';
import { apiClient } from '../../lib/api';
import { Button, Pager, LoadingState, Modal, ModalActions } from '../../components/Ui';
import { ActionDialog, DirectoryPicker, Field, inputClass } from './ManagementFields';
import { value } from './managementForm';
import type { OrgDepartment } from './types';

type Batch = {id:string;login_mode:string;status:string;prepared_at:string;employee_count:number;reason:string};
type PreviewRow = {id:string;employee_id:string;snapshot:{display_name:string;email:string|null;payroll_ids:{external_id:string}[]};decision:string;issue:string|null;reviewer_id:string|null};
type BatchView = {batch:Batch;rows:PreviewRow[];counts:{decision:string;count:number}[];total:number};
type Account = {employee_id:string;display_name:string;employee_status:string;email:string|null;login_alias:string|null;account_type:string;account_status:string;onboarding_state:string;link_expires_at:string|null};
type Action = {kind:'link'|'offboard'|'restore'|'revoke-links';account:Account};
export function EmployeeOnboarding({departments,selectedEmployeeId=''}:{departments:OrgDepartment[];selectedEmployeeId?:string}) {
    const {user}=useAuth(),provision=user?.permissions?.admin===true;
    const [tab,setTab]=useState<'cohorts'|'accounts'>('cohorts'),[version,setVersion]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
    const [history,setHistory]=useState<{batches:Batch[];total:number}>({batches:[],total:0}),[historyPage,setHistoryPage]=useState(0);
    const [batchId,setBatchId]=useState(''),[batchPage,setBatchPage]=useState(0),[preview,setPreview]=useState<BatchView|null>(null);
    const [accounts,setAccounts]=useState<{accounts:Account[];total:number}>({accounts:[],total:0}),[accountPage,setAccountPage]=useState(0),[query,setQuery]=useState(''),[search,setSearch]=useState('');
    const [preparing,setPreparing]=useState(false),[applying,setApplying]=useState(false),[reconcile,setReconcile]=useState<PreviewRow|null>(null),[decision,setDecision]=useState<'link'|'skip'>('skip');
    const [action,setAction]=useState<Action|null>(null),[secret,setSecret]=useState<{activation_url:string;expires_at:string}|null>(null);
    useEffect(()=>{let live=true;void apiClient.get<typeof history>(`/hr/onboarding/batches?page=${historyPage+1}${selectedEmployeeId?`&employee_id=${selectedEmployeeId}`:''}`).then(data=>{if(live){setHistory(data);setLoading(false);setError('');}}).catch((err:Error)=>{if(live){setError(err.message);setLoading(false);}});return()=>{live=false;};},[historyPage,version,selectedEmployeeId]);
    useEffect(()=>{if(!batchId)return;let live=true;void apiClient.get<BatchView>(`/hr/onboarding/batches/${batchId}?page=${batchPage+1}${selectedEmployeeId?`&employee_id=${selectedEmployeeId}`:''}`).then(data=>{if(live){setPreview(data);setError('');}}).catch((err:Error)=>{if(live)setError(err.message);});return()=>{live=false;};},[batchId,batchPage,version,selectedEmployeeId]);
    useEffect(()=>{if(tab!=='accounts')return;let live=true;void apiClient.get<typeof accounts>(`/hr/onboarding/accounts?page=${accountPage+1}&search=${encodeURIComponent(search)}${selectedEmployeeId?`&employee_id=${selectedEmployeeId}`:''}`).then(data=>{if(live){setAccounts(data);setError('');}}).catch((err:Error)=>{if(live)setError(err.message);});return()=>{live=false;};},[tab,accountPage,search,version,selectedEmployeeId]);
    function refresh(message:string){setNotice(message);setVersion(v=>v+1);}
    return <section className="app-panel space-y-4 p-4"><div><h3 className="text-lg font-semibold">{selectedEmployeeId?'Login and enrolment':'Employee onboarding and offboarding'}</h3><p className="mt-1 text-sm text-gray-600">{selectedEmployeeId?'Prepare or review only the selected employee. Account access and Government leave activation are separate decisions.':'Prepare verified individual identities in cohorts, then activate each employee through a private handover.'}</p></div>
        <p className="rounded-lg bg-blue-50 p-3 text-sm text-blue-900">New accounts are Leave-only and disabled until activation. Existing accounts require an explicit verified link. Applying enrols the employee into Government Leave and stops their existing leave submission. Government applications remain unavailable until balances, reconciliation and independent activation are complete. Officeholder permissions are assigned separately.</p>
        {!provision && <p className="text-sm text-gray-600">Central HR can prepare and reconcile cohorts. Portal administration is also required to create accounts or issue activation/recovery links.</p>}
        <nav aria-label="Onboarding views" className="flex flex-wrap gap-2"><Button variant={tab==='cohorts'?'primary':'secondary'} onClick={()=>setTab('cohorts')}>Cohort preparation</Button><Button variant={tab==='accounts'?'primary':'secondary'} onClick={()=>setTab('accounts')}>Account lifecycle</Button></nav>
        {error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice && <p role="status" className="rounded-lg bg-green-50 p-3 text-sm text-green-800">{notice}</p>}
        {tab==='cohorts' && <><div className="flex flex-wrap justify-between gap-2"><h4 className="font-semibold">Prepared cohorts</h4><Button onClick={()=>setPreparing(true)}>{selectedEmployeeId?'Prepare this employee':'Prepare onboarding cohort'}</Button></div>{loading ? <LoadingState label="Loading cohorts…" /> : !history.batches.length && <p className="text-sm text-gray-500">No onboarding cohorts have been prepared.</p>}
            {history.batches.map(batch=><article key={batch.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-gray-200 p-3"><div className="min-w-0"><p className="text-sm font-semibold">{formatDateTime(batch.prepared_at)} · {batch.employee_count} employees</p><p className="text-sm text-gray-600">{batch.login_mode==='payroll'?'Payroll ID aliases':'Individual email'} · {batch.status==='applied'?'Applied':'Preview'}</p><p className="break-words text-xs text-gray-500">{batch.reason}</p>{selectedEmployeeId&&batch.employee_count!==1&&<p className="text-xs text-amber-800">Multi-employee cohort: review under Settings → Employee setup.</p>}</div><Button variant="secondary" disabled={!!selectedEmployeeId&&batch.employee_count!==1} onClick={()=>{setBatchId(batch.id);setBatchPage(0);setPreview(null);}}>Review cohort</Button></article>)}<Pager page={historyPage} pageCount={Math.ceil(history.total/20)} total={history.total} pageSize={20} setPage={setHistoryPage} />
            {preview && <div className="space-y-3 border-t border-gray-200 pt-4"><h4 className="font-semibold">Cohort review · {preview.total} employees · {preview.batch.status}</h4><p className="text-sm text-gray-600">{preview.counts.map(count=>`${count.decision}: ${count.count}`).join(' · ')}</p><p className="text-sm text-gray-600">Applying also enrolls retained existing logins in the gated government leave regime. Review all pages and verify each person's identity, individual contact or Payroll alias before applying. Blocked rows must be linked explicitly or skipped; changed employee facts require a new preview.</p>
                {preview.rows.map(row=><article key={row.id} className="space-y-2 rounded-lg border border-gray-200 p-3"><div className="flex flex-wrap justify-between gap-2"><div className="min-w-0"><h5 className="break-words font-semibold">{row.snapshot.display_name}</h5><p className="break-words text-sm text-gray-600">Payroll ID: {row.snapshot.payroll_ids.map(id=>id.external_id).join(', ') || 'Not verified'} · {row.snapshot.email || 'No email'}</p><p className="text-sm">{row.decision==='create' && preview.batch.status==='applied'?'Disabled account prepared':row.decision==='create'?'Ready to prepare':row.decision}</p></div>{preview.batch.status==='preview' && row.decision!=='retain' && <Button variant="secondary" onClick={()=>{setDecision('skip');setReconcile(row);}}>Resolve {row.snapshot.display_name}</Button>}</div>{row.issue && <p className="text-sm text-gray-600">{row.issue}</p>}</article>)}
                <Pager page={batchPage} pageCount={Math.ceil(preview.total/50)} total={preview.total} pageSize={50} setPage={setBatchPage} />
                {preview.batch.status==='preview' && provision && <Button disabled={preview.counts.some(count=>count.decision==='blocked'&&count.count>0)} onClick={()=>setApplying(true)}>Apply verified cohort</Button>}
            </div>}
        </>}
        {tab==='accounts' && <><form className="flex flex-wrap items-end gap-2" onSubmit={event=>{event.preventDefault();setSearch(query.trim());setAccountPage(0);}}>{!selectedEmployeeId&&<Field label="Search employee accounts"><input className={inputClass} maxLength={100} value={query} onChange={event=>setQuery(event.target.value)} placeholder="Name, email or exact Payroll ID" /></Field>}{!selectedEmployeeId&&<Button type="submit" variant="secondary">Search accounts</Button>}<Button variant="secondary" onClick={()=>setVersion(v=>v+1)}>Refresh accounts</Button></form>
            <p className="text-sm text-gray-600">Links expire after two hours. Reissuing replaces any unused link and ends sessions. Recovery changes the password only after the employee uses the link. Offboarding disables the employee and linked account, revokes sessions, unused links and scoped HR grants, and retains history.</p>
            {!accounts.accounts.length && <p className="text-sm text-gray-500">No linked accounts match.</p>}{accounts.accounts.map(account=><article key={account.employee_id} className="space-y-2 rounded-lg border border-gray-200 p-3"><h4 className="break-words font-semibold">{account.display_name}</h4><p className="break-words text-sm text-gray-600">{account.email || 'No individual email'}{account.login_alias ? ` · Payroll login: ${account.login_alias}` : ''}</p><p className="text-sm">Employee: {account.employee_status} · Account: {account.account_status} · {account.onboarding_state}</p>{account.link_expires_at && <p className="text-xs text-gray-500">Unused link expires {formatDateTime(account.link_expires_at)}; the private link itself cannot be retrieved.</p>}<div className="flex flex-wrap gap-2">
                {provision && account.account_type==='employee' && account.employee_status==='active' && <Button variant="secondary" onClick={()=>setAction({kind:'link',account})}>{account.account_status==='active' && account.onboarding_state==='ready'?'Issue recovery link':'Issue activation link'}</Button>}
                {account.link_expires_at && <Button variant="secondary" onClick={()=>setAction({kind:'revoke-links',account})}>Revoke unused links</Button>}
                {account.employee_status==='active' && <Button variant="secondary" onClick={()=>setAction({kind:'offboard',account})}>Offboard {account.display_name}</Button>}
                {account.employee_status==='inactive' && <Button variant="secondary" onClick={()=>setAction({kind:'restore',account})}>Restore employee record</Button>}
                {account.account_type!=='employee' && <p className="text-xs text-gray-500">Existing staff identity: activation/recovery remains in portal account administration. Disabling it also requires portal administration.</p>}
            </div></article>)}<Pager page={accountPage} pageCount={Math.ceil(accounts.total/50)} total={accounts.total} pageSize={50} setPage={setAccountPage} />
        </>}
        {preparing && <ActionDialog title="Prepare employee onboarding" onClose={()=>setPreparing(false)} onSave={async form=>{const batch=await apiClient.post<Batch>('/hr/onboarding/preview',{...(selectedEmployeeId?{employee_ids:[selectedEmployeeId]}:{department_id:value(form,'department_id')||null}),login_mode:value(form,'login_mode'),reason:value(form,'reason')});setPreparing(false);setBatchId(batch.id);setBatchPage(0);setHistoryPage(0);refresh('Preview prepared. No accounts or passwords have been created.');}}>{!selectedEmployeeId&&<Field label="Cohort department"><select name="department_id" className={inputClass}><option value="">All employee records</option>{departments.map(dept=><option key={dept.id} value={dept.id}>{dept.name}</option>)}</select></Field>}<Field label="Employee login method"><select name="login_mode" className={inputClass}><option value="email">Verified individual email</option><option value="payroll">Exact Payroll ID alias, with email optional</option></select></Field><p className="text-sm text-gray-600">Up to 2,000 employees per cohort. A Payroll alias preserves letters and leading zeros and never serves as a password. Missing/ambiguous verified IDs, shared emails and existing-account conflicts require review.</p></ActionDialog>}
        {applying && preview && <ActionDialog title="Apply verified onboarding cohort" onClose={()=>setApplying(false)} onSave={async form=>{if(!form.has('confirmed'))throw new Error('Confirm that the full cohort has been reviewed.');await apiClient.post(`/hr/onboarding/batches/${preview.batch.id}/apply`,{confirmed:true,reason:value(form,'reason')});setApplying(false);refresh('Cohort applied. New accounts remain disabled until individual activation.');}}><label className="block text-sm"><input type="checkbox" name="confirmed" required /> I have reviewed all {preview.total} employees and verified each creation/link decision and contact or Payroll alias.</label><p className="text-sm text-gray-600">This creates no shared or temporary passwords and sends no email. Issue individual links after verifying the recipient.</p></ActionDialog>}
        {reconcile && <ActionDialog title="Resolve onboarding identity" description={reconcile.snapshot.display_name} onClose={()=>setReconcile(null)} onSave={async form=>{await apiClient.post(`/hr/onboarding/batches/${batchId}/rows/${reconcile.id}`,{decision,reviewer_id:decision==='link'?value(form,'reviewer_id'):null,reason:value(form,'reason')});setReconcile(null);refresh('Identity decision recorded.');}}><Field label="Reconciliation decision"><select className={inputClass} value={decision} onChange={event=>setDecision(event.target.value as 'link'|'skip')}><option value="skip">Skip this employee in this cohort</option><option value="link">Verify an existing individual account</option></select></Field>{decision==='link' && <DirectoryPicker kind="accounts" name="reviewer_id" label="Verified existing account" />}<p className="text-sm text-gray-600">Names and email matches do not prove identity. Linking keeps existing account permissions and adds only Leave self-service grants. It creates no finance or approval rights; explicit account denials still apply. Correct missing facts in employee management and prepare a new cohort.</p></ActionDialog>}
        {action && <ActionDialog title={action.kind==='link'?'Issue private employee link':action.kind==='restore'?'Restore employee record':action.kind==='revoke-links'?'Revoke unused employee links':'Offboard employee'} description={action.account.display_name} onClose={()=>setAction(null)} onSave={async form=>{
            const target=action.account,reason=value(form,'reason');
            if(action.kind==='link'){const issued=await apiClient.post<{activation_url:string;expires_at:string}>(`/hr/onboarding/employees/${target.employee_id}/link`,{purpose:target.account_status==='active'&&target.onboarding_state==='ready'?'recovery':'activation',handover:value(form,'handover'),reason});setSecret(issued);refresh('Private link issued; previous unused links and sessions revoked.');}
            else {const result=await apiClient.post<{message:string}>(`/hr/onboarding/employees/${target.employee_id}/${action.kind}`,{reason});refresh(result.message);}setAction(null);
        }}>{action.kind==='link'?<><Field label="Verified handover method"><select name="handover" className={inputClass}><option value="in_person">In person after identity verification</option><option value="verified_email" disabled={!action.account.email}>Individually verified email</option></select></Field><p className="text-sm text-gray-600">Record how you verified the individual recipient. The private link is displayed once for handover; no email is sent automatically.</p></>:<p className="text-sm text-gray-600">{action.kind==='revoke-links'?'Revoke all unused links and end current sessions without changing account status. Issue a new individual link after verified handover if needed.':action.kind==='restore'?'Restore only after confirming reappointment. The account stays disabled; previous access scopes are not restored. Verify current placement/service facts and issue a fresh activation link separately.':'Disable the employee and linked account immediately. All sessions and unused links are revoked, along with scoped HR grants. Payroll identities, leave history and office appointment history are retained; review outstanding approvals and appointments separately.'}</p>}</ActionDialog>}
        {secret && <Modal title="Private employee activation link" onClose={()=>setSecret(null)}><div className="space-y-3"><p className="text-sm text-gray-600">Expires {formatDateTime(secret.expires_at)}. Give this link only to the verified recipient. Closing this view removes the displayed link; reissue if handover fails.</p><Field label="Private activation link"><textarea className={`${inputClass} break-all`} readOnly rows={4} value={secret.activation_url} /></Field><ModalActions><Button variant="secondary" onClick={()=>setSecret(null)}>Handover complete</Button></ModalActions></div></Modal>}
    </section>;
}
