import { MedicalTracking } from './MedicalTracking';
import type { MedicalTrackingSummary } from './MedicalTracking';
import { policyVersionLabel } from './policyVersionLabel';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiClient } from '../../lib/api';
import { formatDate } from '../../lib/date';
import { AustralianDateInput } from '../../components/AustralianDateInput';
import { Button, LoadingState } from '../../components/Ui';
import { ActionDialog, Field, inputClass } from './ManagementFields';
import { value } from './managementForm';
import { EmployeeDetails } from './EmployeeDetails';
import { EmployeeOnboarding } from './EmployeeOnboarding';
import { GovernmentFoundation } from './GovernmentFoundation';
import { GovernmentPayroll } from './GovernmentPayroll';
import { GovernmentWorkflowManagement } from './GovernmentWorkflowManagement';
import { reviewRecordLabel } from './reviewRecordNames';
import type { EmployeeProfile, WorkPattern } from './managementTypes';
import type { OrgDepartment } from './types';

type LegacyPolicy = {id:string;name:string;default_days:number;is_accruable:boolean;accrual_days_per_fortnight:string;max_balance:string|null;reset_period:string;is_active:boolean};
type Summary = {
    regime:string;account_type:string|null;restricted:boolean;as_of:string;reporting_manager:{name:string|null;description:string};
    legacy:null|{operational:boolean;leave_entitled:boolean;ineligible_reason:string|null;study_leave_start:string|null;study_leave_end:string|null;eligibility_note:string|null;join_date:string|null;daily_rate?:number|string|null;
        effective_balances:{leave_type_id:string;leave_type_name:string;year:number;balance:string;pending:string;source:string}[];
        balances:{id:string;leave_type_name:string;year:number;balance:string;pending:string}[];policies:LegacyPolicy[];settings:{accrual_anchor_date:string|null};application_counts:{status:string;count:number}[]};
    government:null|{medical_tracking:MedicalTrackingSummary;policy:null|{label:string;effective_from:string;effective_to:string};operational_status:string;
        activation:{status:string;enabled_codes:string[]};entitlements:{id:string;code:string;period_start:string;period_end:string;balance:string;held:string;available:string}[];
        application_counts:{status:string;count:number}[];applicability:{code:string;enabled:boolean;opening_certified:boolean;detail:string}[];
        route:{stages:{level:string;label?:string|null;approver_name:string|null;issue:string|null;conditional:boolean;applies_to:string[]}[]}};
    preparation:{key:string;label:string;status:string;detail:string}[];
};
export type EmployeeSection = 'arrangements'|'details'|'applications'|'prepare';
export type PreparationStep = 'identity'|'login'|'balances'|'reconciliation'|'activation';
const stages:Record<string,string>={division:'Divisional approver',department:'Head of Department',hr_verifier:'HR evidence verifier',relevant_secretary:'Relevant Secretary',minister:'Minister',chief_secretary:'Chief Secretary'};
const leaveName=(code:string)=>code.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
const steps:[PreparationStep,string][]=[['identity','1. Identity & appointment'],['login','2. Login & enrolment'],['balances','3. Service & balances'],['reconciliation','4. Retained leave reconciliation'],['activation','5. Activation & accrual']];

export function EmployeeLeaveWorkspace({profile,departments,patterns,central,section,step,onNavigate,onClose,onChanged}:{profile:EmployeeProfile;departments:OrgDepartment[];patterns:WorkPattern[];central:boolean;section:EmployeeSection;step:PreparationStep;onNavigate:(section:EmployeeSection,step?:PreparationStep)=>void;onClose:()=>void;onChanged:()=>Promise<void>}) {
    const id=profile.employee.id;
    const [summary,setSummary]=useState<Summary|null>(null),[error,setError]=useState(''),[version,setVersion]=useState(0),[dialog,setDialog]=useState<'adjust'|'eligibility'|null>(null);
    useEffect(()=>{let live=true;void apiClient.get<Summary>(`/hr/directory/${id}/leave-arrangements`).then(data=>{if(live){setSummary(data);setError('');}}).catch((err:Error)=>{if(live)setError(err.message);});return()=>{live=false;};},[id,version,profile,section,step]);
    async function refresh(){await onChanged();setVersion(v=>v+1);}
    const legacy=summary?.legacy,government=summary?.government;
    const state=summary?.regime==='government'?(summary.restricted?'Government Leave assigned':government?.activation.status==='active'?'Government Leave activated':government?.activation.status==='paused'?'Government Leave paused':'Preparing Government Leave'):summary?.account_type==='employee'?'Government preparation required':summary?'Existing leave workflow':'Checking leave arrangements…';
    return <div className="space-y-5">
        <div className="flex flex-wrap items-center justify-between gap-3"><div className="min-w-0"><Button variant="ghost" onClick={onClose}>← Employees</Button><h2 className="mt-2 break-words text-xl font-semibold text-gray-900">{reviewRecordLabel(profile.employee.display_name)}</h2><p className="break-words text-sm text-gray-600">{reviewRecordLabel(profile.employee.department_code||'Department unverified')} / {reviewRecordLabel(profile.employee.division_code||'Division unverified')} · {profile.employee.status}</p></div><span className="rounded-lg bg-blue-50 px-3 py-2 text-sm font-medium text-blue-900">{state}</span></div>
        <nav aria-label="Employee management" className="flex flex-wrap gap-2 border-b border-gray-200 pb-3">{([['arrangements','Leave arrangements'],['details','Employee details'],['applications','Applications'],...(central?[['prepare','Prepare Government Leave']]:[])] as [EmployeeSection,string][]).map(([key,label])=><Button key={key} variant={section===key?'primary':'secondary'} onClick={()=>onNavigate(key)}>{label}</Button>)}</nav>
        {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
        {!summary&&!error&&<LoadingState label="Loading current leave arrangements…"/>}
        {section==='arrangements'&&summary&&<>
            <div className="app-panel space-y-3 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">Current leave arrangements</h3><Button variant="secondary" onClick={()=>void refresh()}>Refresh arrangements</Button></div><p className="text-sm text-gray-700">{government?.operational_status||(summary.regime==='government'?'Government Leave is assigned. Central HR can confirm activation and balances.':'The existing leave workflow is assigned. Central HR can confirm balances and rules.')}</p><p className="text-sm text-gray-600">Reporting manager: <strong>{reviewRecordLabel(summary.reporting_manager.name||'Not assigned')}</strong>. {summary.reporting_manager.description}</p>
                {government?.policy&&<p className="text-sm text-gray-600">Published Government rules: <strong>{reviewRecordLabel(policyVersionLabel(government.policy.label,'published'))}</strong> · {formatDate(government.policy.effective_from)} to {formatDate(government.policy.effective_to)}. {summary.regime==='legacy'?'These rules have not replaced this employee’s existing calculations.':'Actual applications use the policy effective on their dates.'}</p>}
                {legacy&&<p className="text-sm text-gray-600">Existing leave eligibility: {legacy.leave_entitled?'Entitled':`Restricted${legacy.ineligible_reason?` — ${leaveName(legacy.ineligible_reason)}`:''}`}. Existing values and application history are retained.</p>}
            </div>
            {legacy&&<section className="app-panel space-y-3 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{summary.regime==='government'?'Retained existing balances':'Existing balances'} · {summary.as_of.slice(0,4)}</h3>{central&&summary.regime==='legacy'&&<div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>setDialog('eligibility')}>Edit existing eligibility</Button>{legacy.operational&&<Button variant="secondary" onClick={()=>setDialog('adjust')}>Adjust existing balance</Button>}</div>}</div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="py-2 pr-4">Leave</th><th className="pr-4">Balance</th><th className="pr-4">Pending</th><th>Record</th></tr></thead><tbody>{legacy.effective_balances.map(b=><tr key={b.leave_type_id} className="border-b border-gray-100"><td className="py-3 pr-4">{b.leave_type_name}</td><td className="pr-4">{b.balance}</td><td className="pr-4">{b.pending}</td><td className="text-xs text-gray-500">{b.source==='stored'?'Stored balance':'Existing rule default — no stored balance'}</td></tr>)}</tbody></table></div>{!legacy.effective_balances.length&&<p className="text-sm text-gray-500">No current existing balances are available.</p>}<details className="text-sm"><summary className="cursor-pointer text-gray-600">Stored balance history ({legacy.balances.length})</summary><div className="mt-3 space-y-2">{legacy.balances.map(b=><p key={b.id}>{b.year} · {b.leave_type_name}: {b.balance} · pending {b.pending}</p>)}</div></details><details className="text-sm"><summary className="cursor-pointer text-gray-600">Existing calculation settings</summary><div className="mt-3 space-y-2">{legacy.policies.map(p=><p key={p.id}>{p.name}: {p.is_accruable?`${p.accrual_days_per_fortnight} days per fortnight`:`${p.default_days} days`} · cap {p.max_balance??'none'} · reset {leaveName(p.reset_period)}{p.is_active?'':' · inactive'}</p>)}<p>Accrual anchor: {formatDate(legacy.settings.accrual_anchor_date)}</p><Link className="text-brand underline" to="/leave/settings?view=policies">Manage shared leave rules</Link></div></details></section>}
            {government&&(summary?.regime==='government'||government.entitlements.length>0)&&<section className="app-panel space-y-3 p-4"><h3 className="font-semibold">Government balances and activation</h3>{!government.entitlements.length&&<p className="text-sm text-gray-600">No certified Government balances recorded. Existing balances remain above.</p>}{government.entitlements.map(e=><div key={e.id} className="rounded-lg bg-gray-50 p-3 text-sm"><strong>{leaveName(e.code)}</strong> · {formatDate(e.period_start)} to {formatDate(e.period_end)}<p>Balance {e.balance} · held {e.held} · available {e.available}</p></div>)}<div className="space-y-2">{government.applicability.map(a=><p key={a.code} className="text-sm text-gray-600"><strong>{leaveName(a.code)}</strong>: {a.enabled?'Activation enabled':'Activation not enabled'} · {a.opening_certified?'Current opening certified':'Current opening not certified'}. {a.detail}</p>)}</div></section>}
            {government?.medical_tracking&&<MedicalTracking tracking={government.medical_tracking} legacy={summary.regime==='legacy'}/>}
            {government&&<details className="app-panel space-y-3 p-4"><summary className="cursor-pointer text-sm font-semibold">Government approval route · {formatDate(summary.as_of)}</summary><p className="text-sm text-gray-600">Dated office appointments apply when using Government Leave. They do not overwrite the nominated reporting manager above.</p><ol className="space-y-2">{government.route.stages.filter(s=>s.applies_to.some(code=>['recreation','medical','special'].includes(code))).map(s=><li key={s.level} className="rounded-lg border border-gray-200 p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{s.label||stages[s.level]||leaveName(s.level)}</strong><span>{reviewRecordLabel(s.approver_name||'Unassigned')}</span></div>{s.conditional&&<p className="mt-1 text-xs text-gray-500">Required for: {s.applies_to.map(leaveName).join(', ')}</p>}{s.issue&&<p className="mt-1 text-xs text-amber-800">{s.issue}</p>}</li>)}</ol><Link className="text-sm text-brand underline" to="/leave/settings?view=organisation">Manage organisation and approvers</Link></details>}
            {central&&summary.preparation.length>0&&<details className="app-panel p-4"><summary className="cursor-pointer text-sm font-semibold">Government preparation checks</summary><div className="mt-3 space-y-3">{summary.preparation.map(p=><div key={p.key} className="text-sm"><p><strong>{p.label}</strong> · {p.status==='ready'?'Recorded':p.status==='needs_review'?'Review required':'Preparation required'}</p><p className="mt-1 text-gray-600">{p.detail}</p></div>)}<Button onClick={()=>onNavigate('prepare')}>Continue preparation for this employee</Button></div></details>}
        </>}
        {section==='details'&&<EmployeeDetails embedded profile={profile} central={central} departments={departments} patterns={patterns} onClose={onClose} onChanged={refresh}/>}
        {section==='applications'&&<>{legacy&&<p className="text-sm text-gray-600">Retained existing applications: {legacy.application_counts.length?legacy.application_counts.map(c=>`${c.count} ${c.status}`).join(' · '):'none'}. These remain in Leave reports and retained Finance administration.</p>}{central?<GovernmentWorkflowManagement key={id} selectedEmployeeId={id} view="applications"/>:<p className="text-sm text-gray-600">Application review follows your assigned HR permissions. Open Approvals or Reports to view the records available to you.</p>}</>}
        {section==='prepare'&&central&&<><p className="text-sm text-gray-600">Prepare this employee in order. Publishing shared rules does not enrol or activate them. Applying enrolment stops existing leave submission; complete reconciliation and independent activation before they start using Government Leave. Submissions are paused during preparation.</p><label className="block text-sm font-medium">Preparation step<select className={`${inputClass} mt-2`} aria-label="Preparation step" value={step} onChange={e=>onNavigate('prepare',e.target.value as PreparationStep)}>{steps.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
            {step==='identity'&&<EmployeeDetails embedded profile={profile} central departments={departments} patterns={patterns} onClose={onClose} onChanged={refresh}/>}
            {step==='login'&&<EmployeeOnboarding key={id} departments={departments} selectedEmployeeId={id}/>}
            {step==='balances'&&<GovernmentFoundation key={id} selectedEmployeeId={id}/>}
            {step==='reconciliation'&&<GovernmentPayroll key={id} selectedEmployeeId={id}/>}
            {step==='activation'&&<GovernmentWorkflowManagement key={id} selectedEmployeeId={id} view="activation"/>}
        </>}
        {dialog&&legacy&&<ActionDialog title={dialog==='adjust'?'Adjust existing balance':'Edit existing leave eligibility'} description={profile.employee.display_name} onClose={()=>setDialog(null)} onSave={async data=>{
            if(dialog==='adjust'){const amount=Number(value(data,'amount'));if(!amount)throw new Error('Enter a non-zero adjustment.');await apiClient.post('/hr/adjustments',{employee_id:id,leave_type_id:value(data,'leave_type_id'),amount,reason:value(data,'reason')});}
            else {const entitled=value(data,'leave_entitled')==='true',studying=!entitled&&value(data,'ineligible_reason')==='study_leave';await apiClient.put(`/hr/employees/${id}`,{leave_entitled:entitled,ineligible_reason:entitled?null:value(data,'ineligible_reason'),study_leave_start:studying?value(data,'study_leave_start')||null:null,study_leave_end:studying?value(data,'study_leave_end')||null:null,eligibility_note:entitled?null:value(data,'eligibility_note')||null});}
            setDialog(null);await refresh();
        }}>{dialog==='adjust'?<><Field label="Leave type"><select name="leave_type_id" className={inputClass}>{legacy.policies.filter(p=>p.is_active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Days to add or subtract"><input name="amount" type="number" step="0.5" required className={inputClass}/></Field><p className="text-sm text-gray-600">The adjustment is recorded in the existing ledger with your reason. Pending applications remain protected.</p></>:<><Field label="Existing leave entitlement"><select name="leave_entitled" className={inputClass} defaultValue={String(legacy.leave_entitled)}><option value="true">Entitled</option><option value="false">Restricted</option></select></Field><Field label="Restriction reason"><select name="ineligible_reason" className={inputClass} defaultValue={legacy.ineligible_reason||'temporary'}><option value="study_leave">Study leave</option><option value="temporary">Temporary</option><option value="intern">Intern</option></select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Study leave from"><AustralianDateInput name="study_leave_start" className={inputClass} defaultValue={legacy.study_leave_start?.slice(0,10)||''}/></Field><Field label="Study leave through"><AustralianDateInput name="study_leave_end" className={inputClass} defaultValue={legacy.study_leave_end?.slice(0,10)||''}/></Field></div><Field label="Eligibility note"><input name="eligibility_note" className={inputClass} maxLength={300} defaultValue={legacy.eligibility_note||''}/></Field><p className="text-sm text-gray-600">Existing workflow eligibility only. Government eligibility follows verified appointment facts and the policy effective on requested dates.</p></>}</ActionDialog>}
    </div>;
}
