import {useEffect,useState} from 'react';
import {apiClient} from '../../lib/api';
import {Button,Pager,LoadingState} from '../../components/Ui';
import {ActionDialog,DirectoryPicker,Field,inputClass} from './ManagementFields';
import {value} from './managementForm';
import {useAuth} from '../../contexts/useAuth';
type Rules=Record<string,string|number>;
type Policy={id:string;label:string;effective_from:string;effective_to:string;status:string;rules:Rules;source_reference:string};
type Calendar={id:string;label:string;effective_from:string;effective_to:string;holidays:{date:string;name:string}[];supersedes_id:string|null;source_reference:string};
type Pattern={id:string;name:string;hours_per_day:string|null;working_weekdays:number[];approval_id:string|null};
type Configuration={defaults:Rules;codes:string[];policies:Policy[];calendars:Calendar[];patterns:Pattern[];source_reference:string};
export type GovernmentEntitlement={id:string;code:string;period_start:string;period_end:string;as_of:string;balance:string;held:string;available:string};
type Basis={id:string;effective_from:string;continuity_start:string;anniversary_method:string;schedule_mode:string;leap_day_method:string};
type Exclusion={id:string;start_date:string;end_date:string;kind:string};
type Roster={id:string;day:string;paid_hours:string;policy_days:string};
type EmployeeState={employee:{id:string;display_name:string;status:string;leave_policy_regime:string};service_summary:{issues:string[];period_start?:string;period_end?:string;credited_days?:number;ordinary_recreation_eligible?:string;temporary_recreation_eligible?:string};bases:Basis[];exclusions:Exclusion[];rosters:Roster[];entitlements:GovernmentEntitlement[]};
type Opening={id:string;display_name:string;code:string;amount:string;period_start:string;period_end:string;as_of:string;prepared_by:string;status:string;source_reference:string;payroll_reference:string;historical_snapshot:{leave_type_id:string;leave_type_name?:string;year:number;balance:string;pending:string}[]};
type Movement={id:string;code:string;kind:string;amount:string;effective_date:string;reason:string;source_reference:string};
type Evaluation={eligible_for_preview:boolean;issues:string[];requirements:string[];charge:string;scheduled_hours:number;snapshot_hash:string;required_offices:string[];segments:{date:string;charge:string;scheduled_hours:number;holiday_exempt:boolean;policy_version_id:string;calendar_id:string}[]};
type Kind='policy'|'calendar'|'pattern'|'publish'|'basis'|'exclusion'|'withdraw'|'roster'|'opening'|'certify'|'correction'|'reverse';
type Target=Policy|Calendar|Pattern|Exclusion|Roster|Opening|Movement;
const label=(code:string)=>code.replace(/_/g,' ').replace(/^./,s=>s.toUpperCase());
const today=()=>new Date(Date.now()+12*3600000).toISOString().slice(0,10);
const titles:Record<Kind,string>={policy:'Prepare government policy version',calendar:'Publish approved calendar',pattern:'Verify weekly conversion',publish:'Publish government policy',basis:'Certify continuous-service basis',exclusion:'Record service exclusion',withdraw:'Withdraw incorrect exclusion',roster:'Publish roster day',opening:'Prepare opening preview',certify:'Certify opening balance',correction:'Record certified correction',reverse:'Reverse ledger movement'};
const ruleLabels:Record<string,string>={ordinary_recreation_months:'Ordinary recreation qualifying months',temporary_recreation_months:'Temporary recreation qualifying months',recreation_annual_days:'Recreation annual policy days',recreation_cap_days:'Recreation cap policy days',recreation_notice_days:'Recreation calendar notice days',medical_annual_days:'Medical annual policy days',special_annual_days:'Special annual policy days',medical_uncertified_occasions:'Medical uncertified occasions'};
function TextField({name,label:caption,initial,min=5}:{name:string;label:string;initial?:string;min?:number}){return <Field label={caption}><input name={name} className={inputClass} required minLength={min} maxLength={500} defaultValue={initial}/></Field>;}
function DateField({name,label:caption,initial}:{name:string;label:string;initial?:string}){return <Field label={caption}><input name={name} type="date" className={inputClass} required defaultValue={initial}/></Field>;}
function AmountField({name,label:caption,initial,min,max}:{name:string;label:string;initial?:string;min?:number;max?:number}){return <Field label={caption}><input name={name} type="number" step="0.000001" min={min} max={max} className={inputClass} required defaultValue={initial}/></Field>;}
export function GovernmentFoundation(){
 const {user}=useAuth();const [tab,setTab]=useState<'configuration'|'employee'|'openings'>('configuration'),[config,setConfig]=useState<Configuration|null>(null),[employeeId,setEmployeeId]=useState(''),[employee,setEmployee]=useState<EmployeeState|null>(null),[evaluation,setEvaluation]=useState<Evaluation|null>(null);
 const [openings,setOpenings]=useState<{openings:Opening[];total:number}>({openings:[],total:0}),[openingPage,setOpeningPage]=useState(0),[ledger,setLedger]=useState<{movements:Movement[];total:number}>({movements:[],total:0}),[ledgerPage,setLedgerPage]=useState(0),[dialog,setDialog]=useState<{kind:Kind;target?:Target;eventKey:string}|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
 useEffect(()=>{let live=true;void apiClient.get<Configuration>('/hr/government/configuration').then(r=>{if(live)setConfig(r);}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[version]);
 useEffect(()=>{let live=true;void apiClient.get<typeof openings>(`/hr/government/openings?page=${openingPage+1}`).then(r=>{if(live)setOpenings(r);}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[openingPage,version]);
 useEffect(()=>{if(!employeeId)return;let live=true;void Promise.all([apiClient.get<EmployeeState>(`/hr/government/employees/${employeeId}`),apiClient.get<typeof ledger>(`/hr/government/employees/${employeeId}/ledger?page=${ledgerPage+1}`)]).then(([person,movements])=>{if(live){setEmployee(person);setLedger(movements);}}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[employeeId,ledgerPage,version]);
 function show(kind:Kind,target?:Target){setError('');setDialog({kind,target,eventKey:crypto.randomUUID()});}
 function refreshed(message:string){setNotice(message);setEvaluation(null);setVersion(v=>v+1);}
 async function save(form:FormData){if(!dialog||!config)return;const reason=value(form,'reason'),base={reason,source_reference:value(form,'source_reference')},root=`/hr/government/employees/${employeeId}`;
  switch(dialog.kind){
   case 'policy':{const rules={...config.defaults};for(const key of Object.keys(rules))rules[key]=typeof rules[key]==='number'?Number(value(form,key)):value(form,key);await apiClient.post('/hr/government/policies',{...base,label:value(form,'label'),effective_from:value(form,'effective_from'),effective_to:value(form,'effective_to'),rules});break;}
   case 'calendar':{const holidays=value(form,'holidays').split('\n').filter(line=>line.trim()).map(line=>{const [date,...name]=line.split('|');if(!name.length)throw new Error('Use one YYYY-MM-DD | Holiday name per line.');return {date:date.trim(),name:name.join('|').trim()};});await apiClient.post('/hr/government/calendars',{...base,label:value(form,'label'),effective_from:value(form,'effective_from'),effective_to:value(form,'effective_to'),holidays,...(dialog.target?{supersedes_id:dialog.target.id}:{})});break;}
   case 'pattern':await apiClient.post('/hr/government/patterns/approve',{...base,work_pattern_id:dialog.target?.id,conversion_confirmed:form.has('conversion_confirmed')});break;
   case 'publish':await apiClient.post(`/hr/government/policies/${dialog.target?.id}/publish`,{reason});break;
   case 'basis':await apiClient.post(`${root}/basis`,{...base,effective_from:value(form,'effective_from'),continuity_start:value(form,'continuity_start'),anniversary_method:value(form,'anniversary_method'),leap_day_method:value(form,'leap_day_method'),schedule_mode:value(form,'schedule_mode')});break;
   case 'exclusion':await apiClient.post(`${root}/exclusion`,{...base,start_date:value(form,'start_date'),end_date:value(form,'end_date'),kind:value(form,'kind')});break;
   case 'withdraw':await apiClient.post(`${root}/withdraw-exclusion`,{...base,exclusion_id:dialog.target?.id});break;
   case 'roster':await apiClient.post(`${root}/roster`,{...base,day:value(form,'day'),paid_hours:value(form,'paid_hours'),policy_days:value(form,'policy_days'),...(dialog.target?{supersedes_id:dialog.target.id}:{})});break;
   case 'opening':await apiClient.post(`${root}/openings`,{...base,code:value(form,'code'),amount:value(form,'amount'),policy_version_id:value(form,'policy_version_id'),period_start:value(form,'period_start'),period_end:value(form,'period_end'),as_of:value(form,'as_of'),payroll_reference:value(form,'payroll_reference')});break;
   case 'certify':await apiClient.post(`/hr/government/openings/${dialog.target?.id}/certify`,{reason});break;
   case 'correction':await apiClient.post(`${root}/corrections`,{...base,entitlement_id:value(form,'entitlement_id'),amount:value(form,'amount'),effective_date:value(form,'effective_date'),event_key:dialog.eventKey});break;
   case 'reverse':await apiClient.post(`${root}/movements/${dialog.target?.id}/reverse`,{...base,effective_date:value(form,'effective_date')});break;
  }
  setDialog(null);refreshed(dialog.kind==='opening'?'Opening preview saved. No balance posted; a different central HR officer must certify it.':'Verified foundation change saved. Refresh the calculation before using it.');
 }
 if(!config)return error?<p role="alert" className="text-sm text-red-700">{error}</p>:<LoadingState label="Loading government foundations…"/>;
 const calendarTarget=dialog?.kind==='calendar'?dialog.target as Calendar|undefined:undefined,rosterTarget=dialog?.kind==='roster'?dialog.target as Roster|undefined:undefined;
 return <section className="app-panel space-y-5 p-4 sm:p-5"><div><h3 className="text-lg font-semibold">Government leave foundations</h3><p className="mt-1 text-sm text-gray-600">Publish approved rules and calendars, verify service and schedules, then certify opening entitlements.</p></div><p className="rounded-lg bg-blue-50 p-3 text-sm text-blue-900">Calculation and reconciliation workspace. Government requests remain closed until the division → Head of Department → Chief Secretary workflow is ready. Historical balances remain separate.</p>
  <nav aria-label="Government foundation views" className="flex flex-wrap gap-2">{([['configuration','Policy & calendars'],['employee','Employee calculation'],['openings','Opening certification']] as const).map(([key,text])=><Button key={key} variant={tab===key?'primary':'secondary'} onClick={()=>setTab(key)}>{text}</Button>)}</nav>
  {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="rounded-lg bg-green-50 p-3 text-sm text-green-800">{notice}</p>}
  {tab==='configuration'&&<><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="font-semibold">Effective policy versions</h4><Button onClick={()=>show('policy')}>Prepare policy version</Button></div><p className="text-sm text-gray-600">Review defaults: ordinary recreation 3 months; temporary 12 months; recreation 20 days / cap 60; Medical one 10-day pool; Special 3 days. Publication needs an approved authority reference and does not activate accrual.</p>
   {config.policies.map(p=><article key={p.id} className="space-y-2 rounded-lg border border-gray-200 p-3"><h5 className="font-semibold">{p.label} · {p.status}</h5><p className="text-sm">{p.effective_from} to {p.effective_to}</p><p className="break-words text-sm text-gray-600">{p.source_reference}</p><p className="text-sm">Recreation: {p.rules.ordinary_recreation_months}/{p.rules.temporary_recreation_months} months · {p.rules.recreation_annual_days} annual days · {p.rules.recreation_cap_days} cap · {p.rules.recreation_notice_days} days' notice. Medical {p.rules.medical_annual_days}; Special {p.rules.special_annual_days}.</p>{p.status==='draft'&&<Button variant="secondary" onClick={()=>show('publish',p)}>Publish {p.label}</Button>}</article>)}
   <div className="flex flex-wrap items-center justify-between gap-2"><h4 className="font-semibold">Approved holiday calendars</h4><Button onClick={()=>show('calendar')}>Publish calendar</Button></div><p className="text-sm text-gray-600">Use approved actual/observed Gazette dates. Resolve collisions explicitly. Replacements retain history and require recalculation; no calendar is assumed.</p>
   {config.calendars.map(c=><article key={c.id} className="space-y-2 rounded-lg border border-gray-200 p-3"><h5 className="font-semibold">{c.label}{config.calendars.some(n=>n.supersedes_id===c.id)?' · superseded':''}</h5><p className="text-sm">{c.effective_from} to {c.effective_to} · {c.holidays.length} holidays</p><p className="break-words text-sm text-gray-600">{c.source_reference}</p>{c.holidays.map(h=><p key={h.date} className="text-sm">{h.date} · {h.name}</p>)}{!config.calendars.some(n=>n.supersedes_id===c.id)&&<Button variant="secondary" onClick={()=>show('calendar',c)}>Replace {c.label}</Button>}</article>)}
   <h4 className="font-semibold">Weekly schedule conversions</h4><p className="text-sm text-gray-600">Verify the signed five-day schedule and one-policy-day conversion. Other schedules use published roster days, including off-duty dates, with approved hours and charges.</p>{config.patterns.map(p=><article key={p.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-gray-200 p-3"><div><h5 className="font-semibold">{p.name}</h5><p className="text-sm text-gray-600">{p.working_weekdays.length} days/week · {p.hours_per_day||'Unknown'} paid hours/day · {p.approval_id?'Verified conversion':'Unverified conversion'}</p></div>{!p.approval_id&&<Button variant="secondary" onClick={()=>show('pattern',p)}>Verify {p.name}</Button>}</article>)}</>}
  {tab==='employee'&&<><form className="space-y-3" onSubmit={e=>{e.preventDefault();const id=value(new FormData(e.currentTarget),'employee_id');if(!id){setError('Choose an employee.');return;}setEmployeeId(id);setEmployee(null);setLedgerPage(0);setEvaluation(null);setError('');setVersion(v=>v+1);}}><DirectoryPicker name="employee_id" label="Employee for calculation"/><Button type="submit">Load employee foundations</Button></form>
   {employee&&<><div className="space-y-2 border-t border-gray-200 pt-4"><h4 className="text-lg font-semibold">{employee.employee.display_name}</h4><p className="text-sm">{employee.employee.status} · {employee.employee.leave_policy_regime} regime</p><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>show('basis')}>Certify service basis</Button><Button variant="secondary" onClick={()=>show('exclusion')}>Record service exclusion</Button><Button variant="secondary" onClick={()=>show('roster')}>Publish roster day</Button><Button onClick={()=>show('opening')}>Prepare opening balance</Button></div>
    {employee.service_summary.issues.length?<ul className="list-disc pl-5 text-sm text-amber-800">{employee.service_summary.issues.map(i=><li key={i}>{i}</li>)}</ul>:<p className="text-sm text-gray-600">Service year: {employee.service_summary.period_start} to {employee.service_summary.period_end} · {employee.service_summary.credited_days} credited calendar days. Recreation dates: ordinary {employee.service_summary.ordinary_recreation_eligible}; temporary {employee.service_summary.temporary_recreation_eligible}.</p>}
    {employee.bases.map(b=><p key={b.id} className="text-sm text-gray-600">Basis from {b.effective_from}: continuity {b.continuity_start} · {label(b.anniversary_method)} · {b.schedule_mode} · leap convention {b.leap_day_method}.</p>)}
    {employee.exclusions.map(x=><article key={x.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-gray-200 p-3"><p className="text-sm">{label(x.kind)}: {x.start_date} to {x.end_date}</p><Button variant="secondary" onClick={()=>show('withdraw',x)}>Withdraw incorrect exclusion</Button></article>)}
    {employee.rosters.map(r=><article key={r.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-gray-200 p-3"><p className="text-sm">{r.day}: {r.paid_hours} paid hours · {r.policy_days} policy days</p><Button variant="secondary" onClick={()=>show('roster',r)}>Replace roster day</Button></article>)}
   </div><BalanceCards entitlements={employee.entitlements}/>
   <form className="space-y-3 rounded-lg border border-gray-200 p-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');void apiClient.post<Evaluation>(`/hr/government/employees/${employeeId}/evaluate`,{code:value(f,'code'),start_date:value(f,'start_date'),end_date:value(f,'end_date'),certificate_available:f.has('certificate_available'),justification_available:f.has('justification_available')}).then(setEvaluation).catch((err:Error)=>setError(err.message)).finally(()=>setBusy(false));}}><h4 className="font-semibold">Explain a leave calculation</h4><div className="grid gap-3 sm:grid-cols-3"><Field label="Government leave type"><select name="code" className={inputClass}>{config.codes.map(c=><option key={c} value={c}>{label(c)}</option>)}</select></Field><DateField name="start_date" label="Leave starts"/><DateField name="end_date" label="Leave ends"/></div><label className="block text-sm"><input type="checkbox" name="certificate_available"/> Medical certificate available for review</label><label className="block text-sm"><input type="checkbox" name="justification_available"/> Special-leave justification available</label><p className="text-sm text-gray-600">Preview only. The server uses today's Nauru date for notice and calculates the charge. Evidence is reviewed at submission; forecast accrual cannot be spent.</p><Button type="submit" loading={busy}>Evaluate leave dates</Button></form>
   {evaluation&&<article className="space-y-3 rounded-lg border border-gray-200 p-4"><h4 className="font-semibold">{evaluation.eligible_for_preview?'Calculation ready for review':'Calculation needs attention'} · {evaluation.charge} policy days</h4><p className="text-sm">Scheduled hours: {evaluation.scheduled_hours}. Employee submission requires independent activation under Government workflow.</p>{evaluation.issues.length>0&&<ul className="list-disc space-y-1 pl-5 text-sm text-amber-800">{evaluation.issues.map(i=><li key={i}>{i}</li>)}</ul>}{evaluation.requirements.map(r=><p key={r} className="text-sm text-gray-600">{r}</p>)}<p className="text-sm text-gray-600">Required offices: {evaluation.required_offices.map(label).join(' → ')}. Further statutory approvals depend on the case.</p><details><summary className="cursor-pointer text-sm font-semibold">Daily charges and governing versions</summary><div className="mt-2 max-h-80 space-y-2 overflow-y-auto">{evaluation.segments.map(s=><div key={s.date} className="break-words rounded border border-gray-200 p-2 text-xs"><p>{s.date}: {s.charge} policy days · {s.scheduled_hours} hours{s.holiday_exempt?' · holiday exempt':''}</p><p>Policy {s.policy_version_id} · Calendar {s.calendar_id}</p></div>)}</div><p className="mt-2 break-all text-xs text-gray-500">Calculation reference {evaluation.snapshot_hash}</p></details></article>}
   <div className="flex flex-wrap justify-between gap-2"><h4 className="font-semibold">Government ledger movements</h4><Button variant="secondary" disabled={!employee.entitlements.length} onClick={()=>show('correction')}>Record certified correction</Button></div><p className="text-sm text-gray-600">Opening plus movements equals the committed balance; holds reduce availability. Corrections and reversals append history and protect held entitlement.</p>
   {ledger.movements.map(m=><article key={m.id} className="space-y-1 rounded-lg border border-gray-200 p-3"><h5 className="font-semibold">{label(m.code)} · {label(m.kind)} · {m.amount} days</h5><p className="text-sm">{m.effective_date} · {m.source_reference}</p><p className="break-words text-sm text-gray-600">{m.reason}</p>{['correction','grant','accrual','expiry'].includes(m.kind)&&<Button variant="secondary" onClick={()=>show('reverse',m)}>Reverse movement</Button>}</article>)}<Pager page={ledgerPage} pageCount={Math.ceil(ledger.total/50)} total={ledger.total} pageSize={50} setPage={setLedgerPage}/>
   </>}
  </>}
  {tab==='openings'&&<><h4 className="font-semibold">Opening balance certification</h4><p className="text-sm text-gray-600">HR prepares an explicit cutover amount with personnel and Salary Unit references. A different central officer certifies it. Historical Special and split sick balances are not reduced or merged automatically.</p><Button variant="secondary" onClick={()=>setVersion(v=>v+1)}>Refresh certification queue</Button>{openings.openings.map(o=><article key={o.id} className="space-y-2 rounded-lg border border-gray-200 p-3"><h5 className="font-semibold">{o.display_name} · {label(o.code)} · {o.amount} days</h5><p className="text-sm">{o.period_start} to {o.period_end} · opening {o.as_of} · {o.status}</p><p className="break-words text-sm text-gray-600">HR: {o.source_reference} · Salary Unit: {o.payroll_reference}</p><details><summary className="cursor-pointer text-sm">Preserved historical balance snapshot</summary>{o.historical_snapshot.length?o.historical_snapshot.map(r=><p key={`${r.leave_type_id}-${r.year}`} className="break-all text-xs">{r.year} · {r.leave_type_name||'Historical leave type'} · balance {r.balance} · pending {r.pending}</p>):<p className="text-sm text-gray-500">No historical balance rows.</p>}</details>{o.status==='preview'&&(o.prepared_by===String(user?.id)?<p className="text-sm text-gray-500">A different central HR officer must certify your preview.</p>:<Button onClick={()=>show('certify',o)}>Certify {o.display_name} {label(o.code)}</Button>)}</article>)}<Pager page={openingPage} pageCount={Math.ceil(openings.total/50)} total={openings.total} pageSize={50} setPage={setOpeningPage}/></>}
  {dialog&&<ActionDialog title={titles[dialog.kind]} onClose={()=>setDialog(null)} onSave={save}>
   {dialog.kind==='policy'&&<><TextField name="label" label="Policy version name" min={3}/><DateField name="effective_from" label="Effective from"/><DateField name="effective_to" label="Effective through"/><div className="grid gap-3 sm:grid-cols-2">{Object.entries(config.defaults).map(([key,v])=><Field key={key} label={ruleLabels[key]||label(key)}><input name={key} type="number" min="0" step={typeof v==='number'?'1':'0.000001'} className={inputClass} defaultValue={v} required/></Field>)}</div><p className="text-sm text-gray-600">Only typed parameters are accepted. Fortnightly accrual remains off until anchor, proration and reconciliation are approved.</p></>}
   {dialog.kind==='calendar'&&<><TextField name="label" label="Calendar name" min={3} initial={calendarTarget?`${calendarTarget.label} corrected`:''}/><DateField name="effective_from" label="Effective from" initial={calendarTarget?.effective_from}/><DateField name="effective_to" label="Effective through" initial={calendarTarget?.effective_to}/><Field label="Gazetted actual and observed holidays"><textarea name="holidays" className={inputClass} rows={6} maxLength={15000} placeholder="2026-10-26 | Holiday name (one per line)" defaultValue={calendarTarget?.holidays.map(h=>`${h.date} | ${h.name}`).join('\n')}/></Field><p className="text-sm text-gray-600">A verified calendar may have no holidays in its coverage. Replacements require exactly the predecessor's coverage.</p></>}
   {dialog.kind==='pattern'&&<label className="block text-sm"><input type="checkbox" name="conversion_confirmed" required/> I verified one policy day for each scheduled day in this five-day, seven/eight-paid-hour pattern, including the approved annual quantum and cap.</label>}
   {dialog.kind==='publish'&&<p className="text-sm text-gray-600">Publish this reviewed schedule under its approved authority. Published dates cannot overlap and the version is immutable.</p>}
   {dialog.kind==='basis'&&<><DateField name="effective_from" label="Basis effective from" initial={today()}/><DateField name="continuity_start" label="Verified continuous-service start"/><Field label="Approved anniversary treatment"><select name="anniversary_method" className={inputClass} required defaultValue=""><option value="" disabled>Choose signed determination</option><option value="calendar">Fixed calendar anniversary</option><option value="pause_exclusions">Move anniversary for excluded service</option></select></Field><Field label="Approved leap-day anniversary"><select name="leap_day_method" className={inputClass} required defaultValue=""><option value="" disabled>Choose signed determination</option><option value="feb28">28 February in non-leap years</option><option value="mar1">1 March in non-leap years</option></select></Field><Field label="Verified schedule source"><select name="schedule_mode" className={inputClass}><option value="weekly">Approved weekly pattern</option><option value="roster">Published roster days</option></select></Field><p className="text-sm text-gray-600">A basis does not fill gaps in appointment/category/credit history. A resignation/reappointment break requires a new continuity basis.</p></>}
   {dialog.kind==='exclusion'&&<><DateField name="start_date" label="Exclusion starts"/><DateField name="end_date" label="Exclusion ends"/><Field label="Service effect"><select name="kind" className={inputClass}><option value="lwop">LWOP: pause credited service</option><option value="other_excluded">Other signed excluded interval</option><option value="continuity_break">Break in employment continuity</option></select></Field></>}
   {dialog.kind==='withdraw'&&<p className="text-sm text-gray-600">Withdraw the incorrect exclusion with correction authority. Its original record remains and affected calculations need review.</p>}
   {dialog.kind==='roster'&&<><DateField name="day" label="Roster date" initial={rosterTarget?.day}/><AmountField name="paid_hours" label="Paid scheduled hours" initial={rosterTarget?.paid_hours} min={0} max={24}/><AmountField name="policy_days" label="Approved policy-day charge" initial={rosterTarget?.policy_days} min={0} max={2}/><p className="text-sm text-gray-600">Publish zero hours and zero policy days for off-duty dates. Non-standard/overnight shift attribution needs a signed per-date conversion; hours do not determine policy days automatically.</p></>}
   {dialog.kind==='opening'&&<><Field label="Opening leave type"><select name="code" className={inputClass}>{['recreation','medical','special'].map(c=><option key={c} value={c}>{label(c)}</option>)}</select></Field><Field label="Governing published policy"><select name="policy_version_id" className={inputClass} required><option value="">Choose policy</option>{config.policies.filter(p=>p.status==='published').map(p=><option key={p.id} value={p.id}>{p.label} · {p.effective_from} to {p.effective_to}</option>)}</select></Field><DateField name="period_start" label="Certified service year starts" initial={employee?.service_summary.period_start}/><DateField name="period_end" label="Certified service year ends" initial={employee?.service_summary.period_end}/><DateField name="as_of" label="Cutover balance date" initial={today()}/><AmountField name="amount" label="Certified cutover policy days" min={0}/><TextField name="payroll_reference" label="Salary Unit reconciliation reference"/><p className="text-sm text-gray-600">Include the agreed treatment of past usage and future leave. Preview does not create default grants, migrate pending applications or overwrite historical balances.</p></>}
   {dialog.kind==='certify'&&<p className="text-sm text-gray-600">Confirm the personnel/Salary Unit sources, historical snapshot and cutover amount. Certification posts once; changed facts reject the preview.</p>}
   {dialog.kind==='correction'&&<><Field label="Certified entitlement period"><select name="entitlement_id" className={inputClass} required>{employee?.entitlements.map(e=><option key={e.id} value={e.id}>{label(e.code)} · {e.period_start} to {e.period_end}</option>)}</select></Field><AmountField name="amount" label="Signed correction policy days"/><DateField name="effective_date" label="Correction effective date" initial={today()}/></>}
   {dialog.kind==='reverse'&&<><p className="text-sm text-gray-600">Append the exact opposite movement once, retaining the original and protecting existing holds.</p><DateField name="effective_date" label="Reversal effective date" initial={today()}/></>}
   {!['publish','certify'].includes(dialog.kind)&&<TextField name="source_reference" label="Authority or source reference"/>}
  </ActionDialog>}
 </section>;
}
export function BalanceCards({entitlements}:{entitlements:GovernmentEntitlement[]}){return <div className="space-y-3"><h4 className="font-semibold">Certified government entitlements</h4>{!entitlements.length?<p className="text-sm text-gray-500">No certified opening entitlement yet. Historical balances do not become government allowances automatically.</p>:<div className="grid gap-3 sm:grid-cols-3">{entitlements.map(e=><article key={e.id} className="rounded-lg border border-blue-100 bg-blue-50 p-3"><h5 className="font-semibold">{label(e.code)}</h5><p className="mt-1 text-2xl font-bold text-brand">{e.available.replace(/\.0+$/,'').replace(/(\.\d*?)0+$/,'$1')}</p><p className="text-sm text-gray-600">policy days available · {e.held} held</p><p className="text-xs text-gray-600">Committed balance {e.balance} · {e.period_start} to {e.period_end} · certified from {e.as_of}</p></article>)}</div>}</div>;}
export function GovernmentPersonalBalances({employeeId}:{employeeId:string}){const [entitlements,setEntitlements]=useState<GovernmentEntitlement[]>([]),[error,setError]=useState('');useEffect(()=>{let live=true;void apiClient.get<{entitlements:GovernmentEntitlement[]}>(`/hr/government/employees/${employeeId}`).then(r=>{if(live)setEntitlements(r.entitlements);}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[employeeId]);return <section className="app-panel p-5">{error?<p role="alert" className="text-sm text-red-700">Certified balances unavailable: {error}</p>:<BalanceCards entitlements={entitlements}/>}</section>;}
