import { formatDate } from '../../lib/date';
import { AustralianDateInput } from '../../components/AustralianDateInput';
import {useEffect,useState} from 'react';
import {apiClient} from '../../lib/api';
import {useAuth} from '../../contexts/useAuth';
import {Button,LoadingState,Pager} from '../../components/Ui';
import {ActionDialog,Field,inputClass} from './ManagementFields';
import {value} from './managementForm';
const root='/hr/government/payroll';
const label=(s:string)=>s.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
type Line={key:string;employee_id:string;employee_name:string;payroll_id:string;code:string;kind:string;date:string;salary_percent:string|null;scheduled_hours:string;policy_days:string;payable_aud:string};
type Register={id:string;version:number;period_start:string;period_end:string;prepared_by:string;snapshot_hash:string;supersedes_id:string|null;receipt_reference:string|null;latest:boolean;line_count:number;change_count:number;snapshot?:{lines:Line[];totals:(Line&{rows:number})[];changes:{key:string;action:string;before:Line|null;after:Line|null}[]}};
async function download(path:string,name:string){const blob=await apiClient.getBlob(path),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Source({name='source_reference',title='Signed source reference'}:{name?:string;title?:string}){return <Field label={title}><input name={name} className={inputClass} required minLength={5} maxLength={500}/></Field>;}
function Checksum({hash}:{hash:string}){return <details className="text-xs text-gray-500"><summary className="cursor-pointer">Record verification</summary><p className="mt-2 break-all">SHA-256: {hash}</p></details>;}
export function GovernmentPayroll() {
 const {user}=useAuth();
 const [version,setVersion]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [registers,setRegisters]=useState<Register[]>([]),[registerPage,setRegisterPage]=useState(0),[registerTotal,setRegisterTotal]=useState(0),[detail,setDetail]=useState<Register|null>(null),[linePage,setLinePage]=useState(0);
 const [payrollStart,setPayrollStart]=useState(''),[payrollEnd,setPayrollEnd]=useState(''),[payrollPreview,setPayrollPreview]=useState<{issues:string[];identities:Record<string,{name:string;ids:string[];payroll_id:string|null}>;line_count:number}|null>(null);
 const [dialog,setDialog]=useState<{kind:'register'|'payroll-receipt';key:string;register?:Register}|null>(null);
 useEffect(()=>{let live=true;void apiClient.get<{registers:Register[];total:number}>(`${root}/registers?page=${registerPage+1}`).then(r=>{if(live){setRegisters(r.registers);setRegisterTotal(r.total);}}).catch((e:Error)=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[registerPage,version]);
 function show(kind:'register'|'payroll-receipt',other:{register?:Register}={}){if(kind==='register'){setPayrollPreview(null);setPayrollStart('');setPayrollEnd('');}setDialog({kind,key:crypto.randomUUID(),...other});}
 async function run(work:()=>Promise<void>){setError('');setBusy(true);try{await work();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(data:FormData){if(!dialog)return;const reason=value(data,'reason');
  if(dialog.kind==='register'){const batch=await apiClient.post<Register>(`${root}/registers`,{batch_id:dialog.key,period_start:value(data,'period_start'),period_end:value(data,'period_end'),source_reference:value(data,'source_reference'),reason,payroll_ids:Object.fromEntries([...data.entries()].filter(([key])=>key.startsWith('payroll_id_')).map(([key,v])=>[key.slice(11),String(v)]))});setDetail(batch);setLinePage(0);}
  if(dialog.kind==='payroll-receipt'&&dialog.register)await apiClient.post(`${root}/registers/${dialog.register.id}/receipt`,{reference:value(data,'reference'),snapshot_hash:dialog.register.snapshot_hash,reason,corrections_reconciled:data.has('corrections_reconciled')});
  setDialog(null);setVersion(v=>v+1);if(dialog.kind==='payroll-receipt'&&dialog.register)setDetail(await apiClient.get<Register>(`${root}/registers/${dialog.register.id}`));
 }
 const titles = {register:'Prepare payroll instructions','payroll-receipt':'Record Salary Unit reconciliation'};
 return <div className="min-w-0 space-y-5">
  <p className="text-sm leading-6 text-gray-600">Prepare the approved leave instructions for a payroll period, review any changes, and record Salary Unit reconciliation.</p>
  {error&&<p role="alert" className="break-words rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  {(busy||loading)&&<LoadingState label="Loading payroll instructions…"/>}
   <section className="app-panel space-y-4 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h4 className="font-semibold">Payroll periods</h4><Button onClick={()=>show('register')}>Prepare instructions</Button></div><p className="text-sm text-gray-600">Each version replaces its exact period. Reconcile corrections against the previous version before recording Salary Unit's receipt. Full, partial and unpaid salary instructions are separate.</p>
   {!registers.length&&<p className="text-sm text-gray-500">No payroll instructions have been prepared.</p>}{registers.map(r=><article key={r.id} className="space-y-3 rounded-xl border border-gray-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h5 className="font-semibold">{formatDate(r.period_start)} to {formatDate(r.period_end)} · Version {r.version}</h5><span className="rounded bg-blue-50 px-2 py-1 text-xs text-blue-900">{r.latest?'Current period version':'Superseded'}</span></div><p className="text-sm">{r.line_count} instructions · {r.change_count} changed rows · {r.receipt_reference?`Received: ${r.receipt_reference}`:'Awaiting Salary Unit reconciliation'}</p><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>void run(async()=>{setDetail(await apiClient.get<Register>(`${root}/registers/${r.id}`));setLinePage(0);})}>Review register</Button><Button variant="secondary" onClick={()=>void run(()=>download(`${root}/registers/${r.id}/export?format=csv`,`leave-payroll-${r.id}-v${r.version}.csv`))}>Download CSV</Button><Button variant="secondary" onClick={()=>void run(()=>download(`${root}/registers/${r.id}/export?format=json`,`leave-payroll-${r.id}-v${r.version}.json`))}>Download exact JSON</Button>{r.version>1&&<Button variant="secondary" onClick={()=>void run(()=>download(`${root}/registers/${r.id}/export?format=corrections`,`leave-corrections-${r.id}-v${r.version}.csv`))}>Download corrections</Button>}{r.latest&&!r.receipt_reference&&r.prepared_by!==String(user?.id)&&<Button onClick={()=>show('payroll-receipt',{register:r})}>Record reconciliation</Button>}</div><Checksum hash={r.snapshot_hash}/></article>)}<Pager page={registerPage} total={registerTotal} pageSize={50} pageCount={Math.ceil(registerTotal/50)} setPage={setRegisterPage}/></section>
   {detail?.snapshot&&<section className="app-panel min-w-0 space-y-4 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="font-semibold">Register version {detail.version} · {detail.snapshot.lines.length} dated instructions</h4><Button variant="secondary" onClick={()=>setDetail(null)}>Close register</Button></div><Checksum hash={detail.snapshot_hash}/><div className="max-w-full overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Employee / Payroll ID','Date / type','Instruction','Salary','Hours / days','Payable AUD'].map(h=><th key={h} className="whitespace-nowrap px-3 py-2">{h}</th>)}</tr></thead><tbody>{detail.snapshot.lines.slice(linePage*50,(linePage+1)*50).map(l=><tr key={l.key} className="border-t border-gray-100"><td className="px-3 py-2">{l.employee_name}<br/><span className="text-xs text-gray-500">{l.payroll_id}</span></td><td className="px-3 py-2">{formatDate(l.date)}<br/>{label(l.code)}</td><td className="px-3 py-2">{label(l.kind)}</td><td className="px-3 py-2">{l.salary_percent===null?'—':`${Number(l.salary_percent)}%`}</td><td className="px-3 py-2">{Number(l.scheduled_hours)}h / {Number(l.policy_days)}d</td><td className="px-3 py-2">{l.kind==='absence'||l.kind==='attendance_instruction'?'Salary Unit calculates':l.payable_aud}</td></tr>)}</tbody></table></div><Pager page={linePage} total={detail.snapshot.lines.length} pageSize={50} pageCount={Math.ceil(detail.snapshot.lines.length/50)} setPage={setLinePage}/><p className="text-sm text-gray-600">{detail.snapshot.changes.filter(c=>c.action==='add').length} additions · {detail.snapshot.changes.filter(c=>c.action==='replace').length} replacements · {detail.snapshot.changes.filter(c=>c.action==='remove').length} removals. Exact JSON includes per-employee/type totals and both sides of every correction.</p></section>}
  {dialog&&<ActionDialog title={titles[dialog.kind]} onClose={()=>setDialog(null)} onSave={save}>
   {dialog.kind==='register'&&<><div className="grid gap-3 sm:grid-cols-2"><Field label="Payroll period starts"><AustralianDateInput name="period_start" required value={payrollStart} onChange={e=>{setPayrollStart(e.target.value);setPayrollPreview(null);}} className={inputClass}/></Field><Field label="Payroll period ends"><AustralianDateInput name="period_end" required value={payrollEnd} onChange={e=>{setPayrollEnd(e.target.value);setPayrollPreview(null);}} className={inputClass}/></Field></div><Button variant="secondary" disabled={!payrollStart||!payrollEnd||busy} onClick={()=>void run(async()=>setPayrollPreview(await apiClient.get(`${root}/register-preview?period_start=${payrollStart}&period_end=${payrollEnd}`)))}>Check Payroll identities</Button>{payrollPreview&&<><p className="text-sm">{payrollPreview.line_count} dated instructions with verified IDs.</p>{Object.entries(payrollPreview.identities).filter(([,p])=>!p.payroll_id).map(([id,p])=><Field key={id} label={`Payroll assignment for ${p.name}`}><select name={`payroll_id_${id}`} required className={inputClass} defaultValue=""><option value="">Choose verified assignment</option>{p.ids.map(x=><option key={x} value={x}>{x}</option>)}</select></Field>)}{payrollPreview.issues.length>0&&<p className="text-sm text-amber-800">Choose each affected verified Payroll assignment. Missing IDs must be verified in Employee management before exchange.</p>}</>}<Source title="Salary Unit approval reference"/><p className="text-sm text-gray-600">Confirm the period and payroll identities before preparing instructions. Missing or ambiguous IDs and overlapping periods must be resolved first.</p></>}
   {dialog.kind==='payroll-receipt'&&dialog.register&&<><Checksum hash={dialog.register.snapshot_hash}/><Source name="reference" title="Actual Salary Unit reconciliation reference"/><label className="block text-sm"><input type="checkbox" required name="corrections_reconciled"/> I reconciled every instruction, per-employee/type total and previous-version correction with Salary Unit.</label></>}
  </ActionDialog>}
 </div>;
}
