import { formatDate } from '../../lib/date';
import {useEffect,useState} from 'react';
import {apiClient} from '../../lib/api';
import {Button,Pager} from '../../components/Ui';
import {csvCell} from '../../lib/csv';
type Activity={summary:Record<'total'|'pending'|'approved'|'rejected'|'cancelled'|'overdue'|'salary_unacknowledged',number>;queue:{level:string;applications:number}[];balances:{code:string;committed:string;held:string;available:string}[];rows:{id:string;employee_name:string;department_name:string|null;code:string;start_date:string;end_date:string;policy_days:string}[];total:number;semantics:string};
const label=(v:string)=>v.replace(/_/g,' ').replace(/^./,s=>s.toUpperCase());
export function GovernmentActivity({from,to,details=false}:{from:string;to:string;details?:boolean}){
 const [data,setData]=useState<Activity|null>(null),[error,setError]=useState(''),[page,setPage]=useState(0),[version,setVersion]=useState(0),[exporting,setExporting]=useState(false);
 useEffect(()=>{setPage(0);},[from,to]);
 useEffect(()=>{let live=true;setError('');setData(null);if(!from||!to||from>to)return;void apiClient.get<Activity>(`/hr/government/report?from=${from}&to=${to}&page=${page+1}`).then(r=>{if(live)setData(r);}).catch((e:Error)=>{if(live){setData(null);setError(e.message);}});return()=>{live=false;};},[from,to,page,version]);
 async function download(){if(!data)return;setExporting(true);try{const rows=[];for(let p=1;p<=Math.ceil(data.total/100);p++){const result=await apiClient.get<Activity>(`/hr/government/report?from=${from}&to=${to}&page=${p}`);rows.push(...result.rows);}const csv=[['Employee','Department','Leave type','Starts','Effective end','Policy days in period'],...rows.map(r=>[r.employee_name,r.department_name||'',label(r.code),formatDate(r.start_date),formatDate(r.end_date),r.policy_days])].map(row=>row.map(csvCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`government-leave-${from}-to-${to}.csv`;a.click();URL.revokeObjectURL(url);}catch(e){setError((e as Error).message);}finally{setExporting(false);}}
 return <section className="app-panel space-y-3 p-4" aria-label="Government leave activity"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">Government leave activity</h3><Button variant="secondary" onClick={()=>setVersion(v=>v+1)}>Refresh</Button></div>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{data&&<><p className="text-sm text-gray-600">{formatDate(from)} to {formatDate(to)} · Your authorised departments and divisions. Approved activity uses this period; pending stages and Salary acknowledgements cover all dates.</p><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{(['pending','approved','overdue','salary_unacknowledged'] as const).map(key=><div key={key}><p className="text-sm text-gray-600">{key==='overdue'?'Pending over five days':key==='salary_unacknowledged'?'Salary acknowledgement due':label(key)}</p><p className="text-xl font-semibold tabular-nums">{data.summary[key]}</p></div>)}</div><p className="text-sm text-gray-600">{data.queue.length?data.queue.map(q=>`${label(q.level)}: ${q.applications}`).join(' · '):'No pending Government approval stages.'}</p>{data.balances.map(b=><p key={b.code} className="text-sm text-gray-600">{label(b.code)} current certified balances: {Number(b.available).toFixed(2)} policy days available · {Number(b.held).toFixed(2)} held · {Number(b.committed).toFixed(2)} committed.</p>)}<p className="text-sm text-gray-600">Open Employees → Government applications & jobs for decisions and follow-ups. These queues are reviewed in the portal; Government email reminders are not automated; assigned officers should review these queues routinely.</p>{details&&<><p className="text-sm text-gray-600">{data.semantics}</p><Button variant="secondary" disabled={!data.total} loading={exporting} onClick={()=>void download()}>Export Government absences</Button><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr>{['Employee','Department','Leave type','Starts','Effective end','Policy days in period'].map(h=><th key={h} className="px-3 py-2">{h}</th>)}</tr></thead><tbody>{data.rows.map(r=><tr key={r.id} className="border-t border-gray-100"><td className="px-3 py-2">{r.employee_name}</td><td className="px-3 py-2">{r.department_name||'—'}</td><td className="px-3 py-2">{label(r.code)}</td><td className="px-3 py-2">{formatDate(r.start_date)}</td><td className="px-3 py-2">{formatDate(r.end_date)}</td><td className="px-3 py-2 tabular-nums">{r.policy_days}</td></tr>)}</tbody></table></div>{!data.rows.length&&<p className="text-sm text-gray-500">No approved Government absences in this period.</p>}<Pager page={page} setPage={setPage} pageCount={Math.ceil(data.total/100)} total={data.total} pageSize={100}/></>}</>}</section>;
}
