import { policyVersionLabel } from './policyVersionLabel';
import { formatDate } from '../../lib/date';
import { AustralianDateInput } from '../../components/AustralianDateInput';
import {useEffect,useState} from 'react';
import {apiClient} from '../../lib/api';
import {useAuth} from '../../contexts/useAuth';
import {Button,LoadingState,Pager} from '../../components/Ui';
import {ActionDialog,DirectoryPicker,Field,inputClass} from './ManagementFields';
import {value} from './managementForm';
const root='/hr/government/payroll';
const today=()=>new Date(Date.now()+12*3600000).toISOString().slice(0,10);
const label=(s:string)=>s.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
type Line={key:string;employee_id:string;employee_name:string;payroll_id:string;code:string;kind:string;date:string;salary_percent:string|null;scheduled_hours:string;policy_days:string;payable_aud:string};
type Register={id:string;version:number;period_start:string;period_end:string;prepared_by:string;snapshot_hash:string;supersedes_id:string|null;receipt_reference:string|null;latest:boolean;line_count:number;change_count:number;snapshot?:{lines:Line[];totals:(Line&{rows:number})[];changes:{key:string;action:string;before:Line|null;after:Line|null}[]}};
type Target={code:string;target:string;current:string;difference:string;held:string};
type Review={id:string;display_name:string;employee_id:string;cutover_date:string;context_hash:string;prepared_by:string;certified_by:string|null;plan:{targets:Target[];external_pending_count:number};transfers:{legacy_request_id:string;request_id:string;code:string;status:string|null}[];transition_reference:string;history_reference:string};
type MigrationState={initial_setup:{id:string;status:string;policy_label:string|null;start_date:string;mappings:{leave_type_id:string;code:string|null}[]}|null;context:{employee:{display_name:string};entitlements:{code:string;balance:string;held:string;period_start:string;period_end:string}[]};identity:{payroll_id:string|null};historical_balances:{leave_type_id:string;leave_type_name:string;year:number;balance:string;pending:string}[];retained_legacy_leave:{id:string;leave_type_id:string;status:string;start_date:string;end_date:string;days:string}[];government_requests:{id:string;code:string;status:string;start_date:string;end_date:string}[];benefit_bases:{id:string}[]};
type Handover={id:string;prepared_by:string;snapshot_hash:string;employee_ids:string[];includes_evidence:boolean;receipt_reference:string|null};
type Person={id:string;display_name:string;department_code:string|null;external_ids:{external_id:string}[]};
async function download(path:string,name:string){const blob=await apiClient.getBlob(path),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Source({name='source_reference',title='Signed source reference'}:{name?:string;title?:string}){return <Field label={title}><input name={name} className={inputClass} required minLength={5} maxLength={500}/></Field>;}
function Checksum({hash}:{hash:string}){return <p className="break-all text-xs text-gray-500">Snapshot SHA-256: {hash}</p>;}
export function GovernmentPayroll({selectedEmployeeId=''}:{selectedEmployeeId?:string}){
 const {user}=useAuth(),[tab,setTab]=useState(selectedEmployeeId?'migrations':'registers'),[version,setVersion]=useState(0),[error,setError]=useState('');
 const [registers,setRegisters]=useState<Register[]>([]),[registerPage,setRegisterPage]=useState(0),[registerTotal,setRegisterTotal]=useState(0),[detail,setDetail]=useState<Register|null>(null),[linePage,setLinePage]=useState(0);
 const [reviews,setReviews]=useState<Review[]>([]),[reviewPage,setReviewPage]=useState(0),[reviewTotal,setReviewTotal]=useState(0);
 const [handovers,setHandovers]=useState<Handover[]>([]),[handoverPage,setHandoverPage]=useState(0),[handoverTotal,setHandoverTotal]=useState(0);
 const [employeeId,setEmployeeId]=useState(selectedEmployeeId),[cutover,setCutover]=useState(today()),[state,setState]=useState<MigrationState|null>(null),[busy,setBusy]=useState(false);
 const [people,setPeople]=useState<Person[]>([]),[peoplePage,setPeoplePage]=useState(0),[peopleTotal,setPeopleTotal]=useState(0),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<string[]>([]);
 const [payrollStart,setPayrollStart]=useState(''),[payrollEnd,setPayrollEnd]=useState(''),[payrollPreview,setPayrollPreview]=useState<{issues:string[];identities:Record<string,{name:string;ids:string[];payroll_id:string|null}>;line_count:number}|null>(null);
 const [dialog,setDialog]=useState<{kind:string;key:string;register?:Register;review?:Review;handover?:Handover;transfer?:{legacy_request_id:string;code:string};transferKeys?:Record<string,string>}|null>(null);
 useEffect(()=>{if(selectedEmployeeId)return;let live=true;void apiClient.get<{registers:Register[];total:number}>(`${root}/registers?page=${registerPage+1}`).then(r=>{if(live){setRegisters(r.registers);setRegisterTotal(r.total);}}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[registerPage,version,selectedEmployeeId]);
 useEffect(()=>{let live=true;void apiClient.get<{reviews:Review[];total:number}>(`${root}/migrations?page=${reviewPage+1}${selectedEmployeeId?`&employee_id=${selectedEmployeeId}`:''}`).then(r=>{if(live){setReviews(r.reviews);setReviewTotal(r.total);}}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[reviewPage,version,selectedEmployeeId]);
 useEffect(()=>{if(selectedEmployeeId)return;let live=true;void apiClient.get<{handovers:Handover[];total:number}>(`${root}/handovers?page=${handoverPage+1}`).then(r=>{if(live){setHandovers(r.handovers);setHandoverTotal(r.total);}}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[handoverPage,version,selectedEmployeeId]);
 useEffect(()=>{if(tab!=='handovers')return;let live=true;void apiClient.get<{employees:Person[];total:number}>(`/hr/directory?page=${peoplePage+1}&search=${encodeURIComponent(search)}`).then(r=>{if(live){setPeople(r.employees);setPeopleTotal(r.total);}}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[peoplePage,search,tab]);
 function show(kind:string,other:Partial<NonNullable<typeof dialog>>={}){if(kind==='register'){setPayrollPreview(null);setPayrollStart('');setPayrollEnd('');}setDialog({kind,key:crypto.randomUUID(),...(kind==='migration'&&state?{transferKeys:Object.fromEntries(state.retained_legacy_leave.map(r=>[r.id,crypto.randomUUID()]))}:{}),...other});}
 async function run(work:()=>Promise<void>){setError('');setBusy(true);try{await work();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(data:FormData){if(!dialog)return;const why=value(data,'reason');
  if(dialog.kind==='register'){const batch=await apiClient.post<Register>(`${root}/registers`,{batch_id:dialog.key,period_start:value(data,'period_start'),period_end:value(data,'period_end'),source_reference:value(data,'source_reference'),reason:why,payroll_ids:Object.fromEntries([...data.entries()].filter(([key])=>key.startsWith('payroll_id_')).map(([key,v])=>[key.slice(11),String(v)]))});setDetail(batch);setLinePage(0);}
  if(dialog.kind==='payroll-receipt'&&dialog.register)await apiClient.post(`${root}/registers/${dialog.register.id}/receipt`,{reference:value(data,'reference'),snapshot_hash:dialog.register.snapshot_hash,reason:why,corrections_reconciled:data.has('corrections_reconciled')});
  if(dialog.kind==='migration'&&state){const dispositions=state.retained_legacy_leave.map(r=>{const linked=value(data,`link_${r.id}`);return {legacy_request_id:r.id,action:linked==='transfer_with_fresh_approval'?linked:linked?'portal_link':'retain_external',...(linked?{portal_request_id:linked==='transfer_with_fresh_approval'?dialog.transferKeys?.[r.id]:linked}:{}),...(linked==='transfer_with_fresh_approval'?{code:value(data,`code_${r.id}`)}:{}),reference:value(data,`reference_${r.id}`)};});await apiClient.post(`${root}/employees/${employeeId}/migrations`,{review_id:dialog.key,cutover_date:cutover,targets:['recreation','medical','special'].map(code=>({code,amount:value(data,code)})),dispositions,source_reference:value(data,'source_reference'),payroll_reference:value(data,'payroll_reference'),transition_reference:value(data,'transition_reference'),history_reference:value(data,'history_reference'),reason:why});}
  if(dialog.kind==='certify'&&dialog.review)await apiClient.post(`${root}/migrations/${dialog.review.id}/certify`,{context_hash:dialog.review.context_hash,reason:why});
  if(dialog.kind==='handover')await apiClient.post(`${root}/handovers`,{handover_id:dialog.key,employee_ids:selected,include_documents:data.has('include_documents'),source_reference:value(data,'source_reference'),reason:why});
  if(dialog.kind==='handover-receipt'&&dialog.handover)await apiClient.post(`${root}/handovers/${dialog.handover.id}/receipt`,{snapshot_hash:dialog.handover.snapshot_hash,reference:value(data,'reference'),reason:why});
  if(dialog.kind==='transfer'&&dialog.transfer){const form=new FormData();form.append('reason',why);form.append('medical_mode',value(data,'medical_mode')||'not_applicable');if(value(data,'related_request_id'))form.append('related_request_id',value(data,'related_request_id'));for(const file of data.getAll('documents'))if(file instanceof File&&file.size)form.append('documents',file);await apiClient.upload(`${root}/transfers/${dialog.transfer.legacy_request_id}/submit`,form);}
  setDialog(null);setVersion(v=>v+1);if(dialog.kind==='payroll-receipt'&&dialog.register)setDetail(await apiClient.get<Register>(`${root}/registers/${dialog.register.id}`));
 }
 const titles:Record<string,string>={register:'Prepare Payroll period register','payroll-receipt':'Record Salary Unit reconciliation',migration:'Prepare opening and retained-leave dry run',certify:'Independently certify migration',handover:'Prepare portable handover part','handover-receipt':'Record receiving-system rehearsal',transfer:'Submit retained leave for fresh approval'};
 return <div className="min-w-0 space-y-4">
  <div><h3 className="text-xl font-semibold">Payroll & handover</h3><p className="mt-1 text-sm text-gray-600">{selectedEmployeeId?'Review this employee’s retained balances and applications against signed cutover targets.':'Reconcile certified leave with Salary Unit and rehearse the later HRIS handover.'}</p></div>
  {!selectedEmployeeId&&<nav aria-label="Payroll and migration" className="flex gap-2 overflow-x-auto sm:flex-wrap">{[['registers','Salary Unit register'],['migrations','Opening & cutover review'],['handovers','Portable handover']].map(([id,title])=><Button key={id} className="shrink-0" variant={tab===id?'primary':'secondary'} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{title}</Button>)}</nav>}
  {error&&<p role="alert" className="break-words rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{busy&&<LoadingState label="Checking reviewed records…"/>}
  {tab==='registers'&&<>
   <section className="app-panel space-y-3 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h4 className="font-semibold">Versioned Payroll registers</h4><Button onClick={()=>show('register')}>Prepare period register</Button></div><p className="text-sm text-gray-600">Each version replaces its exact period. Reconcile corrections against the previous version before recording Salary Unit's receipt. Full, partial and unpaid salary instructions are separate.</p>
   {!registers.length&&<p className="text-sm text-gray-500">No Payroll registers prepared.</p>}{registers.map(r=><article key={r.id} className="space-y-2 rounded-lg border border-gray-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><h5 className="font-semibold">{formatDate(r.period_start)} to {formatDate(r.period_end)} · Version {r.version}</h5><span className="rounded bg-blue-50 px-2 py-1 text-xs text-blue-900">{r.latest?'Current period version':'Superseded'}</span></div><p className="text-sm">{r.line_count} instructions · {r.change_count} changed rows · {r.receipt_reference?`Received: ${r.receipt_reference}`:'Awaiting Salary Unit reconciliation'}</p><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>void run(async()=>{setDetail(await apiClient.get<Register>(`${root}/registers/${r.id}`));setLinePage(0);})}>Review register</Button><Button variant="secondary" onClick={()=>void run(()=>download(`${root}/registers/${r.id}/export?format=csv`,`leave-payroll-${r.id}-v${r.version}.csv`))}>Download CSV</Button><Button variant="secondary" onClick={()=>void run(()=>download(`${root}/registers/${r.id}/export?format=json`,`leave-payroll-${r.id}-v${r.version}.json`))}>Download exact JSON</Button>{r.version>1&&<Button variant="secondary" onClick={()=>void run(()=>download(`${root}/registers/${r.id}/export?format=corrections`,`leave-corrections-${r.id}-v${r.version}.csv`))}>Download corrections</Button>}{r.latest&&!r.receipt_reference&&r.prepared_by!==String(user?.id)&&<Button onClick={()=>show('payroll-receipt',{register:r})}>Record reconciliation</Button>}</div><Checksum hash={r.snapshot_hash}/></article>)}<Pager page={registerPage} total={registerTotal} pageSize={50} pageCount={Math.ceil(registerTotal/50)} setPage={setRegisterPage}/></section>
   {detail?.snapshot&&<section className="app-panel min-w-0 space-y-3 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="font-semibold">Register version {detail.version} · {detail.snapshot.lines.length} dated instructions</h4><Button variant="secondary" onClick={()=>setDetail(null)}>Close register</Button></div><Checksum hash={detail.snapshot_hash}/><div className="max-w-full overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Employee / Payroll ID','Date / type','Instruction','Salary','Hours / days','Payable AUD'].map(h=><th key={h} className="whitespace-nowrap px-3 py-2">{h}</th>)}</tr></thead><tbody>{detail.snapshot.lines.slice(linePage*50,(linePage+1)*50).map(l=><tr key={l.key} className="border-t border-gray-100"><td className="px-3 py-2">{l.employee_name}<br/><span className="text-xs text-gray-500">{l.payroll_id}</span></td><td className="px-3 py-2">{formatDate(l.date)}<br/>{label(l.code)}</td><td className="px-3 py-2">{label(l.kind)}</td><td className="px-3 py-2">{l.salary_percent===null?'—':`${Number(l.salary_percent)}%`}</td><td className="px-3 py-2">{Number(l.scheduled_hours)}h / {Number(l.policy_days)}d</td><td className="px-3 py-2">{l.kind==='absence'||l.kind==='attendance_instruction'?'Salary Unit calculates':l.payable_aud}</td></tr>)}</tbody></table></div><Pager page={linePage} total={detail.snapshot.lines.length} pageSize={50} pageCount={Math.ceil(detail.snapshot.lines.length/50)} setPage={setLinePage}/><p className="text-sm text-gray-600">{detail.snapshot.changes.filter(c=>c.action==='add').length} additions · {detail.snapshot.changes.filter(c=>c.action==='replace').length} replacements · {detail.snapshot.changes.filter(c=>c.action==='remove').length} removals. Exact JSON includes per-employee/type totals and both sides of every correction.</p></section>}
  </>}
  {tab==='migrations'&&<>
   <form className="app-panel space-y-3 p-4" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget),id=value(data,'employee_id');setEmployeeId(id);setState(null);if(id)void run(async()=>setState(await apiClient.get<MigrationState>(`${root}/employees/${id}/migration-state?cutover_date=${cutover}`)));else setError('Choose an employee first.');}}><h4 className="font-semibold">Employee opening and retained-leave reconciliation</h4>{selectedEmployeeId?<input type="hidden" name="employee_id" value={selectedEmployeeId}/>:<DirectoryPicker name="employee_id" label="Migration employee" allowInactive/>}<Field label="Reviewed cutover date"><AustralianDateInput required value={cutover} max={today()} className={inputClass} onChange={e=>{setCutover(e.target.value);setState(null);}}/></Field><Button type="submit" disabled={busy}>Load reconciliation</Button></form>
   {state&&<section className="app-panel space-y-3 p-4"><h4 className="font-semibold">{state.context.employee.display_name} · {state.identity.payroll_id||'Payroll ID needs verification'}</h4>{state.initial_setup&&<p className="rounded-lg bg-blue-50 p-3 text-sm text-blue-900">Initial setup {state.initial_setup.status==='adopted'?'adopted':'draft'}: {state.initial_setup.policy_label?policyVersionLabel(state.initial_setup.policy_label,'published'):'Policy not selected'} · planned start {formatDate(state.initial_setup.start_date)}. Saved type mappings are shown below and suggested for retained application transfers. Opening amounts still require review; the governing policy is resolved by date.</p>}<h5 className="font-medium">Historical balances retained</h5>{!state.historical_balances.length&&<p className="text-sm text-gray-500">No historical balances recorded.</p>}{state.historical_balances.map(b=><p key={`${b.leave_type_id}:${b.year}`} className="break-words text-sm">{b.leave_type_name} · {b.year}: {b.balance} days / {b.pending} pending{state.initial_setup&&<span className="ml-2 text-xs text-gray-600">→ {state.initial_setup.mappings.find(m=>m.leave_type_id===b.leave_type_id)?.code==='retain_history'?'Retain history only':state.initial_setup.mappings.find(m=>m.leave_type_id===b.leave_type_id)?.code?label(state.initial_setup.mappings.find(m=>m.leave_type_id===b.leave_type_id)!.code!):'Mapping needs a decision'}</span>}</p>)}<h5 className="font-medium">Current government accounts</h5>{state.context.entitlements.map(a=><p key={`${a.code}:${a.period_start}`} className="text-sm">{label(a.code)} · {formatDate(a.period_start)} to {formatDate(a.period_end)}: {a.balance} days / {a.held} held</p>)}<p className="text-sm">{state.retained_legacy_leave.length} pending/future legacy applications to reconcile. Prior long-service/furlough baselines: {state.benefit_bases.length} retained.</p><p className="text-sm text-gray-600">Signed targets establish remaining credit at cutover. Historical types, five-day Special balances, medical records, grants and PDFs remain intact. Linked future grants must first pass the government approval chain.</p><Button disabled={!state.identity.payroll_id} onClick={()=>show('migration')}>Prepare certified targets</Button></section>}
   <section className="app-panel space-y-3 p-4"><h4 className="font-semibold">Migration review queue</h4>{!reviews.length&&<p className="text-sm text-gray-500">No migration dry runs prepared.</p>}{reviews.map(r=><article key={r.id} className="space-y-2 rounded-lg border border-gray-200 p-3"><h5 className="font-semibold">{r.display_name} · {formatDate(r.cutover_date)} · {r.certified_by?'Certified':'Awaiting independent review'}</h5>{r.plan.targets.map(t=><p key={t.code} className="text-sm">{label(t.code)}: {t.current} → {t.target} days · correction {t.difference} · holds {t.held}</p>)}<p className="break-words text-sm text-gray-600">Transition: {r.transition_reference}<br/>History: {r.history_reference}</p><p className="text-sm">{r.plan.external_pending_count} retained or transferred applications require reconciliation before employee use.</p>{r.transfers?.map(t=><div key={t.legacy_request_id} className="space-y-1 rounded bg-blue-50 p-2"><p className="break-words text-sm">Transferred {label(t.code)} · {t.status||'Awaiting assisted submission'} · Application {t.request_id}</p>{!t.status&&<Button variant="secondary" onClick={()=>show('transfer',{transfer:t})}>Submit retained application</Button>}{t.status&&<p className="text-xs text-gray-600">Review the application and every statutory stage under Government workflow.</p>}</div>)}<Checksum hash={r.context_hash}/><Button variant="secondary" onClick={()=>void run(()=>download(`${root}/migrations/${r.id}/export`,`leave-migration-${r.id}.json`))}>Download reviewed sources</Button>{!r.certified_by&&r.prepared_by!==String(user?.id)&&<Button onClick={()=>show('certify',{review:r})}>Certify reviewed migration</Button>}{!r.certified_by&&r.prepared_by===String(user?.id)&&<p className="text-sm text-gray-500">A second central HR officer must certify this dry run.</p>}</article>)}<Pager page={reviewPage} total={reviewTotal} pageSize={50} pageCount={Math.ceil(reviewTotal/50)} setPage={setReviewPage}/></section>
  </>}
  {tab==='handovers'&&<>
   <section className="app-panel space-y-3 p-4"><h4 className="font-semibold">Prepare a portable employee cohort</h4><p className="text-sm text-gray-600">Select up to 50 employees per part. For 2,000 employees, prepare and reconcile 40 parts. Each part retains IDs, service, certified accounts, movements, holds, pending/future workflows, decisions, PDFs and exchange history.</p><form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();setSearch(query.trim());setPeoplePage(0);}}><input aria-label="Search handover employees" className={`${inputClass} flex-1 basis-48`} value={query} maxLength={100} onChange={e=>setQuery(e.target.value)} placeholder="Name or exact Payroll ID"/><Button type="submit" variant="secondary">Search</Button></form><div className="flex flex-wrap items-center gap-3"><Button variant="secondary" onClick={()=>setSelected(people.map(p=>p.id))}>Select this page</Button><Button variant="secondary" onClick={()=>setSelected([])}>Clear selection</Button><p className="text-sm">{selected.length} selected / 50 maximum</p></div><div className="max-h-80 space-y-1 overflow-y-auto rounded-lg border border-gray-200 p-2">{people.map(p=><label key={p.id} className="flex items-start gap-2 rounded p-2 text-sm hover:bg-blue-50"><input type="checkbox" className="mt-1" checked={selected.includes(p.id)} disabled={!selected.includes(p.id)&&selected.length>=50} onChange={e=>setSelected(s=>e.target.checked?[...s,p.id]:s.filter(id=>id!==p.id))}/><span className="min-w-0 break-words">{p.display_name} · {p.department_code||'Unverified department'} · {p.external_ids.map(x=>x.external_id).join(', ')||'No Payroll ID'}</span></label>)}</div><Pager page={peoplePage} total={peopleTotal} pageSize={50} pageCount={Math.ceil(peopleTotal/50)} setPage={setPeoplePage}/><Button disabled={!selected.length} onClick={()=>show('handover')}>Prepare handover part</Button></section>
   <section className="app-panel space-y-3 p-4"><h4 className="font-semibold">Frozen handover parts</h4>{!handovers.length&&<p className="text-sm text-gray-500">No handover parts prepared.</p>}{handovers.map(h=><article key={h.id} className="space-y-2 rounded-lg border border-gray-200 p-3"><p className="font-semibold">{h.employee_ids.length} employees · {h.includes_evidence?'Evidence archive included':'Evidence manifest only'}</p><p className="break-words text-sm">{h.receipt_reference?`Rehearsal reconciled: ${h.receipt_reference}`:'Awaiting receiving-system rehearsal'}</p><Checksum hash={h.snapshot_hash}/><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>void run(()=>download(`${root}/handovers/${h.id}/export`,`leave-handover-${h.id}.json`))}>Download handover JSON</Button>{!h.receipt_reference&&h.prepared_by!==String(user?.id)&&<Button onClick={()=>show('handover-receipt',{handover:h})}>Record rehearsal receipt</Button>}</div></article>)}<Pager page={handoverPage} total={handoverTotal} pageSize={50} pageCount={Math.ceil(handoverTotal/50)} setPage={setHandoverPage}/></section>
  </>}
  {dialog&&<ActionDialog title={titles[dialog.kind]} onClose={()=>setDialog(null)} onSave={save}>
   {dialog.kind==='register'&&<><div className="grid gap-3 sm:grid-cols-2"><Field label="Payroll period starts"><AustralianDateInput name="period_start" required value={payrollStart} onChange={e=>{setPayrollStart(e.target.value);setPayrollPreview(null);}} className={inputClass}/></Field><Field label="Payroll period ends"><AustralianDateInput name="period_end" required value={payrollEnd} onChange={e=>{setPayrollEnd(e.target.value);setPayrollPreview(null);}} className={inputClass}/></Field></div><Button variant="secondary" disabled={!payrollStart||!payrollEnd||busy} onClick={()=>void run(async()=>setPayrollPreview(await apiClient.get(`${root}/register-preview?period_start=${payrollStart}&period_end=${payrollEnd}`)))}>Check Payroll identities</Button>{payrollPreview&&<><p className="text-sm">{payrollPreview.line_count} dated instructions with verified IDs.</p>{Object.entries(payrollPreview.identities).filter(([,p])=>!p.payroll_id).map(([id,p])=><Field key={id} label={`Payroll assignment for ${p.name}`}><select name={`payroll_id_${id}`} required className={inputClass} defaultValue=""><option value="">Choose verified assignment</option>{p.ids.map(x=><option key={x} value={x}>{x}</option>)}</select></Field>)}{payrollPreview.issues.length>0&&<p className="text-sm text-amber-800">Choose each affected verified Payroll assignment. Missing IDs must be verified in Employee management before exchange.</p>}</>}<Source title="Salary Unit approved exchange reference"/><p className="text-sm text-gray-600">The generic contract needs Salary Unit acceptance before operational use. Missing or ambiguous Payroll IDs block preparation; overlapping different periods are rejected.</p></>}
   {dialog.kind==='payroll-receipt'&&dialog.register&&<><Checksum hash={dialog.register.snapshot_hash}/><Source name="reference" title="Actual Salary Unit reconciliation reference"/><label className="block text-sm"><input type="checkbox" required name="corrections_reconciled"/> I reconciled every instruction, per-employee/type total and previous-version correction with Salary Unit.</label></>}
   {dialog.kind==='migration'&&state&&<><p className="text-sm">Propose remaining credits at {formatDate(cutover)}. A second officer checks this dry run before corrections or openings post.</p><div className="grid gap-3 sm:grid-cols-3">{['recreation','medical','special'].map(code=><Field key={code} label={`${label(code)} target days`}><input name={code} type="number" min="0" step="0.000001" required defaultValue={state.context.entitlements.find(a=>a.code===code&&a.period_start<=cutover&&a.period_end>=cutover)?.balance||'0'} className={inputClass}/></Field>)}</div><Source title="Certified opening register reference"/><Source name="payroll_reference" title="Salary Unit balance reconciliation reference"/><Source name="transition_reference" title="Signed legacy type / single Medical pool / Special transition"/><Source name="history_reference" title="Verified service, Medical absence and prior payout history"/>{state.retained_legacy_leave.map(r=><fieldset key={r.id} className="min-w-0 space-y-2 rounded-lg border p-3"><legend className="text-sm font-semibold">{r.status} · {formatDate(r.start_date)} to {formatDate(r.end_date)} · {r.days} days</legend><Field label={`Disposition for ${formatDate(r.start_date)}`}><select name={`link_${r.id}`} className={inputClass}><option value="">Retain external record; resolve before activation</option><option value="transfer_with_fresh_approval">Prepare transfer with fresh government approvals</option>{state.government_requests.filter(g=>g.start_date===r.start_date&&g.end_date===r.end_date&&g.status===r.status).map(g=><option key={g.id} value={g.id}>{label(g.code)} · {g.status} · {g.id.slice(0,8)}</option>)}</select></Field><Field label={`Transfer type for ${formatDate(r.start_date)}`}><select name={`code_${r.id}`} defaultValue={state.initial_setup?.mappings.find(m=>m.leave_type_id===r.leave_type_id)?.code==='retain_history'?'':state.initial_setup?.mappings.find(m=>m.leave_type_id===r.leave_type_id)?.code||''} className={inputClass}><option value="">Choose Government transfer type</option>{['recreation','medical','special','teacher_recreation','extended_medical','extended_medical_minister','maternity','paternity','adoption','official','lwop','long_service','furlough','recreation_encashment','recreation_separation','witness_republic','witness_other'].map(c=><option key={c} value={c}>{label(c)}</option>)}</select></Field><Source name={`reference_${r.id}`} title={`Reconciliation authority for ${formatDate(r.start_date)}`}/></fieldset>)}</>}
   {dialog.kind==='transfer'&&dialog.transfer&&<><p className="text-sm">Copy the certified source dates and type into a new government application. The original legacy record is retained. Every government approval is required; no old approval is treated as a new Chief Secretary grant.</p>{dialog.transfer.code==='medical'&&<Field label="Verified transferred Medical evidence"><select name="medical_mode" className={inputClass} required defaultValue="certificate"><option value="certificate">Practitioner certificate</option><option value="exemption">Reviewed single-date exemption</option></select></Field>}{dialog.transfer.code==='extended_medical_minister'&&<Field label="Related approved government Medical extension ID"><input name="related_request_id" required maxLength={36} className={inputClass}/></Field>}<Field label="Supporting evidence for transferred application"><input name="documents" type="file" multiple accept="application/pdf,image/png,image/jpeg" className={inputClass}/></Field><p className="text-sm text-gray-600">Confirm signed remaining credits account for the replaced legacy future deduction before submitting. A common leave type needs its independently published configuration. Event determinations and evidence checks continue under Government workflow.</p></>}
   {dialog.kind==='certify' &&dialog.review&&<><Checksum hash={dialog.review.context_hash}/>{dialog.review.plan.targets.map(t=><p key={t.code} className="text-sm">{label(t.code)}: {t.current} → {t.target}; delta {t.difference}</p>)}<label className="block text-sm"><input type="checkbox" required/> I independently checked opening sources, transition, service/history, prior payouts and every pending/future disposition.</label><p className="text-sm text-gray-600">Changed records invalidate this review. Certification posts the reviewed openings/corrections; workflow activation and job scheduling remain separate.</p></>}
   {dialog.kind==='handover'&&<><p className="text-sm">Freeze {selected.length} selected employee records for a receiving-system rehearsal.</p><Source title="HRIS handover authority reference"/><label className="block text-sm"><input name="include_documents" type="checkbox" defaultChecked/> Include attachments with checksums. Granted PDFs are always included.</label><p className="text-sm text-gray-600">Use the approved personnel-file transfer channel. Evidence-heavy cohorts may need smaller parts. Agree the final freeze boundary before switching the sole accrual engine.</p></>}
   {dialog.kind==='handover-receipt'&&dialog.handover&&<><Checksum hash={dialog.handover.snapshot_hash}/><Source name="reference" title="Receiving-system rehearsal reconciliation reference"/><label className="block text-sm"><input type="checkbox" required/> I reconciled identities, balances/movements, pending/future leave, jobs and document checksums in this exact part.</label><p className="text-sm text-gray-600">This receipt records a rehearsal; operational cutover remains separate.</p></>}
  </ActionDialog>}
 </div>;
}
