import { formatDate } from '../../lib/date';
import { formatDateTime } from '../../lib/date';
import { AustralianDateInput } from '../../components/AustralianDateInput';
import {GovernmentCaseApplication,GovernmentCaseReview} from './GovernmentCases';
import {useEffect,useState} from 'react';
import {apiClient} from '../../lib/api';
import {Button,Pager,LoadingState} from '../../components/Ui';
import {useAuth} from '../../contexts/useAuth';
import {ActionDialog,DirectoryPicker,Field,inputClass} from './ManagementFields';
import {value} from './managementForm';
import {BalanceCards} from './GovernmentFoundation';
import type {GovernmentEntitlement} from './GovernmentFoundation';
import {governmentLabel as label} from './governmentWorkflowTypes';
import type {GovernmentRequest,GovernmentRequestSummary,GovernmentStage} from './governmentWorkflowTypes';
const root='/hr/government/workflow';
async function download(path:string,name:string){const blob=await apiClient.getBlob(path),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function GovernmentRequestList({mode,refreshVersion=0,onChanged,selectedRequestId,employeeId}:{employeeId?:string;selectedRequestId?:string;mode:'mine'|'queue'|'all';refreshVersion?:number;onChanged?:()=>void}) {
 const {user}=useAuth(),central=user?.permissions?.hr_admin===true;
 const [page,setPage]=useState(0),[status,setStatus]=useState(mode==='mine'?'all':'pending'),[data,setData]=useState<{requests:GovernmentRequestSummary[];total:number}>({requests:[],total:0}),[detail,setDetail]=useState<GovernmentRequest|null>(null),[version,setVersion]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [dialog,setDialog]=useState<{kind:'approve'|'reject'|'cancel'|'rebind'|'ack'|'continue'|'evidence';stage?:GovernmentStage;eventKey:string}|null>(null);
 useEffect(()=>{let live=true;void apiClient.get<typeof data>(`${root}/requests?mode=${mode}&status=${status}&page=${page+1}${employeeId?`&employee_id=${employeeId}`:''}`).then(r=>{if(live){setData(r);setError('');setLoading(false);}}).catch((e:Error)=>{if(live){setError(e.message);setLoading(false);}});return()=>{live=false;};},[mode,status,page,version,refreshVersion,employeeId]);
 useEffect(()=>{if(!selectedRequestId)return;let live=true;void apiClient.get<GovernmentRequest>(`${root}/requests/${selectedRequestId}`).then(r=>{if(live)setDetail(r);}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[selectedRequestId]);
 async function open(id:string){setError('');try{setDetail(await apiClient.get<GovernmentRequest>(`${root}/requests/${id}`));}catch(e){setError((e as Error).message);}}
 function show(kind:'approve'|'reject'|'cancel'|'rebind'|'ack'|'continue'|'evidence',stage?:GovernmentStage){setDialog({kind,stage,eventKey:crypto.randomUUID()});}
 async function save(form:FormData){if(!dialog||!detail)return;const reason=value(form,'reason');
  if(dialog.kind==='approve'||dialog.kind==='reject')await apiClient.post(`${root}/requests/${detail.id}/decisions`,{stage_id:dialog.stage?.id,binding_id:dialog.stage?.binding?.id,event_key:dialog.eventKey,decision:dialog.kind==='approve'?'approved':'rejected',note:reason,discretion_confirmed:form.has('discretion_confirmed'),...(dialog.stage?.level==='hr_verifier'&&dialog.kind==='approve'?{evidence_reviewed:form.has('evidence_reviewed'),certificate_reviewed:form.has('certificate_reviewed'),justification_accepted:form.has('justification_accepted'),source_reference:value(form,'source_reference'),...(detail.code==='medical'&&detail.medical_mode==='certificate'?{covers_start:value(form,'covers_start'),covers_end:value(form,'covers_end')}:{})}:{}),...(dialog.kind==='reject'&&dialog.stage?.level==='relevant_secretary'&&detail.code==='recreation'?{operational_refusal:form.has('operational_refusal'),alternative_date:value(form,'alternative_date'),consultation_reference:value(form,'consultation_reference')}:{})});
  else if(dialog.kind==='evidence')await apiClient.post(`${root}/requests/${detail.id}/evidence-review`,{reason,evidence_reviewed:form.has('evidence_reviewed'),certificate_reviewed:form.has('certificate_reviewed'),justification_accepted:form.has('justification_accepted'),source_reference:value(form,'source_reference'),...(detail.code==='medical'&&detail.medical_mode==='certificate'?{covers_start:value(form,'covers_start'),covers_end:value(form,'covers_end')}:{})});
  else if(dialog.kind==='cancel')await apiClient.post(`${root}/requests/${detail.id}/cancel`,{reason});
  else if(dialog.kind==='rebind')await apiClient.post(`${root}/requests/${detail.id}/stages/${dialog.stage?.id}/rebind`,{reason,source_reference:value(form,'source_reference'),...(value(form,'substitute_employee_id')?{substitute_employee_id:value(form,'substitute_employee_id')}:{})});
  else if(dialog.kind==='continue')await apiClient.post(`${root}/requests/${detail.id}/continue`,{reason,source_reference:value(form,'source_reference'),request_id:dialog.eventKey});
  else await apiClient.post(`${root}/requests/${detail.id}/salary-acknowledgement`,{reason,reference:value(form,'reference')});
  setDialog(null);setVersion(v=>v+1);onChanged?.();await open(detail.id);
 }
 const current=detail?.stages.find(s=>s.ordinal===detail.stage_index),action=current?.ordinal===(detail?.stages.length||0)-1?'Grant leave':current?.level==='hr_verifier'?'Verify evidence':current?.level==='relevant_secretary'?'Record consent':current?.level==='minister'?'Record Minister grant':'Recommend leave';
 return <section className="app-panel space-y-4 p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-lg font-semibold">{mode==='mine'?'My government applications':'Government approval workflow'}</h3><div className="flex flex-wrap items-center gap-2"><Field label="Government application status"><select className={inputClass} value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}>{['pending','approved','rejected','cancelled','all'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></Field><Button variant="secondary" onClick={()=>{setVersion(v=>v+1);if(detail)void open(detail.id);}}>Refresh applications</Button></div></div>
  {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  {loading?<LoadingState label="Loading government applications…"/>:!data.requests.length?<p className="text-sm text-gray-500">No government applications in this view.</p>:data.requests.map(r=><article key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-gray-200 p-3"><div className="min-w-0"><h4 className="font-semibold">{r.employee_name} · {label(r.code)}</h4><p className="text-sm">{formatDate(r.start_date)} to {formatDate(r.end_date)} · {Number(r.charge)>0?`${r.charge} policy days`:'Event / reviewed case'} · {label(r.status)}</p>{r.status==='pending'&&<p className="text-sm text-gray-600">Next: {r.current_label||label(r.current_level||'unassigned')} · {r.current_approver||'HR must assign the officeholder'}{r.unassigned_stages?` · ${r.unassigned_stages} unassigned stages`:''}</p>}{r.status==='approved'&&<p className="text-sm text-gray-600">Final grant recorded · Salary Unit {r.salary_acknowledged?'acknowledged':'acknowledgement pending'}</p>}</div><Button variant="secondary" onClick={()=>void open(r.id)}>Review application</Button></article>)}
  <Pager page={page} pageCount={Math.ceil(data.total/50)} total={data.total} pageSize={50} setPage={setPage}/>
  {detail&&<article className="space-y-4 rounded-lg border border-blue-200 bg-blue-50/40 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h4 className="text-lg font-semibold">{detail.employee_name} · {label(detail.code)}</h4><p className="text-sm">{formatDate(detail.start_date)} to {formatDate(detail.end_date)} · {detail.case?'Event / reviewed case':`${detail.charge} policy days`} · {label(detail.status)}</p></div><Button variant="secondary" onClick={()=>setDetail(null)}>Close application</Button></div>
    {detail.code==='medical'&&<p className="text-sm font-medium">{detail.medical_mode==='certificate'?'With medical certificate (M/C)':detail.medical_mode==='exemption'?'Without medical certificate · uncertified occasion':'Medical evidence route not recorded'}</p>}
    {detail.reason&&<p className="whitespace-pre-wrap break-words rounded-lg bg-white p-3 text-sm">{detail.reason}</p>}{!detail.private_access&&<p className="text-sm text-gray-600">Personnel reasons and supporting documents require separate evidence access. HR records the evidence verification stage.</p>}
    {detail.documents.map(doc=><Button key={doc.id} variant="secondary" onClick={()=>{void download(`${root}/requests/${detail.id}/documents/${doc.id}`,doc.file_name).catch((e:Error)=>setError(e.message));}}>Download {doc.file_name}</Button>)}
    <ol className="space-y-2">{detail.stages.map(stage=><li key={stage.id} className="space-y-1 rounded-lg border border-gray-200 bg-white p-3"><p className="font-semibold">{stage.ordinal+1}. {stage.label||label(stage.level)} · {stage.binding?.approver_name||'Unassigned'}</p><p className="text-sm">{stage.decision?`${stage.decision.decision==='approved'?stage.ordinal===detail.stages.length-1||stage.level==='minister'?'Granted':stage.level==='hr_verifier'?'Verified':stage.level==='relevant_secretary'?'Consented':'Recommended':'Rejected'} · ${formatDateTime(stage.decision.decided_at)}`:stage.ordinal===detail.stage_index&&detail.status==='pending'?'Current stage':'Awaiting earlier stages'}</p>{stage.decision?.note&&<p className="break-words text-sm text-gray-600">{stage.decision.note}</p>}{stage.issue&&!stage.decision&&detail.status==='pending'&&<p className="text-sm text-amber-800">{stage.issue}</p>}{central&&!stage.decision&&detail.status==='pending'&&<Button variant="secondary" onClick={()=>show('rebind',stage)}>Review stage assignment</Button>}</li>)}</ol>
    {current?.can_decide&&<div className="flex flex-wrap gap-2"><Button onClick={()=>show('approve',current)}>{action}</Button><Button variant="danger" onClick={()=>show('reject',current)}>Reject application</Button></div>}
    <div className="flex flex-wrap gap-2">{detail.can_cancel&&<Button variant="secondary" onClick={()=>show('cancel')}>Cancel pending application</Button>}{detail.can_pdf&&<Button onClick={()=>{void download(`${root}/requests/${detail.id}/pdf`,`government-leave-${detail.id}.pdf`).catch((e:Error)=>setError(e.message));}}>Download granted PDF</Button>}{detail.can_ack&&<Button variant="secondary" onClick={()=>show('ack')}>Record Salary Unit acknowledgement</Button>}</div>
    {central&&detail.can_continue&&<Button variant="secondary" onClick={()=>show('continue')}>Continue with fresh route approvals</Button>}
    {detail.evidence_review_required&&<div className="space-y-2 rounded-lg border border-gray-200 bg-white p-3"><p className="text-sm">Supporting evidence: {detail.evidence_review?`verified by HR on ${formatDateTime(detail.evidence_review.recorded_at)}`:'HR verification required before the final grant'}</p>{detail.can_verify_evidence&&<Button variant="secondary" onClick={()=>show('evidence')}>Verify supporting evidence</Button>}</div>}
    <GovernmentCaseReview request={detail} central={central} onChanged={async()=>{setVersion(v=>v+1);onChanged?.();await open(detail.id);}}/>
    {detail.salary_acknowledgement&&<p className="text-sm">Salary Unit reference: {detail.salary_acknowledgement.reference}</p>}
   </article>}
   {dialog&&detail&&<ActionDialog title={dialog.kind==='evidence'?'Verify supporting evidence':dialog.kind==='approve'?action:dialog.kind==='reject'?'Reject government application':dialog.kind==='cancel'?'Cancel pending government application':dialog.kind==='rebind'?'Review pending stage assignment':dialog.kind==='continue'?'Continue pending application with fresh approvals':'Record Salary Unit acknowledgement'} onClose={()=>setDialog(null)} onSave={save} saveLabel={dialog.kind==='approve'?action:'Record verified action'}>
     {dialog.kind==='approve'&&dialog.stage?.level==='minister'&&<p className="text-sm">Record the statutory Minister grant for the further medical period and explicit salary segments. Chief Secretary final processing follows this retained Minister decision.</p>}
     {dialog.kind==='approve'&&dialog.stage?.level==='chief_secretary'&&detail.determination&&detail.determination.discretion.length>0&&<label className="block text-sm"><input name="discretion_confirmed" type="checkbox" required/> I confirm the recorded late-notice or extended-LWOP discretionary authority for this grant.</label>}
     {dialog.kind==='approve'&&dialog.stage?.ordinal===detail.stages.length-1&&<p className="text-sm">Record the final grant by {dialog.stage.label||label(dialog.stage.level)}. The server rechecks all required decisions, current authority, evidence, calculation and held entitlement before posting usage once.</p>}
     {dialog.kind==='approve'&&dialog.stage?.level==='hr_verifier'&&detail.case&&<p className="text-sm">Verify the sourced case facts, dated salary segments, evidence and financial history independently. The preparer cannot verify their own determination.</p>}
     {(dialog.kind==='evidence'||dialog.kind==='approve'&&dialog.stage?.level==='hr_verifier')&&<><label className="block text-sm"><input type="checkbox" name="evidence_reviewed" required/> I reviewed the personnel sources, evidence and medical-counter history.</label><Field label="HR verification source"><input name="source_reference" required minLength={5} maxLength={500} className={inputClass}/></Field>{detail.code==='medical'&&detail.medical_mode==='certificate'&&<><label className="block text-sm"><input name="certificate_reviewed" type="checkbox" required/> I verified the registered-practitioner certificate and absence coverage.</label><Field label="Certificate covers from"><AustralianDateInput name="covers_start" required defaultValue={detail.start_date} className={inputClass}/></Field><Field label="Certificate covers through"><AustralianDateInput name="covers_end" required defaultValue={detail.end_date} className={inputClass}/></Field></>}{detail.code==='medical'&&detail.medical_mode==='exemption'&&<p className="text-sm">The server rechecks the approved single-date rule, scheduled-day adjacency and three-occasion limit, including pending applications.</p>}{detail.code==='special'&&<label className="block text-sm"><input name="justification_accepted" type="checkbox" required/> I reviewed sufficient-cause justification for Special leave.</label>}</>}
     {dialog.kind==='reject'&&dialog.stage?.level==='relevant_secretary'&&detail.code==='recreation'&&<><label className="block text-sm"><input type="checkbox" name="operational_refusal" required/> Consent is refused for operational reasons recorded below.</label><Field label="Alternative leave date"><AustralianDateInput name="alternative_date" required className={inputClass}/></Field><Field label="Employee consultation reference"><input name="consultation_reference" required minLength={5} maxLength={500} className={inputClass}/></Field></>}
     {dialog.kind==='cancel'&&<p className="text-sm">Release the pending balance hold and any pending medical exemption. Decisions and documents remain in history. Granted leave requires an assisted amendment.</p>}
     {dialog.kind==='rebind'&&<><p className="text-sm">Retain the submitted department/division and prior assignment history. Use the current dated officeholder, or a signed case-specific substitute for the selected stage. Chief Secretary must remain a verified current/acting Chief Secretary.</p>{dialog.stage?.level!=='chief_secretary'&&<DirectoryPicker name="substitute_employee_id" label="Authorised substitute" requireLinked allowClear/>}<Field label="Assignment authority reference"><input name="source_reference" required minLength={5} maxLength={500} className={inputClass}/></Field></>}
     {dialog.kind==='continue'&&<><p className="text-sm">Cancel the pending application and release its hold in the same transaction as a linked replacement. Retain earlier documents and decisions; recalculate for current placement and offices, then obtain every approval again. This needs an actual employee/HR continuation authority.</p><Field label="Continuation authority reference"><input name="source_reference" required minLength={5} maxLength={500} className={inputClass}/></Field></>}
     {dialog.kind==='ack'&&<><p className="text-sm">Record the Salary Unit's received acknowledgement after final grant. This does not issue payment or change leave usage.</p><Field label="Salary Unit reference"><input name="reference" required minLength={5} maxLength={500} className={inputClass}/></Field></>}
   </ActionDialog>}
 </section>;
}

type Preview={eligible_for_preview:boolean;issues:string[];charge:string;scheduled_hours:number;medical_exemptions_used?:number;requirements:string[]};
export function GovernmentMyLeave({employeeId}:{employeeId:string}) {
 const [configuration,setConfiguration]=useState<{enabled_codes:string[];medical_rule:string|null}|null>(null),[entitlements,setEntitlements]=useState<GovernmentEntitlement[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[version,setVersion]=useState(0),[code,setCode]=useState('recreation'),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[requestId,setRequestId]=useState(()=>crypto.randomUUID()),[fileVersion,setFileVersion]=useState(0);
 useEffect(()=>{let live=true;void Promise.all([apiClient.get<NonNullable<typeof configuration>>(`${root}/me`),apiClient.get<{entitlements:GovernmentEntitlement[]}>(`/hr/government/employees/${employeeId}`)]).then(([config,facts])=>{if(live){setConfiguration(config);setEntitlements(facts.entitlements);if(config.enabled_codes.length&&!config.enabled_codes.includes(code))setCode(config.enabled_codes[0]);}}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[employeeId,version,code]);
 function changed(){setVersion(v=>v+1);}
 function formInput(form:FormData){return {code:value(form,'code'),start_date:value(form,'start_date'),end_date:value(form,'end_date'),reason:value(form,'reason'),medical_mode:value(form,'medical_mode')||'not_applicable'};}
 async function evaluate(form:HTMLFormElement){setBusy(true);setError('');try{setPreview(await apiClient.post<Preview>(`${root}/preview`,formInput(new FormData(form))));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function submit(form:HTMLFormElement){if(!preview?.eligible_for_preview)return;const data=new FormData(form);data.set('request_id',requestId);const files=data.getAll('documents').filter((f):f is File=>f instanceof File&&f.size>0);if(files.length>3||files.some(f=>f.size>5*1024*1024)){setError('Attach at most three documents, each no larger than 5 MB.');return;}setBusy(true);setError('');setMessage('');try{const result=await apiClient.upload<{id:string}>(`${root}/requests`,data);setMessage(`Application submitted. Balance reserved; follow the approval timeline below. Reference ${result.id}`);setPreview(null);setRequestId(crypto.randomUUID());setFileVersion(v=>v+1);form.reset();changed();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="space-y-5"><div><h2 className="text-2xl font-semibold">My government leave</h2><p className="mt-1 text-sm text-gray-600">Apply using certified policy entitlements and follow the nominated approval levels through the final grant.</p></div>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message&&<p role="status" className="rounded-lg bg-green-50 p-3 text-sm text-green-800">{message}</p>}<section className="app-panel p-5"><BalanceCards entitlements={entitlements}/></section>
  {!configuration?<LoadingState label="Loading government leave readiness…"/>:!configuration.enabled_codes.length?<p className="app-panel p-4 text-sm text-blue-900">Common leave submission is awaiting HR's independent activation review. Certified balances remain available for review.</p>:<form className="app-panel space-y-4 p-4 sm:p-5" onChange={()=>{setPreview(null);setRequestId(crypto.randomUUID());}} onSubmit={e=>{e.preventDefault();void submit(e.currentTarget);}}><h3 className="text-lg font-semibold">Apply for government leave</h3><fieldset disabled={busy} className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Field label="Government leave type"><select name="code" value={code} onChange={e=>setCode(e.target.value)} className={inputClass}>{configuration.enabled_codes.map(c=><option key={c} value={c}>{label(c)}</option>)}</select></Field><Field label="Leave starts"><AustralianDateInput name="start_date" required className={inputClass}/></Field><Field label="Leave ends"><AustralianDateInput name="end_date" required className={inputClass}/></Field></div><Field label="Explanation for government leave"><textarea name="reason" required minLength={10} maxLength={4000} rows={3} className={inputClass}/></Field>
    {code==='medical'&&<><Field label="Medical evidence route"><select name="medical_mode" className={inputClass} defaultValue="certificate"><option value="certificate">Medical certificate for HR review</option><option value="exemption">Approved single-day uncertified exemption</option></select></Field><p className="text-sm text-gray-600">One ten-day pool. The three single-date exemptions include pending applications. Adjacent scheduled absences require combined certificate review or an assisted case.</p></>}
    <Field label="Supporting documents"><input key={fileVersion} name="documents" type="file" multiple accept="application/pdf,image/png,image/jpeg" className={inputClass}/></Field><p className="text-sm text-gray-600">Up to three PDF/PNG/JPEG files, 5 MB each. HR verifies required evidence. Recreation needs at least 14 calendar days' notice; missing future entitlement cannot be spent.</p>
    <Button variant="secondary" loading={busy} onClick={e=>{const form=e.currentTarget.closest('form');if(form?.reportValidity())void evaluate(form);}}>Preview government application</Button>
    {preview&&<article className="space-y-2 rounded-lg border border-blue-200 bg-blue-50 p-3"><h4 className="font-semibold">{preview.eligible_for_preview?'Ready for submission':'Review required'} · {preview.charge} policy days</h4><p className="text-sm">{preview.scheduled_hours} scheduled hours{preview.medical_exemptions_used!==undefined?` · ${preview.medical_exemptions_used} medical exemptions already committed`:''}</p>{preview.issues.length>0&&<ul className="list-disc pl-5 text-sm text-amber-800">{preview.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>}<p className="text-sm">The server will calculate again and reserve entitlement at submission. The application is granted only after every required stage.</p></article>}
    <Button type="submit" loading={busy} disabled={!preview?.eligible_for_preview}>Submit government application</Button>
   </fieldset></form>}
   <GovernmentCaseApplication employeeId={employeeId} onChanged={changed}/>
   <GovernmentRequestList mode="mine" refreshVersion={version} onChanged={changed}/>
 </div>;
}
