import { formatDate, parseAustralianDate } from '../../lib/date';
import { AustralianDateInput } from '../../components/AustralianDateInput';
import {DraftLifecycle} from './DraftLifecycle';
import {GovernmentCaseApplication,GovernmentCaseTasks} from './GovernmentCases';
import {useEffect,useState} from 'react';
import {apiClient} from '../../lib/api';
import {useAuth} from '../../contexts/useAuth';
import {Button,LoadingState} from '../../components/Ui';
import {ActionDialog,DirectoryPicker,Field,inputClass} from './ManagementFields';
import {value} from './managementForm';
import {BalanceCards} from './GovernmentFoundation';
import type {GovernmentEntitlement} from './GovernmentFoundation';
import {GovernmentRequestList} from './GovernmentRequests';
import {governmentLabel as label} from './governmentWorkflowTypes';
import type {WorkflowConfiguration,GovernmentJobPlan} from './governmentWorkflowTypes';
const root='/hr/government/workflow',today=()=>new Date(Date.now()+12*3600000).toISOString().slice(0,10);
type AdminData={configs:WorkflowConfiguration[];plans:GovernmentJobPlan[];alerts:{id:string;display_name:string;event_date:string;amount:string}[]};
type Dialog={kind:'config'|'publish'|'plan'|'approve-plan';target?:WorkflowConfiguration|GovernmentJobPlan};
function SourceField({label:caption='Approved source reference',name='source_reference'}:{label?:string;name?:string}){return <Field label={caption}><input name={name} required minLength={5} maxLength={500} className={inputClass}/></Field>;}
export function GovernmentWorkflowManagement({selectedEmployeeId='',view='all'}:{selectedEmployeeId?:string;view?:'all'|'activation'|'applications'}) {
 const {user}=useAuth();const [data,setData]=useState<AdminData|null>(null),[employeeId,setEmployeeId]=useState(selectedEmployeeId),[facts,setFacts]=useState<{employee:{display_name:string;leave_policy_regime:string};periods:{start_date:string;end_date:string|null;is_teacher:boolean}[];entitlements:GovernmentEntitlement[]}|null>(null),[version,setVersion]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dialog,setDialog]=useState<Dialog|null>(null),[code,setCode]=useState('recreation'),[busy,setBusy]=useState(false),[selectedRequestId,setSelectedRequestId]=useState('');
 useEffect(()=>{let live=true;void apiClient.get<AdminData>(`${root}/administration${employeeId?`?employee_id=${employeeId}`:''}`).then(r=>{if(live)setData(r);}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[version,employeeId]);
 useEffect(()=>{if(!employeeId)return;let live=true;void apiClient.get<NonNullable<typeof facts>>(`/hr/government/employees/${employeeId}`).then(r=>{if(live)setFacts(r);}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[version,employeeId]);
 function show(kind:Dialog['kind'],target?:Dialog['target']){setError('');if(kind==='plan'&&!target&&teacher)setCode('medical');if(target){if(target.employee_id!==employeeId)setSelectedRequestId('');setEmployeeId(target.employee_id);if('code' in target)setCode(target.code);else if(kind==='plan'&&teacher)setCode('medical');}setDialog({kind,target});}
 async function save(form:FormData){if(!dialog)return;const reason=value(form,'reason'),source_reference=value(form,'source_reference');
  if(dialog.kind==='config') {
    const history=value(form,'medical_history').split('\n').filter(line=>line.trim()).map(line=>{const [start,end,mode]=line.split('|').map(x=>x.trim());const startIso=parseAustralianDate(start||''),endIso=parseAustralianDate(end||'');if(!startIso||!endIso||!['certified','uncertified'].includes(mode))throw new Error('Use valid DD/MM/YYYY | DD/MM/YYYY | certified or uncertified per line.');return {start_date:startIso,end_date:endIso,uncertified:mode==='uncertified'};});
    await apiClient.post(`${root}/employees/${employeeId}/configurations`,{reason,source_reference,legacy_resolution_reference:value(form,'legacy_resolution_reference'),enabled_codes:form.getAll('enabled_codes'),medical_rule:value(form,'medical_rule'),medical_history:history,history_confirmed:form.has('history_confirmed')});
  }else if(dialog.kind==='publish')await apiClient.post(`${root}/configurations/${dialog.target?.id}/publish`,{reason});
  else if(dialog.kind==='plan')await apiClient.post(`${root}/employees/${employeeId}/job-plans`,{reason,source_reference,code:value(form,'code'),calculation_confirmed:form.has('calculation_confirmed'),...(value(form,'code')==='recreation'?{first_post_end:value(form,'first_post_end'),payroll_anchor:value(form,'payroll_anchor'),temporary_start:value(form,'temporary_start')}:{})});
  else await apiClient.post(`${root}/job-plans/${dialog.target?.id}/approve`,{reason});
  setDialog(null);setNotice(dialog.kind==='approve-plan'?'Accrual plan approved.':dialog.kind==='plan'?'Accrual plan saved. Initial admin migration plans can be approved by that administrator; later changes need independent approval.':'Reviewed configuration saved. Publication/activation needs a different central HR officer.');setVersion(v=>v+1);
 }
 async function runJobs(id:string){setBusy(true);setError('');try{const result=await apiClient.post<{results:{code:string;posts?:{amount:string;capped:boolean}[];renewals?:{date:string;amount:string}[];paused?:boolean;more_due?:boolean}[]}>(`${root}/employees/${id}/run-jobs`,{});setNotice(result.results.length?result.results.map(r=>`${label(r.code)}: ${r.paused?'paused':`${r.posts?.length||0} due payroll postings, ${r.renewals?.length||0} anniversary renewals${r.more_due?' · more catch-up remains':''}`}`).join(' · '):'No independently approved job plan. No entitlement posted.');setVersion(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!data)return error?<p role="alert" className="text-sm text-red-700">{error}</p>:<LoadingState label="Loading government workflow controls…"/>;
 const teacher=!!facts?.periods?.find(p=>p.start_date<=today()&&(!p.end_date||p.end_date>=today()))?.is_teacher;
 const titles:Record<Dialog['kind'],string>={config:'Prepare common leave activation',publish:'Approve common leave activation',plan:'Prepare approved entitlement job plan','approve-plan':'Approve entitlement job plan'};
 return <div className="space-y-5">  {!selectedEmployeeId&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();const id=value(new FormData(e.currentTarget),'employee_id');if(!id){setError('Choose an employee.');return;}setEmployeeId(id);setFacts(null);setSelectedRequestId('');}}><DirectoryPicker name="employee_id" label="Employee for workflow controls" allowInactive/><Button type="submit">Load workflow employee</Button></form>}{error&&view==='applications'&&<p role="alert" className="text-sm text-red-700">{error}</p>}{view!=='applications'&&<section className="app-panel space-y-4 p-4 sm:p-5"><h3 className="text-lg font-semibold">Government common leave controls</h3><p className="text-sm text-gray-600">Activate reviewed Recreation, Medical and Special entitlements per employee. Policy/balance publication, submission activation and accrual approval are separate decisions.</p>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="rounded-lg bg-green-50 p-3 text-sm text-green-800">{notice}</p>}

  {employeeId&&facts&&<>{!selectedEmployeeId&&<h4 className="text-lg font-semibold">{facts.employee.display_name}</h4>}<BalanceCards entitlements={facts.entitlements}/>{facts.employee.leave_policy_regime!=='government'&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">This employee still uses the existing workflow. Login &amp; enrolment must be applied before Government activation. Enrolment pauses existing submissions until the preparation and independent activation are complete.</p>}<div className="flex flex-wrap gap-2"><Button disabled={facts.employee.leave_policy_regime!=='government'} onClick={()=>show('config')}>Prepare employee activation</Button><Button variant="secondary" disabled={facts.employee.leave_policy_regime!=='government'} onClick={()=>show('plan')}>Prepare entitlement job plan</Button><Button variant="secondary" loading={busy} disabled={facts.employee.leave_policy_regime!=='government'} onClick={()=>void runJobs(employeeId)}>Run approved due jobs</Button></div><p className="text-sm text-gray-600">Teachers activate Medical and Special here; teacher Recreation needs the separately reviewed discretionary route and dated work schedule. First certify openings and service in this employee’s preparation steps, then complete retained leave reconciliation. Missing/unknown inputs block activation. Jobs never post future balances.</p></>}
  <h4 className="font-semibold">Reviewed submission activation</h4>{data.configs.map(c=><article key={c.id} className="space-y-2 rounded-lg border border-gray-200 p-3"><h5 className="font-semibold">{c.display_name} · {c.status}</h5><p className="text-sm">{c.enabled_codes.length?c.enabled_codes.map(label).join(', '):'New submission and jobs paused after publication'}</p><p className="break-words text-sm text-gray-600">{c.source_reference}</p><p className="break-words text-sm">Historical/pending/future reconciliation: {c.legacy_resolution_reference}</p><p className="text-sm">Medical baseline: {formatDate(c.medical_period_start?.slice(0,10))} through cutover {formatDate(c.medical_as_of?.slice(0,10))} · {c.medical_rule==='single_verified_shift_nonadjacent_scheduled_days'?'one calendar shift / verified roster charge':'one calendar date / one policy day'}, separated by a scheduled day</p>{c.medical_history.length?<ul className="list-disc pl-5 text-sm">{c.medical_history.map((h,i)=><li key={i}>{formatDate(h.start_date)} to {formatDate(h.end_date)} · {h.uncertified?'Uncertified':'Certified'} · {h.charge} policy days</li>)}</ul>:<p className="text-sm">Reviewed register confirms no earlier medical absences in this service year.</p>}<p className="break-words text-sm text-gray-600">Recorded reason: {c.reason}</p>{c.status==='draft'&&<div className="flex flex-wrap gap-2"><DraftLifecycle kind="configuration" record={c} onChanged={()=>setVersion(v=>v+1)}/>{!c.discarded&&<Button variant="secondary" onClick={()=>show('config',c)}>Prepare corrected activation</Button>}</div>}{c.discarded&&<p className="text-sm text-gray-500">Deleted draft · retained in preparation history</p>}{c.status==='draft'&&!c.discarded&&(c.prepared_by===String(user?.id)?<p className="text-sm text-gray-500">A different central HR officer must approve your activation preview.</p>:<Button onClick={()=>show('publish',c)}>Approve activation for {c.display_name}</Button>)}</article>)}
  <h4 className="font-semibold">Entitlement job plans</h4><p className="text-sm text-gray-600">Review actual Payroll/HR calculations. The administrator who applied an initial staff migration can approve its first plan for each leave type. Later changes require independent approval. Scheduling follows the production setting. Run only reviewed due dates; retries reconcile to the same postings.</p>{data.plans.map(p=><article key={p.id} className="space-y-2 rounded-lg border border-gray-200 p-3"><h5 className="font-semibold">{p.display_name} · {label(p.code)} · {p.status}</h5><p className="text-sm">{p.code==='recreation'?`26 payroll cycles, cumulative rounding and calendar proration · anchor ${formatDate(p.payroll_anchor)} · first posting ${formatDate(p.first_post_end)}`:'Service-anniversary expiry and annual regrant; no carry-forward'}</p><p className="break-words text-sm text-gray-600">{p.source_reference}</p>{p.code==='recreation'&&<p className="text-sm">Temporary accrual starts: {p.temporary_start==='qualification'?'After twelve-month qualification':'From credited appointment service'}</p>}<p className="break-words text-sm text-gray-600">Recorded reason: {p.reason}</p>{p.status==='draft'&&<div className="flex flex-wrap gap-2"><DraftLifecycle kind="job" record={p} onChanged={()=>setVersion(v=>v+1)}/>{!p.discarded&&<Button variant="secondary" onClick={()=>show('plan',p)}>Prepare corrected job plan</Button>}</div>}{p.discarded&&<p className="text-sm text-gray-500">Deleted draft · retained in preparation history</p>}{p.status==='draft'&&!p.discarded&&(p.prepared_by===String(user?.id)&&!(p.initial_setup_review_id&&user?.role==='admin')?<p className="text-sm text-gray-500">A different central HR officer must approve this job plan.</p>:<Button onClick={()=>show('approve-plan',p)}>Approve {label(p.code)} job for {p.display_name}</Button>)}</article>)}
  <h4 className="font-semibold">Recorded Recreation cap events</h4>{!data.alerts.length?<p className="text-sm text-gray-500">No cap events recorded.</p>:data.alerts.map(a=><p key={a.id} className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{a.display_name} · {formatDate(a.event_date.slice(0,10))} · accrual stopped/capped. Review current credit and obtain Chief Secretary direction to take leave or authorised exceptional cash-out; Salary Unit pays any directed amount.</p>)}
 </section>}
 {view!=='activation'&&<>{employeeId&&facts&&facts.employee.leave_policy_regime==='government'&&<GovernmentCaseApplication employeeId={employeeId} assisted onChanged={()=>setVersion(v=>v+1)}/>}
 <GovernmentCaseTasks key={`tasks-${employeeId||'all'}`} employeeId={employeeId} refreshVersion={version} onSelect={setSelectedRequestId}/>
 <p className="text-sm text-gray-600">Applications and follow-ups remain in the selected employee context. Without an employee selection, this is the central HR operations queue.</p>
 <GovernmentRequestList key={`requests-${employeeId||'all'}`} employeeId={employeeId||undefined} mode="all" refreshVersion={version} selectedRequestId={selectedRequestId} onChanged={()=>setVersion(v=>v+1)}/></>}
 {dialog&&<ActionDialog title={titles[dialog.kind]} onClose={()=>setDialog(null)} onSave={save}>
   {dialog.target&&['config','plan'].includes(dialog.kind)&&<p className="rounded-lg bg-blue-50 p-3 text-sm">Prepare a new corrected preview with current foundations and signed references. The original remains in history; delete it separately when no longer wanted. Independent approval is still required.</p>}
   {dialog.kind==='config'&&<><p className="text-sm">Choose the common types ready for this employee. Leave all unchecked to prepare a pause. Historical and future leave must be reconciled; this never imports legacy usage automatically.</p><fieldset className="space-y-2"><legend className="text-sm font-semibold">Enable reviewed common leave types</legend>{['recreation','medical','special'].map(c=><label key={c} className="block text-sm"><input type="checkbox" name="enabled_codes" value={c} disabled={teacher&&c==='recreation'} defaultChecked={dialog.target&&'enabled_codes' in dialog.target?dialog.target.enabled_codes.includes(c)&&!(teacher&&c==='recreation'):false}/> {label(c)}</label>)}</fieldset><SourceField name="legacy_resolution_reference" label="Historical/pending/future leave reconciliation reference"/><Field label="Approved medical day and adjacency rule"><select name="medical_rule" required defaultValue="" className={inputClass}><option value="" disabled>Choose signed operational definition</option><option value="single_calendar_date_nonadjacent_scheduled_days">One calendar date / one policy day; separated by a scheduled day</option><option value="single_verified_shift_nonadjacent_scheduled_days">One calendar shift / verified roster charge; separated by a scheduled day</option></select></Field><Field label="Medical history before certified cutover"><textarea name="medical_history" defaultValue={dialog.target&&'medical_history' in dialog.target?dialog.target.medical_history.map(h=>`${formatDate(h.start_date)} | ${formatDate(h.end_date)} | ${h.uncertified?'uncertified':'certified'}`).join('\n'):''} rows={5} maxLength={15000} className={inputClass} placeholder="DD/MM/YYYY | DD/MM/YYYY | certified or uncertified (one absence per line)"/></Field><label className="block text-sm"><input name="history_confirmed" type="checkbox" required/> I reconciled all medical history before the opening date. Blank means the reviewed register confirms no prior absences in this service year.</label><SourceField/></>}
   {dialog.kind==='publish'&&<p className="text-sm">Approve the reviewed sources, enabled types, medical baseline and operational definition independently. Changed foundations reject this preview. Published configuration does not approve any leave.</p>}
   {dialog.kind==='plan'&&<><Field label="Job leave type"><select name="code" value={teacher&&code==='recreation'?'medical':code} onChange={e=>setCode(e.target.value)} className={inputClass}>{(teacher?['medical','special']:['recreation','medical','special']).map(c=><option key={c} value={c}>{label(c)}</option>)}</select></Field>{code==='recreation'&&!teacher?<><Field label="Confirmed Payroll fortnight end anchor"><AustralianDateInput name="payroll_anchor"  defaultValue={dialog.target&&'payroll_anchor' in dialog.target?dialog.target.payroll_anchor||'':''} required className={inputClass}/></Field><Field label="First posting after cutover"><AustralianDateInput name="first_post_end"  defaultValue={dialog.target&&'first_post_end' in dialog.target?dialog.target.first_post_end||'':''} required className={inputClass}/></Field><Field label="Temporary Recreation accrual begins"><select name="temporary_start" required defaultValue="" className={inputClass}><option value="" disabled>Choose approved treatment</option><option value="appointment">From credited appointment service</option><option value="qualification">After twelve-month qualification</option></select></Field><p className="text-sm text-gray-600">Supported reviewed method: 26 full fortnight postings sum exactly to the annual quantum. Partial fortnights use credited calendar days / 14, truncated at six decimals. The first period excludes dates before the certified opening; its as-of date is the start of cutover. Resolve payroll or policy-boundary exceptions before approving this method.</p></>:<p className="text-sm text-gray-600">Expire the unused old service-year credit, then grant Medical or Special under the effective policy. Pending holds block expiry. No historical Medical exemptions carry into a new automatically granted service year.</p>}<label className="block text-sm"><input type="checkbox" name="calculation_confirmed" required/> I have actual HR/Salary Unit approval for this anchor, proration/rounding, service-year and temporary-service treatment.</label><SourceField/></>}
   {dialog.kind==='approve-plan'&&<p className="text-sm">Approve the documented job calculation. Initial migration administrators can approve the first plan for each type; later changes need an independent officer. No future entitlement is posted. Missing inputs, changed service, retained holds and unreconciled future openings stop processing.</p>}
 </ActionDialog>}
 </div>;
}
