import {GovernmentCaseApplication,GovernmentCaseTasks} from './GovernmentCases';
import {useEffect,useState} from 'react';
import {apiClient} from '../../lib/api';
import {useAuth} from '../../contexts/useAuth';
import {Button,LoadingState} from '../../components/Ui';
import {ActionDialog,DirectoryPicker,Field,inputClass} from './ManagementFields';
import {value} from './managementForm';
import {BalanceCards} from './GovernmentFoundation';
import type {GovernmentEntitlement} from './GovernmentFoundation';
import {GovernmentRequestList} from './GovernmentRequests';
import {governmentLabel as label} from './governmentWorkflowTypes';
import type {WorkflowConfiguration,ConsentOffice,GovernmentJobPlan} from './governmentWorkflowTypes';
import type {OrgDepartment} from './types';
const root='/hr/government/workflow',today=()=>new Date(Date.now()+12*3600000).toISOString().slice(0,10);
type AdminData={configs:WorkflowConfiguration[];offices:ConsentOffice[];plans:GovernmentJobPlan[];alerts:{id:string;display_name:string;event_date:string;amount:string}[]};
type Dialog={kind:'config'|'publish'|'office'|'close-office'|'plan'|'approve-plan';target?:WorkflowConfiguration|ConsentOffice|GovernmentJobPlan};
function SourceField({label:caption='Approved source reference',name='source_reference'}:{label?:string;name?:string}){return <Field label={caption}><input name={name} required minLength={5} maxLength={500} className={inputClass}/></Field>;}
export function GovernmentWorkflowManagement({departments}:{departments:OrgDepartment[]}) {
 const {user}=useAuth();const [data,setData]=useState<AdminData|null>(null),[employeeId,setEmployeeId]=useState(''),[facts,setFacts]=useState<{employee:{display_name:string};entitlements:GovernmentEntitlement[]}|null>(null),[version,setVersion]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dialog,setDialog]=useState<Dialog|null>(null),[code,setCode]=useState('recreation'),[officeLevel,setOfficeLevel]=useState('relevant_secretary'),[busy,setBusy]=useState(false),[selectedRequestId,setSelectedRequestId]=useState('');
 useEffect(()=>{let live=true;void apiClient.get<AdminData>(`${root}/administration${employeeId?`?employee_id=${employeeId}`:''}`).then(r=>{if(live)setData(r);}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[version,employeeId]);
 useEffect(()=>{if(!employeeId)return;let live=true;void apiClient.get<NonNullable<typeof facts>>(`/hr/government/employees/${employeeId}`).then(r=>{if(live)setFacts(r);}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[version,employeeId]);
 function show(kind:Dialog['kind'],target?:Dialog['target']){setError('');setDialog({kind,target});}
 async function save(form:FormData){if(!dialog)return;const reason=value(form,'reason'),source_reference=value(form,'source_reference');
  if(dialog.kind==='config') {
    const history=value(form,'medical_history').split('\n').filter(line=>line.trim()).map(line=>{const [start,end,mode]=line.split('|').map(x=>x.trim());if(!start||!end||!['certified','uncertified'].includes(mode))throw new Error('Use YYYY-MM-DD | YYYY-MM-DD | certified or uncertified per line.');return {start_date:start,end_date:end,uncertified:mode==='uncertified'};});
    await apiClient.post(`${root}/employees/${employeeId}/configurations`,{reason,source_reference,legacy_resolution_reference:value(form,'legacy_resolution_reference'),enabled_codes:form.getAll('enabled_codes'),medical_rule:value(form,'medical_rule'),medical_history:history,history_confirmed:form.has('history_confirmed')});
  }else if(dialog.kind==='publish')await apiClient.post(`${root}/configurations/${dialog.target?.id}/publish`,{reason});
  else if(dialog.kind==='office')await apiClient.post(`${root}/consent-offices`,{reason,source_reference,level:value(form,'level'),department_id:value(form,'department_id')||null,approver_employee_id:value(form,'approver_employee_id'),effective_from:value(form,'effective_from'),effective_to:value(form,'effective_to')||null});
  else if(dialog.kind==='close-office')await apiClient.post(`${root}/consent-offices/${dialog.target?.id}/close`,{reason,effective_to:value(form,'effective_to')});
  else if(dialog.kind==='plan')await apiClient.post(`${root}/employees/${employeeId}/job-plans`,{reason,source_reference,code:value(form,'code'),calculation_confirmed:form.has('calculation_confirmed'),...(value(form,'code')==='recreation'?{first_post_end:value(form,'first_post_end'),payroll_anchor:value(form,'payroll_anchor'),temporary_start:value(form,'temporary_start')}:{})});
  else await apiClient.post(`${root}/job-plans/${dialog.target?.id}/approve`,{reason});
  setDialog(null);setNotice('Reviewed configuration saved. Publication/activation needs a different central HR officer.');setVersion(v=>v+1);
 }
 async function runJobs(id:string){setBusy(true);setError('');try{const result=await apiClient.post<{results:{code:string;posts?:{amount:string;capped:boolean}[];renewals?:{date:string;amount:string}[];paused?:boolean;more_due?:boolean}[]}>(`${root}/employees/${id}/run-jobs`,{});setNotice(result.results.length?result.results.map(r=>`${label(r.code)}: ${r.paused?'paused':`${r.posts?.length||0} due payroll postings, ${r.renewals?.length||0} anniversary renewals${r.more_due?' · more catch-up remains':''}`}`).join(' · '):'No independently approved job plan. No entitlement posted.');setVersion(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!data)return error?<p role="alert" className="text-sm text-red-700">{error}</p>:<LoadingState label="Loading government workflow controls…"/>;
 const titles:Record<Dialog['kind'],string>={config:'Prepare common leave activation',publish:'Approve common leave activation',office:'Assign statutory consent or HR verifier', 'close-office':'Close statutory office appointment',plan:'Prepare approved entitlement job plan','approve-plan':'Approve entitlement job plan'};
 return <div className="space-y-5"><section className="app-panel space-y-4 p-4 sm:p-5"><h3 className="text-lg font-semibold">Government common leave controls</h3><p className="text-sm text-gray-600">Activate reviewed Recreation, Medical and Special entitlements per employee. Policy/balance publication, submission activation and accrual approval are separate decisions.</p>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="rounded-lg bg-green-50 p-3 text-sm text-green-800">{notice}</p>}
  <form className="space-y-3" onSubmit={e=>{e.preventDefault();const id=value(new FormData(e.currentTarget),'employee_id');if(!id){setError('Choose an employee.');return;}setEmployeeId(id);setFacts(null);}}><DirectoryPicker name="employee_id" label="Employee for workflow controls" allowInactive/><Button type="submit">Load workflow employee</Button></form>
  {employeeId&&facts&&<><h4 className="text-lg font-semibold">{facts.employee.display_name}</h4><BalanceCards entitlements={facts.entitlements}/><div className="flex flex-wrap gap-2"><Button onClick={()=>show('config')}>Prepare employee activation</Button><Button variant="secondary" onClick={()=>show('plan')}>Prepare entitlement job plan</Button><Button variant="secondary" loading={busy} onClick={()=>void runJobs(employeeId)}>Run approved due jobs</Button></div><p className="text-sm text-gray-600">First certify openings and service under Policy & balances. Missing/unknown inputs block activation. Jobs never post future balances.</p></>}
  <h4 className="font-semibold">Reviewed submission activation</h4>{data.configs.map(c=><article key={c.id} className="space-y-2 rounded-lg border border-gray-200 p-3"><h5 className="font-semibold">{c.display_name} · {c.status}</h5><p className="text-sm">{c.enabled_codes.length?c.enabled_codes.map(label).join(', '):'New submission and jobs paused after publication'}</p><p className="break-words text-sm text-gray-600">{c.source_reference}</p><p className="break-words text-sm">Historical/pending/future reconciliation: {c.legacy_resolution_reference}</p><p className="text-sm">Medical baseline: {c.medical_period_start?.slice(0,10)} through cutover {c.medical_as_of?.slice(0,10)} · one calendar date / one policy day, separated by a scheduled day</p>{c.medical_history.length?<ul className="list-disc pl-5 text-sm">{c.medical_history.map((h,i)=><li key={i}>{h.start_date} to {h.end_date} · {h.uncertified?'Uncertified':'Certified'} · {h.charge} policy days</li>)}</ul>:<p className="text-sm">Reviewed register confirms no earlier medical absences in this service year.</p>}<p className="break-words text-sm text-gray-600">Recorded reason: {c.reason}</p>{c.status==='draft'&&(c.prepared_by===String(user?.id)?<p className="text-sm text-gray-500">A different central HR officer must approve your activation preview.</p>:<Button onClick={()=>show('publish',c)}>Approve activation for {c.display_name}</Button>)}</article>)}
  <h4 className="font-semibold">Entitlement job plans</h4><p className="text-sm text-gray-600">Plans require actual Payroll/HR authority and independent approval. Unattended government scheduling remains off in local Docker. Run only reviewed due dates; retries reconcile to the same postings.</p>{data.plans.map(p=><article key={p.id} className="space-y-2 rounded-lg border border-gray-200 p-3"><h5 className="font-semibold">{p.display_name} · {label(p.code)} · {p.status}</h5><p className="text-sm">{p.code==='recreation'?`26 payroll cycles, cumulative rounding and calendar proration · anchor ${p.payroll_anchor} · first posting ${p.first_post_end}`:'Service-anniversary expiry and annual regrant; no carry-forward'}</p><p className="break-words text-sm text-gray-600">{p.source_reference}</p>{p.code==='recreation'&&<p className="text-sm">Temporary accrual starts: {p.temporary_start==='qualification'?'After twelve-month qualification':'From credited appointment service'}</p>}<p className="break-words text-sm text-gray-600">Recorded reason: {p.reason}</p>{p.status==='draft'&&(p.prepared_by===String(user?.id)?<p className="text-sm text-gray-500">A different central HR officer must approve this job plan.</p>:<Button onClick={()=>show('approve-plan',p)}>Approve {label(p.code)} job for {p.display_name}</Button>)}</article>)}
  <h4 className="font-semibold">Recorded Recreation cap events</h4>{!data.alerts.length?<p className="text-sm text-gray-500">No cap events recorded.</p>:data.alerts.map(a=><p key={a.id} className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{a.display_name} · {a.event_date.slice(0,10)} · accrual stopped/capped. Review current credit and obtain Chief Secretary direction to take leave or authorised exceptional cash-out; Salary Unit pays any directed amount.</p>)}
 </section>
 <section className="app-panel space-y-4 p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-lg font-semibold">Additional statutory and evidence offices</h3><Button onClick={()=>show('office')}>Assign consent office</Button></div><p className="text-sm text-gray-600">Division, HOD and Chief Secretary appointments remain under Organisation & approvers. These offices add the department's relevant Secretary and an independent central HR verifier.</p>{data.offices.map(o=><article key={o.id} className="space-y-2 rounded-lg border border-gray-200 p-3"><h4 className="font-semibold">{label(o.level)} · {o.display_name}{o.closed_office_id?' · closure recorded':''}</h4><p className="text-sm">{o.effective_from} to {o.effective_to||'open'} · {o.department_id?departments.find(d=>d.id===o.department_id)?.name||'Managed department':'Government-wide HR verification'}</p><p className="break-words text-sm text-gray-600">{o.source_reference}</p>{!o.closed_office_id&&<Button variant="secondary" onClick={()=>show('close-office',o)}>Close office appointment</Button>}</article>)}</section>
 {employeeId&&facts&&<GovernmentCaseApplication employeeId={employeeId} assisted onChanged={()=>setVersion(v=>v+1)}/>}
 <GovernmentCaseTasks key={employeeId||'all'} employeeId={employeeId} refreshVersion={version} onSelect={setSelectedRequestId}/>
 <GovernmentRequestList key={employeeId||'all'} mode="all" refreshVersion={version} selectedRequestId={selectedRequestId} onChanged={()=>setVersion(v=>v+1)}/>
 {dialog&&<ActionDialog title={titles[dialog.kind]} onClose={()=>setDialog(null)} onSave={save}>
   {dialog.kind==='config'&&<><p className="text-sm">Choose the common types ready for this employee. Leave all unchecked to prepare a pause. Historical and future leave must be reconciled; this never imports legacy usage automatically.</p><fieldset className="space-y-2"><legend className="text-sm font-semibold">Enable reviewed common leave types</legend>{['recreation','medical','special'].map(c=><label key={c} className="block text-sm"><input type="checkbox" name="enabled_codes" value={c}/> {label(c)}</label>)}</fieldset><SourceField name="legacy_resolution_reference" label="Historical/pending/future leave reconciliation reference"/><Field label="Approved medical day and adjacency rule"><select name="medical_rule" required defaultValue="" className={inputClass}><option value="" disabled>Choose signed operational definition</option><option value="single_calendar_date_nonadjacent_scheduled_days">One calendar date / one policy day; separated by a scheduled day</option></select></Field><Field label="Medical history before certified cutover"><textarea name="medical_history" rows={5} maxLength={15000} className={inputClass} placeholder="YYYY-MM-DD | YYYY-MM-DD | certified or uncertified (one absence per line)"/></Field><label className="block text-sm"><input name="history_confirmed" type="checkbox" required/> I reconciled all medical history before the opening date. Blank means the reviewed register confirms no prior absences in this service year.</label><SourceField/></>}
   {dialog.kind==='publish'&&<p className="text-sm">Approve the reviewed sources, enabled types, medical baseline and operational definition independently. Changed foundations reject this preview. Published configuration does not approve any leave.</p>}
   {dialog.kind==='office'&&<><Field label="Consent or evidence office"><select name="level" className={inputClass} value={officeLevel} onChange={e=>setOfficeLevel(e.target.value)}><option value="relevant_secretary">Relevant Secretary</option><option value="hr_verifier">Central HR verifier</option><option value="minister">Minister for medical escalation</option></select></Field>{officeLevel!=='hr_verifier'&&<Field label="Statutory office department"><select name="department_id" className={inputClass} required><option value="">Choose managed department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field>}<DirectoryPicker name="approver_employee_id" label="Consent officeholder" requireLinked/><Field label="Office effective from"><input name="effective_from" type="date" required defaultValue={today()} className={inputClass}/></Field><Field label="Office effective through"><input name="effective_to" type="date" className={inputClass}/></Field><p className="text-sm text-gray-600">The Secretary and Minister need an explicit approval grant; the HR verifier needs central HR authority. Appointment does not grant account permissions.</p><SourceField/></>}
   {dialog.kind==='close-office'&&<><p className="text-sm">Record the inclusive last effective date without deleting appointment history. Pending bindings need explicit review after an office change.</p><Field label="Last effective office date"><input name="effective_to" type="date" required className={inputClass}/></Field></>}
   {dialog.kind==='plan'&&<><Field label="Job leave type"><select name="code" value={code} onChange={e=>setCode(e.target.value)} className={inputClass}>{['recreation','medical','special'].map(c=><option key={c} value={c}>{label(c)}</option>)}</select></Field>{code==='recreation'?<><Field label="Confirmed Payroll fortnight end anchor"><input name="payroll_anchor" type="date" required className={inputClass}/></Field><Field label="First posting after cutover"><input name="first_post_end" type="date" required className={inputClass}/></Field><Field label="Temporary Recreation accrual begins"><select name="temporary_start" required defaultValue="" className={inputClass}><option value="" disabled>Choose approved treatment</option><option value="appointment">From credited appointment service</option><option value="qualification">After twelve-month qualification</option></select></Field><p className="text-sm text-gray-600">Supported reviewed method: 26 full fortnight postings sum exactly to the annual quantum. Partial fortnights use credited calendar days / 14, truncated at six decimals. The first period excludes dates before the certified opening; its as-of date is the start of cutover. Resolve payroll or policy-boundary exceptions before approving this method.</p></>:<p className="text-sm text-gray-600">Expire the unused old service-year credit, then grant Medical or Special under the effective policy. Pending holds block expiry. No historical Medical exemptions carry into a new automatically granted service year.</p>}<label className="block text-sm"><input type="checkbox" name="calculation_confirmed" required/> I have actual HR/Salary Unit approval for this anchor, proration/rounding, service-year and temporary-service treatment.</label><SourceField/></>}
   {dialog.kind==='approve-plan'&&<p className="text-sm">Independently approve the documented job calculation. No future entitlement is posted. Missing inputs, changed service, retained holds and unreconciled future openings stop processing.</p>}
 </ActionDialog>}
 </div>;
}
