import { formatDate } from '../../lib/date';
import { formatDateTime } from '../../lib/date';
import {useEffect,useState} from 'react';
import {apiClient} from '../../lib/api';
import {useAuth} from '../../contexts/useAuth';
import {Button,LoadingState,Pager} from '../../components/Ui';
import {ActionDialog,Field,inputClass} from './ManagementFields';
import {value} from './managementForm';
import type {OrgDepartment} from './types';
import {ReviewRecordName,ReviewRecordReference} from './ReviewRecordName';
import {GovernmentCommissioning} from './GovernmentCommissioning';
import {GovernmentBenefitReconciliation} from './GovernmentBenefitReconciliation';
import {GovernmentAssistedCoverage} from './GovernmentAssistedCoverage';
import {reviewRecordLabel} from './reviewRecordNames';

const root='/hr/government/rollout';
const evidenceLabels:Record<string,string>={policy_cases:'Signed policy examples and pilot cases',access_review:'Access, keyboard and mobile review',capacity:'Capacity rehearsal and hosting assessment',restore:'Verified backup restore and recovery owner',training:'Employee and approver training',support:'Support owner and escalation process',assisted_cases:'Assisted-case routes and responsible officers',single_accrual_engine:'Accrual ownership and scheduler cutover'};
type Person={id:string;employment_category?:string|null;join_date?:string|null;display_name:string;external_ids:{external_id:string}[]};
type Readiness={employee_id:string;display_name:string;payroll_id:string|null;ready:boolean;issues:string[]};
type Preview={as_of:string;employees:Readiness[];ready:number;total:number};
type Wave={id:string;label:string;kind:string;prepared_by:string;snapshot_hash:string;as_of:string;ready:number;total:number;approved_by:string|null};
type Register={id:string;period_start:string;period_end:string;version:number;receipt_reference:string|null;latest:boolean};
type Operations={totals:Record<string,number>;job_runs:{id:string;started_at:string;summary:{employees:number;changed:number;blocked:{employee_id:string;message:string}[]}}[];schedulers:{government:boolean;legacy:boolean};email_configured:boolean;activation:string};
async function download(id:string){const blob=await apiClient.getBlob(`${root}/waves/${id}/export`),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`leave-cohort-${id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function GovernmentRollout({departments}:{departments:OrgDepartment[]}){
 const {user}=useAuth();
 const [regime,setRegime]=useState<'legacy'|'government'|'excluded'>('legacy');
 const [operations,setOperations]=useState<Operations|null>(null),[department,setDepartment]=useState(''),[page,setPage]=useState(0),[people,setPeople]=useState<Person[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[version,setVersion]=useState(0);
 const [waves,setWaves]=useState<Wave[]>([]),[wavePage,setWavePage]=useState(0),[waveTotal,setWaveTotal]=useState(0),[registers,setRegisters]=useState<Register[]>([]),[registerPage,setRegisterPage]=useState(0),[registerTotal,setRegisterTotal]=useState(0),[dialog,setDialog]=useState<{key:string;wave?:Wave}|null>(null);
 useEffect(()=>{let live=true;void apiClient.get<Operations>(`${root}/operations`).then(r=>{if(live)setOperations(r);}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[version]);
 useEffect(()=>{let live=true;void apiClient.get<{waves:Wave[];total:number}>(`${root}/waves?page=${wavePage+1}`).then(r=>{if(live){setWaves(r.waves);setWaveTotal(r.total);}}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[wavePage,version]);
 useEffect(()=>{if(!department)return;let live=true;setLoading(true);void apiClient.get<{employees:Person[];total:number}>(`/hr/directory?department_id=${department}&status=active&regime=${regime==='government'?'government':'legacy'}${regime==='government'?'':`&contract_without_leave=${regime==='excluded'?'only':'exclude'}`}&page=${page+1}`).then(r=>{if(live){setPeople(r.employees);setTotal(r.total);}}).catch((e:Error)=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[department,page,version,regime]);
 useEffect(()=>{if(!dialog||dialog.wave)return;let live=true;void apiClient.get<{registers:Register[];total:number}>(`/hr/government/payroll/registers?page=${registerPage+1}`).then(r=>{if(live){setRegisters(r.registers);setRegisterTotal(r.total);}}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[dialog,registerPage]);
 const select=(next:string[])=>{setSelected(next);setPreview(null);};
 const check=async()=>{setBusy(true);setError('');try{setPreview(await apiClient.post<Preview>(`${root}/preview`,{employee_ids:selected}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const save=async(f:FormData)=>{
  if(!dialog)return;
  if(dialog.wave){await apiClient.post(`${root}/waves/${dialog.wave.id}/approve`,{snapshot_hash:dialog.wave.snapshot_hash,reason:value(f,'reason')});setNotice('Independent cohort review recorded. Per-employee activation and scheduler controls remain in Applications & jobs.');}
  else{await apiClient.post(`${root}/waves`,{wave_id:dialog.key,label:value(f,'label'),kind:value(f,'kind'),employee_ids:selected,payroll_batch_ids:[value(f,'payroll_1'),value(f,'payroll_2')],source_reference:value(f,'source_reference'),reason:value(f,'reason'),evidence:Object.fromEntries(Object.keys(evidenceLabels).map(key=>[key,value(f,key)]))});setNotice('Cohort evidence frozen for independent review.');}
  setDialog(null);setVersion(v=>v+1);
 };
 return <section className="space-y-5">
  <div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-semibold text-gray-900">Staff migration & readiness</h3><p className="mt-1 text-sm text-gray-500">{regime==='legacy'?'Select existing staff below, then use Consolidate existing staff for the initial admin migration. Awaiting migration shows staff who still need the switch. Use Migrated staff to check those already migrated. Review groups of up to 50.':regime==='excluded'?'These contract staff have no leave entitlement recorded. Their existing profiles and history are retained. No opening credits or leave migration are required.':'These staff have moved to Government leave. Select them to check operating readiness and review any remaining setup.'}</p></div><Button variant="secondary" onClick={()=>{select([]);setPage(0);setVersion(v=>v+1);}}>Refresh</Button></div>
  {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="text-sm text-green-800">{notice}</p>}
  {operations&&<><div className="grid gap-3 sm:grid-cols-3">{[['pending_requests','Awaiting decisions'],['missing_officeholders','Applications missing officeholders'],['registers_due','Payroll receipts due']].map(([key,label])=><div key={key} className="app-panel p-4"><p className="text-sm text-gray-500">{label}</p><p className="mt-1 text-2xl font-semibold text-gray-900">{operations.totals[key]}</p></div>)}</div><p className="text-xs text-gray-500">Government scheduler: {operations.schedulers.government?'on':'off'} · Historical scheduler: {operations.schedulers.legacy?'on':'off'} · Email: {operations.email_configured?'configured':'off'} · Opening reviews: {operations.totals.openings_due} · Job plans: {operations.totals.job_plans_due} · Salary acknowledgements: {operations.totals.salary_acknowledgements_due}</p></>}
  <div className="app-panel space-y-4 p-4">
   <div className="flex flex-wrap items-end gap-3"><div className="min-w-0 flex-1"><Field label="Department for this cohort"><select className={inputClass} value={department} onChange={e=>{setDepartment(e.target.value);setPage(0);select([]);setPeople([]);setTotal(0);}}><option value="">Choose department</option>{departments.map(d=><option key={d.id} value={d.id}>{reviewRecordLabel(d.name)}</option>)}</select></Field></div><Field label="Staff to show"><select className={inputClass} value={regime} onChange={e=>{setRegime(e.target.value as 'legacy'|'government'|'excluded');setPage(0);select([]);setPeople([]);setTotal(0);}}><option value="legacy">Awaiting migration</option><option value="government">Migrated staff</option><option value="excluded">Contract staff — no leave entitlement</option></select></Field><Button variant="secondary" disabled={regime==='excluded'||!people.length||busy||loading} onClick={()=>select(people.map(p=>p.id))}>Select this page</Button><Button variant="secondary" disabled={!selected.length||busy} onClick={()=>select([])}>Clear</Button></div>
   {loading?<LoadingState label="Loading department…"/>:department&&!people.length?<p role="status" className="text-sm text-gray-600">{regime==='legacy'?'No staff awaiting migration in this department.':regime==='excluded'?'No contract staff without leave entitlement in this department.':'No migrated staff in this department.'}</p>:<div className="divide-y divide-gray-100">{people.map(p=><label key={p.id} className="flex cursor-pointer items-start gap-3 py-3 text-sm"><input type="checkbox" className="mt-1" checked={selected.includes(p.id)} disabled={regime==='excluded'||busy||(!selected.includes(p.id)&&selected.length>=50)} onChange={e=>select(e.target.checked?[...selected,p.id]:selected.filter(id=>id!==p.id))}/><span className="min-w-0 break-words"><span className="font-medium text-gray-900"><ReviewRecordName name={p.display_name}/></span><span className="block text-xs text-gray-500">{p.external_ids.map(x=>x.external_id).join(', ')||'Payroll ID unverified'}</span></span></label>)}</div>}
   {department&&<Pager page={page} pageCount={Math.ceil(total/50)} total={total} pageSize={50} setPage={setPage}/>}
   {regime!=='excluded'&&<div className="flex flex-wrap items-center gap-3"><Button disabled={!selected.length||loading} loading={busy} onClick={()=>void check()}>Check operating readiness</Button><p className="text-sm text-gray-500">{selected.length} of 50 selected</p>{preview&&<Button variant="secondary" onClick={()=>{setRegisterPage(0);setDialog({key:crypto.randomUUID()});}}>Prepare operational review</Button>}</div>}
  </div>
  {preview&&<div className="app-panel divide-y divide-gray-100"><p role="status" className="p-4 text-sm font-medium">{preview.ready} of {preview.total} ready on {formatDate(preview.as_of)}</p>{preview.employees.map(p=><article key={p.employee_id} className="p-4"><p className="text-sm font-semibold"><ReviewRecordName name={p.display_name}/><span className={`ml-2 font-normal ${p.ready?'text-green-700':'text-amber-800'}`}>{p.ready?'Ready for review':'Needs preparation'}</span></p>{p.issues.length>0&&<ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-gray-600">{p.issues.map(i=><li key={i}>{i}</li>)}</ul>}</article>)}</div>}
  {regime==='legacy'&&<GovernmentCommissioning selected={selected} names={Object.fromEntries(people.map(p=>[p.id,p.display_name]))} starts={Object.fromEntries(people.map(p=>[p.id,p.join_date?.slice(0,10)||'']))} categories={Object.fromEntries(people.map(p=>[p.id,p.employment_category||'']))} onChanged={()=>setVersion(v=>v+1)} onMigrated={()=>{select([]);setPage(0);setVersion(v=>v+1);}}/>}
  <GovernmentAssistedCoverage selected={selected} onChanged={()=>{setPreview(null);setVersion(v=>v+1);}}/>
  <div className="space-y-3 border-t border-gray-200 pt-4"><p className="text-sm font-semibold text-gray-900">Operational cohort reviews</p>{!waves.length&&<p className="text-sm text-gray-500">No frozen cohort reviews yet. Payroll and operational evidence must be available before preparing a release.</p>}{waves.map(w=><article key={w.id} className="app-panel space-y-2 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold"><ReviewRecordName name={w.label}/></p><ReviewRecordReference name={w.label}/><p className="text-xs text-gray-500">{w.kind} · {formatDate(w.as_of)} · {w.ready}/{w.total} ready when prepared · {w.approved_by?'Independently reviewed':'Awaiting review'}</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>void download(w.id).catch((e:Error)=>setError(e.message))}>Download review</Button>{!w.approved_by&&w.prepared_by!==String(user?.id)&&<Button disabled={w.ready!==w.total} onClick={()=>setDialog({key:crypto.randomUUID(),wave:w})}>Approve cohort review</Button>}</div></div><p className="break-all text-xs text-gray-400">SHA-256 {w.snapshot_hash}</p></article>)}<Pager page={wavePage} pageCount={Math.ceil(waveTotal/50)} total={waveTotal} pageSize={50} setPage={setWavePage}/></div>
  <GovernmentBenefitReconciliation selected={selected}/>
  <details className="border-t border-gray-200 pt-4"><summary className="cursor-pointer text-sm font-medium text-gray-600">Recent scheduled job runs</summary><div className="mt-3 space-y-3">{!operations?.job_runs.length&&<p className="text-sm text-gray-500">No scheduled run recorded. Local review schedulers remain off; approved manual jobs can be reviewed under Applications & jobs.</p>}{operations?.job_runs.map(r=><article key={r.id} className="rounded-lg border border-gray-200 p-3 text-sm"><p>{formatDateTime(r.started_at)} · {r.summary.employees} employees · {r.summary.changed} changed · {r.summary.blocked.length} blocked</p>{r.summary.blocked.slice(0,50).map(x=><p key={x.employee_id} className="mt-1 break-words text-xs text-amber-800">{x.employee_id}: {x.message}</p>)}{r.summary.blocked.length>50&&<p className="text-xs text-gray-500">Showing the first 50 blocked employees; use the operator run log for the complete run.</p>}</article>)}</div></details>
  {dialog&&<ActionDialog title={dialog.wave?'Approve cohort review':'Prepare release review'} onClose={()=>setDialog(null)} onSave={save} saveLabel={dialog.wave?'Record independent review':'Freeze review'}>{dialog.wave?<><p className="text-sm text-gray-600">{operations?.activation}</p><p className="break-all text-xs text-gray-500">{dialog.wave.snapshot_hash}</p><label className="flex gap-2 text-sm"><input type="checkbox" required/> I reviewed the downloaded record, both Payroll cycles and the referenced operational evidence. Rehearsal evidence is not production acceptance.</label></>:<><Field label="Cohort name"><input name="label" className={inputClass} required minLength={5} maxLength={500}/></Field><Field label="Review purpose"><select name="kind" className={inputClass}><option value="rehearsal">Local rehearsal</option><option value="pilot">Pilot release</option><option value="department">Department release</option></select></Field><p className="text-sm text-gray-500">Choose two independently reconciled, current Payroll registers with representative grants from this cohort.</p><div className="grid gap-3 sm:grid-cols-2">{[1,2].map(n=><Field key={n} label={`Payroll cycle ${n}`}><select name={`payroll_${n}`} className={inputClass} required><option value="">Choose reconciled cycle</option>{registers.filter(r=>r.latest&&r.receipt_reference).map(r=><option key={r.id} value={r.id}>{formatDate(r.period_start)} to {formatDate(r.period_end)} · v{r.version}</option>)}</select></Field>)}</div><Pager page={registerPage} pageCount={Math.ceil(registerTotal/50)} total={registerTotal} pageSize={50} setPage={setRegisterPage}/><Field label="Release authority reference"><input name="source_reference" className={inputClass} required minLength={5} maxLength={500}/></Field><div className="grid gap-3 sm:grid-cols-2">{Object.entries(evidenceLabels).map(([key,label])=><Field key={key} label={label}><input name={key} className={inputClass} required minLength={5} maxLength={500} placeholder="Reviewed evidence reference"/></Field>)}</div><p className="text-sm text-gray-500">Record actual evidence references. The server checks identity, entitlement, authority and Payroll facts again at independent review. The review retains preparation issues and does not change balances or activate employees.</p></>}</ActionDialog>}
 </section>;
}
