import {useEffect,useState} from 'react';
import {apiClient} from '../../lib/api';
import {useAuth} from '../../contexts/useAuth';
import {Button} from '../../components/Ui';
import {ActionDialog} from './ManagementFields';
import {value} from './managementForm';
import type {ServicePeriod} from './managementTypes';
type Correction={id:string;prepared_by:string;status:string;source_reference:string;recorded_at:string;before_snapshot:ServicePeriod;proposed:ServicePeriod;reason:string};
const root='/hr/directory/service-corrections';
export function ServiceCorrectionHistory({employeeId,onChanged}:{employeeId:string;onChanged:()=>Promise<void>}){
 const {user}=useAuth();const [rows,setRows]=useState<Correction[]>([]),[version,setVersion]=useState(0),[error,setError]=useState(''),[dialog,setDialog]=useState<{row:Correction;action:'approve'|'discard'|'restore'}|null>(null);
 useEffect(()=>{let live=true;void apiClient.get<Correction[]>(`${root}/employees/${employeeId}`).then(r=>{if(live)setRows(r);}).catch((e:Error)=>{if(live)setError(e.message);});return()=>{live=false;};},[employeeId,version]);
 return <>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{rows.length>0&&<details open><summary className="cursor-pointer text-sm font-medium">Appointment correction history ({rows.length})</summary><div className="mt-2 space-y-2">{rows.map(r=><article key={r.id} className="rounded-lg border border-gray-200 p-3 text-sm"><p className="font-medium">{r.status} · {r.recorded_at.slice(0,10)}</p><p>{r.before_snapshot.start_date} / {r.before_snapshot.employment_category} → {r.proposed.start_date} / {r.proposed.employment_category}</p><p>Corrected end: {r.proposed.end_date||'Open'} · {r.proposed.is_teacher?'Teacher':'Non-teacher'} · {r.proposed.is_intern?'Intern':'Non-intern'} · Service credit: {r.proposed.counts_for_service===null?'Unknown':r.proposed.counts_for_service?'Included':'Excluded'} · Work pattern: {r.proposed.work_pattern_id||'Unverified'}</p><p className="break-words text-gray-600">{r.source_reference} · {r.reason}</p><div className="mt-2 flex flex-wrap gap-2">{r.status==='draft'&&<>{r.prepared_by!==String(user?.id)?<Button onClick={()=>setDialog({row:r,action:'approve'})}>Approve appointment correction</Button>:<p>A different central HR officer must approve this correction.</p>}<Button variant="secondary" onClick={()=>setDialog({row:r,action:'discard'})}>Delete correction draft</Button></>}{r.status==='discarded'&&<Button variant="secondary" onClick={()=>setDialog({row:r,action:'restore'})}>Restore correction draft</Button>}</div></article>)}</div></details>}{dialog&&<ActionDialog title={dialog.action==='approve'?'Independently approve appointment correction':dialog.action==='discard'?'Delete correction draft':'Restore correction draft'} onClose={()=>setDialog(null)} onSave={async form=>{await apiClient.post(`${root}/${dialog.row.id}/${dialog.action==='approve'?'approve':'lifecycle'}`,{reason:value(form,'reason'),...(dialog.action==='approve'?{}:{action:dialog.action})});setDialog(null);setVersion(v=>v+1);await onChanged();}}><p className="text-sm text-gray-600">{dialog.action==='approve'?'Verify the appointment instrument, dates, category and service credit independently. Existing balances and approved leave remain preserved. New activation and job plans require review; affected pending leave must be cancelled and resubmitted.':'Retain the correction facts in history. This does not change employee service or balances.'}</p><label className="block text-sm"><input type="checkbox" required/> I reviewed the proposed appointment facts and selected action.</label></ActionDialog>}</>;
}
