import {describe,test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {connectTestDatabase,resetLeaveTables,skipWithoutDatabase} from '../test-support/database.js';
import {DEFAULT_RULES} from '../lib/governmentLeaveRules.js';
describe('government preparation lifecycle and verified appointment correction',{skip:skipWithoutDatabase},()=>{
 let pool,l,w,d,c,directory,hr,certifier,owner,employee,period,policy,server,base,auth;
 const reason='Verified local test correction against authorised appointment records.';
 const user=row=>({...row,permissions:row.permissions});
 before(async()=>{pool=await connectTestDatabase();l=await import('./governmentLeave.js');w=await import('./governmentLeaveWorkflow.js');d=await import('./governmentLeaveDrafts.js');c=await import('./employeeServiceCorrections.js');directory=await import('./employeeDirectory.js');auth=await import('./authService.js');const express=(await import('express')).default,errors=await import('../middleware/errors.js');errors.enableAsyncErrors();const app=express();app.use(express.json());app.use('/api/hr',(await import('../routes/hr.js')).default);app.use(errors.notFoundHandler);app.use(errors.errorHandler);server=await new Promise(resolve=>{const running=app.listen(0,'127.0.0.1',()=>resolve(running));});base=`http://127.0.0.1:${server.address().port}`;});
 after(async()=>{if(server)await new Promise(resolve=>server.close(resolve));await pool?.end();});
 async function account(permissions){return(await pool.query("INSERT INTO reviewers(email,display_name,role,password_hash,permissions) VALUES($1,'Test HR officer','user','x',$2) RETURNING *",[`${randomUUID()}@example.test`,permissions])).rows[0];}
 beforeEach(async()=>{await resetLeaveTables(pool);await pool.query('TRUNCATE hr_gov_policy_versions,hr_gov_calendars,hr_gov_pattern_approvals CASCADE');hr=await account({hr_access:true,hr_admin:true});certifier=await account({hr_access:true,hr_admin:true});owner=await account({hr_access:true,hr_leave_apply:true});employee=(await pool.query("INSERT INTO hr_employees(display_name,reviewer_id,leave_policy_regime) VALUES('Test correction employee',$1,'government') RETURNING *",[owner.id])).rows[0];period=await directory.addServicePeriod(pool,{employeeId:employee.id,actor:hr,reason,period:{start_date:'2026-01-01',employment_category:'permanent',counts_for_service:true}});policy=await l.createPolicy(pool,{user:user(hr),actor:hr,data:{label:'Test corrected policy',effective_from:'2026-01-01',effective_to:'2027-12-31',rules:DEFAULT_RULES,source_reference:'Test policy source',reason}});});
 async function configuration(){return w.prepareConfiguration(pool,{user:user(hr),actor:hr,employeeId:employee.id,data:{enabled_codes:[],medical_rule:'single_calendar_date_nonadjacent_scheduled_days',medical_history:[],source_reference:'Test no new application activation',legacy_resolution_reference:'Test verified historic cutover',reason}});}
 const lifecycle=(kind,id,action,expected_revision,by=hr)=>d.changeDraftState(pool,{user:user(by),actor:by,kind,id,data:{action,expected_revision,reason}});
 test('deleted activation cannot publish; restore retains facts and stale revisions fail',async()=>{const row=await configuration();assert.equal((await lifecycle('configuration',row.id,'discard',0)).discarded,true);await assert.rejects(w.publishConfiguration(pool,{user:user(certifier),actor:certifier,id:row.id,reason}),/discarded/);await assert.rejects(lifecycle('configuration',row.id,'restore',0),/changed/);assert.equal((await lifecycle('configuration',row.id,'restore',1)).discarded,false);await w.publishConfiguration(pool,{user:user(certifier),actor:certifier,id:row.id,reason});await assert.rejects(lifecycle('configuration',row.id,'discard',2),/Published and certified/);assert.equal((await pool.query('SELECT COUNT(*)::int n FROM hr_gov_draft_events WHERE draft_id=$1',[row.id])).rows[0].n,2);});
 test('opening and job previews retain facts and protected history; no ledger changes',async()=>{
 const opening=(await pool.query("INSERT INTO hr_gov_openings(employee_id,code,policy_version_id,period_start,period_end,as_of,amount,source_reference,payroll_reference,snapshot_hash,historical_snapshot,prepared_by,reason) VALUES($1,'medical',$2,'2026-01-01','2026-12-31','2026-10-07',10,'Test register','Test payroll','test','[]',$3,$4) RETURNING *",[employee.id,policy.id,hr.id,reason])).rows[0];
 await lifecycle('opening',opening.id,'discard',0);await assert.rejects(l.certifyOpening(pool,{user:user(certifier),actor:certifier,id:opening.id,reason}),/discarded/);await lifecycle('opening',opening.id,'restore',1);
 const basis=await l.addFoundationRecord(pool,{user:user(hr),actor:hr,employeeId:employee.id,kind:'basis',data:{effective_from:'2026-01-01',continuity_start:'2026-01-01',anniversary_method:'calendar',leap_day_method:'feb28',schedule_mode:'weekly',source_reference:'Test service basis',reason}});
 const job=(await pool.query("INSERT INTO hr_gov_job_plans(employee_id,code,service_basis_id,method,source_reference,prepared_by,reason,snapshot_hash) VALUES($1,'medical',$2,'service_anniversary_reset','Test annual grant',$3,$4,'test') RETURNING *",[employee.id,basis.id,hr.id,reason])).rows[0];await lifecycle('job',job.id,'discard',0);const jobs=await import('./governmentLeaveJobs.js');await assert.rejects(jobs.approveJobPlan(pool,{user:user(certifier),actor:certifier,id:job.id,reason}),/discarded/);assert.equal((await pool.query('SELECT COUNT(*)::int n FROM hr_gov_ledger')).rows[0].n,0);
 await assert.rejects(pool.query('DELETE FROM hr_gov_draft_events WHERE draft_id=$1',[job.id]),/immutable/);
 });
 test('revoked or scoped HR cannot delete/restore preparation',async()=>{const row=await configuration();await assert.rejects(lifecycle('configuration',row.id,'discard',0,owner),e=>e.status===403);await pool.query("UPDATE reviewers SET permissions='{}' WHERE id=$1",[hr.id]);await assert.rejects(lifecycle('configuration',row.id,'discard',0),e=>e.status===403);});
 async function prepare(overrides={}){const profile=await directory.employeeProfile(pool,employee.id),p=profile.service_periods.find(p=>p.id===period.id);return c.prepareServiceCorrection(pool,{user:user(hr),actor:hr,employeeId:employee.id,periodId:period.id,data:{start_date:'2026-02-01',end_date:null,employment_category:'temporary',is_teacher:false,is_intern:true,counts_for_service:true,work_pattern_id:null,appointment_reference:'Corrected appointment instrument',source_reference:'Test signed correction source',expected_hash:p.correction_hash,reason,...overrides}});}
 test('independent correction changes classification and dates with original facts retained, preserves balances',async()=>{const before=await configuration(),row=await prepare();assert.equal((await directory.employeeProfile(pool,employee.id)).service_periods[0].start_date,'2026-01-01');await assert.rejects(c.approveServiceCorrection(pool,{user:user(hr),actor:hr,id:row.id,reason}),e=>e.status===403);await c.approveServiceCorrection(pool,{user:user(certifier),actor:certifier,id:row.id,reason});const p=(await directory.employeeProfile(pool,employee.id)).service_periods[0];assert.equal(p.start_date,'2026-02-01');assert.equal(p.employment_category,'temporary');assert.equal(p.is_intern,true);assert.equal(row.before_snapshot.start_date,'2026-01-01');assert.match(await c.serviceCorrectionIssue(pool,employee.id,before.recorded_at),/Appointment facts/);await assert.rejects(w.publishConfiguration(pool,{user:user(certifier),actor:certifier,id:before.id,reason}),/foundations changed/);assert.equal((await pool.query('SELECT COUNT(*)::int n FROM hr_gov_ledger')).rows[0].n,0);await assert.rejects(c.discardServiceCorrection(pool,{user:user(hr),actor:hr,id:row.id,reason}),/approved history/);await assert.rejects(pool.query('UPDATE hr_employee_service_corrections SET reason=$2 WHERE id=$1',[row.id,'Changed history']),/immutable/);});
 test('correction conflicts and changed original facts reject before any mutation',async()=>{const row=await prepare();await pool.query("UPDATE hr_employee_service_periods SET appointment_reference='Later verified instrument' WHERE id=$1",[period.id]);await assert.rejects(c.approveServiceCorrection(pool,{user:user(certifier),actor:certifier,id:row.id,reason}),/changed/);assert.equal((await pool.query('SELECT status FROM hr_employee_service_corrections WHERE id=$1',[row.id])).rows[0].status,'draft');await assert.rejects(prepare({expected_hash:'a'.repeat(64)}),/changed/);await assert.rejects(prepare({start_date:'2026-03-01',end_date:'2026-02-01'}),/reversed/);});

 test('pending leave keeps its hold after independent appointment correction, then governed cancellation releases it',async()=>{
 const dept=(await pool.query("INSERT INTO hr_departments(name) VALUES('Test correction department') RETURNING *")).rows[0],div=(await pool.query("INSERT INTO hr_divisions(name,department_id) VALUES('Test correction division',$1) RETURNING *",[dept.id])).rows[0];
 await pool.query('UPDATE hr_employees SET department_id=$2,division_id=$3 WHERE id=$1',[employee.id,dept.id,div.id]);
 const pattern=(await pool.query("INSERT INTO hr_work_patterns(name,working_weekdays,hours_per_day) VALUES($1,ARRAY[1,2,3,4,5],7) RETURNING *",[`Test correction ${randomUUID()}`])).rows[0];
 await pool.query('UPDATE hr_employee_service_periods SET work_pattern_id=$2 WHERE id=$1',[period.id,pattern.id]);
 await l.addFoundationRecord(pool,{user:user(hr),actor:hr,kind:'pattern',data:{work_pattern_id:pattern.id,source_reference:'Test standard policy days',reason}});
 await l.addFoundationRecord(pool,{user:user(hr),actor:hr,employeeId:employee.id,kind:'basis',data:{effective_from:'2026-01-01',continuity_start:'2026-01-01',anniversary_method:'calendar',leap_day_method:'feb28',schedule_mode:'weekly',source_reference:'Test appointment service basis',reason}});
 await l.publishPolicy(pool,{user:user(hr),actor:hr,id:policy.id,reason});await l.createCalendar(pool,{user:user(hr),actor:hr,data:{label:'Test correction calendar',effective_from:'2026-01-01',effective_to:'2027-12-31',holidays:[],source_reference:'Test holidays',reason}});
 const opening=await l.prepareOpening(pool,{user:user(hr),actor:hr,employeeId:employee.id,data:{code:'recreation',amount:'20',policy_version_id:policy.id,period_start:'2026-01-01',period_end:'2026-12-31',as_of:'2026-10-01',source_reference:'Test employee credit',payroll_reference:'Test reconciled salary register',reason}});await l.certifyOpening(pool,{user:user(certifier),actor:certifier,id:opening.id,reason});
 const config=await w.prepareConfiguration(pool,{user:user(hr),actor:hr,employeeId:employee.id,data:{enabled_codes:['recreation'],medical_rule:'single_calendar_date_nonadjacent_scheduled_days',medical_history:[],source_reference:'Test reviewed medical rule',legacy_resolution_reference:'Test all historical leave reconciled',reason}});await w.publishConfiguration(pool,{user:user(certifier),actor:certifier,id:config.id,reason});
 const officers={};for(const level of w.routeLevels('recreation')){const by=level==='hr_verifier'?certifier:await account({hr_access:true,hr_leave_approve:true}),staff=(await pool.query("INSERT INTO hr_employees(display_name,reviewer_id,department_id,division_id) VALUES($1,$2,$3,$4) RETURNING *",[`Test ${level}`,by.id,dept.id,div.id])).rows[0];officers[level]=by;
 if(['division','department','chief_secretary'].includes(level))await pool.query("INSERT INTO hr_approval_assignments(level,department_id,division_id,approver_employee_id,effective_from,reason) VALUES($1,$2,$3,$4,'2026-01-01',$5)",[level,level==='chief_secretary'?null:dept.id,level==='division'?div.id:null,staff.id,reason]);else await w.assignConsentOffice(pool,{user:user(hr),actor:hr,data:{level,department_id:level==='relevant_secretary'?dept.id:null,approver_employee_id:staff.id,effective_from:'2026-01-01',source_reference:'Test signed office',reason}});}
 const request=await w.submitRequest(pool,{user:user(owner),actor:owner,employeeId:employee.id,data:{request_id:randomUUID(),code:'recreation',start_date:'2026-11-02',end_date:'2026-11-02',reason,medical_mode:'not_applicable'}}),before=await w.requestView(pool,user(hr),request.id),stage=before.stages[0];
 const correction=await prepare({start_date:'2026-01-01',employment_category:'contract',is_intern:false,work_pattern_id:pattern.id});await c.approveServiceCorrection(pool,{user:user(certifier),actor:certifier,id:correction.id,reason});
 const accountAfter=(await l.loadContext(pool,employee.id)).entitlements[0];assert.equal(accountAfter.balance,'20.000000');assert.equal(accountAfter.held,'1.000000');assert.match((await w.requestView(pool,user(hr),request.id)).stages[0].issue,/Appointment facts/);
 await assert.rejects(w.decideRequest(pool,{user:user(officers.division),actor:officers.division,id:request.id,data:{stage_id:stage.id,binding_id:stage.binding.id,event_key:randomUUID(),decision:'approved',note:reason}}),/Appointment facts/);
 assert.equal((await w.getRequest(pool,request.id)).status,'pending');await w.cancelRequest(pool,{user:user(hr),actor:hr,id:request.id,reason});assert.equal((await l.loadContext(pool,employee.id)).entitlements[0].held,'0');assert.equal((await l.loadContext(pool,employee.id)).entitlements[0].balance,'20.000000');
 });

 async function http(path,by,data){const session=await auth.createSession(by.id),token=auth.buildTokenPayload(by,session.tokenId,session.expiresAt);const r=await fetch(base+'/api/hr'+path,{method:data?'POST':'GET',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});return{status:r.status,body:await r.json()};}

 test('independent verified-shift activation reconciles historical 1.5-day use inside the ten-day Medical pool',async()=>{
 await l.publishPolicy(pool,{user:user(hr),actor:hr,id:policy.id,reason});await l.createCalendar(pool,{user:user(hr),actor:hr,data:{label:'Test medical shift calendar',effective_from:'2026-01-01',effective_to:'2027-12-31',holidays:[],source_reference:'Test shift holidays',reason}});
 await l.addFoundationRecord(pool,{user:user(hr),actor:hr,employeeId:employee.id,kind:'basis',data:{effective_from:'2026-01-01',continuity_start:'2026-01-01',anniversary_method:'calendar',leap_day_method:'feb28',schedule_mode:'roster',source_reference:'Test signed shift service basis',reason}});
 for(const [day,paid_hours,policy_days] of [['2026-02-02','12','1.5'],['2026-02-03','8','1'],['2026-11-02','12','1.5']])await l.addFoundationRecord(pool,{user:user(hr),actor:hr,employeeId:employee.id,kind:'roster',data:{day,paid_hours,policy_days,source_reference:'Test signed payroll shift conversion',reason}});
 const opening=await l.prepareOpening(pool,{user:user(hr),actor:hr,employeeId:employee.id,data:{code:'medical',amount:'8.5',policy_version_id:policy.id,period_start:'2026-01-01',period_end:'2026-12-31',as_of:'2026-10-01',source_reference:'Test remaining medical credit',payroll_reference:'Test medical Salary Unit register',reason}});await l.certifyOpening(pool,{user:user(certifier),actor:certifier,id:opening.id,reason});
 const data={enabled_codes:['medical'],medical_rule:'single_verified_shift_nonadjacent_scheduled_days',medical_history:[{start_date:'2026-02-02',end_date:'2026-02-02',uncertified:true}],source_reference:'Test approved single-shift definition',legacy_resolution_reference:'Test shift medical baseline reconciliation',reason};
 await assert.rejects(w.prepareConfiguration(pool,{user:user(hr),actor:hr,employeeId:employee.id,data:{...data,medical_rule:'single_calendar_date_nonadjacent_scheduled_days'}}),/certificate|one-day or verified-shift/);
 const config=await w.prepareConfiguration(pool,{user:user(hr),actor:hr,employeeId:employee.id,data});assert.equal(config.medical_history[0].charge,'1.500000');await w.publishConfiguration(pool,{user:user(certifier),actor:certifier,id:config.id,reason});
 const evaluation=await w.previewRequest(pool,user(owner),employee.id,{code:'medical',start_date:'2026-11-02',end_date:'2026-11-02',reason,medical_mode:'exemption'});assert.equal(evaluation.charge,'1.500000');assert.equal(evaluation.eligible_for_preview,true);assert.equal(evaluation.medical_exemptions_used,1);const injected=await http(`/government/employees/${employee.id}/evaluate`,hr,{code:'medical',start_date:'2026-11-02',end_date:'2026-11-02',certificate_available:false,verified_single_shift_exemption:true});assert.equal(injected.status,200);assert.match(injected.body.issues.join(),/certificate/);assert.equal((await l.loadContext(pool,employee.id)).entitlements[0].balance,'8.500000');
 });
 test('HTTP controls restrict personnel corrections and expose recoverable preparation states',async()=>{
 const row=await configuration(),profile=await directory.employeeProfile(pool,employee.id),data={start_date:'2026-02-01',end_date:null,employment_category:'temporary',is_teacher:false,is_intern:true,counts_for_service:true,work_pattern_id:null,source_reference:'Test signed appointment instrument',expected_hash:profile.service_periods[0].correction_hash,reason};
 assert.equal((await http(`/directory/service-corrections/employees/${employee.id}`,owner)).status,403);
 assert.equal((await http(`/directory/service-corrections/employees/${employee.id}/periods/${period.id}`,owner,data)).status,403);
 const made=await http(`/directory/service-corrections/employees/${employee.id}/periods/${period.id}`,hr,data);assert.equal(made.status,201);
 assert.equal((await http(`/directory/service-corrections/${made.body.id}/approve`,hr,{reason})).status,403);
 assert.equal((await http(`/directory/service-corrections/${made.body.id}/approve`,certifier,{reason})).status,200);
 assert.equal((await http(`/government/drafts/configuration/${row.id}/lifecycle`,owner,{reason,action:'discard',expected_revision:0})).status,403);
 assert.equal((await http(`/government/drafts/configuration/${row.id}/lifecycle`,hr,{reason,action:'discard',expected_revision:0})).status,200);
 const list=await http('/government/workflow/administration',hr);assert.equal(list.status,200);assert.equal(list.body.configs.find(c=>c.id===row.id).discarded,true);
 assert.equal((await http(`/government/workflow/configurations/${row.id}/publish`,certifier,{reason})).status,409);
 });
 test('concurrent approval and discard serialize so deleted preparation cannot become published',async()=>{
 const row=await configuration(),results=await Promise.allSettled([lifecycle('configuration',row.id,'discard',0),w.publishConfiguration(pool,{user:user(certifier),actor:certifier,id:row.id,reason})]);
 assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const final=(await pool.query('SELECT status FROM hr_gov_workflow_configs WHERE id=$1',[row.id])).rows[0],state=await d.draftState(pool,'configuration',row.id);
 assert.ok(final.status==='published'&&!state.discarded||final.status==='draft'&&state.discarded);
 });
 test('correction discard/restore keeps independently reviewable facts',async()=>{const row=await prepare();await c.discardServiceCorrection(pool,{user:user(hr),actor:hr,id:row.id,reason});await assert.rejects(c.approveServiceCorrection(pool,{user:user(certifier),actor:certifier,id:row.id,reason}),/active correction draft/);await c.discardServiceCorrection(pool,{user:user(hr),actor:hr,id:row.id,reason,action:'restore'});await c.approveServiceCorrection(pool,{user:user(certifier),actor:certifier,id:row.id,reason});});
});
