import governmentLeaveWorkflowRouter from './governmentLeaveWorkflow.js';
import express from 'express';
import {pool} from '../db.js';
import {body,param,query,handleValidation} from '../middleware/validation.js';
import {requirePermission} from '../services/authService.js';
import {PERMISSIONS} from '../config.js';
import {withTransaction} from '../lib/transaction.js';
import {CODES,COMMON_CODES,DEFAULT_RULES,SOURCE,dayNumber,serviceFacts} from '../lib/governmentLeaveRules.js';
import * as service from '../services/governmentLeave.js';
const router=express.Router(),central=requirePermission(PERMISSIONS.HR_ADMIN),access=requirePermission(PERMISSIONS.HR_ACCESS,PERMISSIONS.HR_ADMIN,PERMISSIONS.HR_STAFF_MANAGE,PERMISSIONS.HR_BALANCE_MANAGE,PERMISSIONS.HR_LEAVE_APPROVE);
router.use((_req,res,next)=>{res.set('Cache-Control','no-store');next();});
router.use('/workflow',governmentLeaveWorkflowRouter);
const reason=body('reason').isString().trim().isLength({min:10,max:1000}),reference=body('source_reference').isString().trim().isLength({min:5,max:500}),id=param('id').isUUID();
const date=name=>body(name).isString().custom(value=>{dayNumber(value);return true;});
const actor=req=>({id:req.user.id,email:req.user.email,ip:req.ip});
const data=req=>({user:req.user,actor:actor(req),data:req.body,employeeId:req.params.id});
router.get('/configuration',central,async(_req,res)=>{
 const [policies,calendars,patterns]=await Promise.all([pool.query("SELECT *,to_char(effective_from,'YYYY-MM-DD') AS effective_from,to_char(effective_to,'YYYY-MM-DD') AS effective_to FROM hr_gov_policy_versions ORDER BY recorded_at DESC LIMIT 100"),pool.query("SELECT *,to_char(effective_from,'YYYY-MM-DD') AS effective_from,to_char(effective_to,'YYYY-MM-DD') AS effective_to FROM hr_gov_calendars ORDER BY recorded_at DESC LIMIT 100"),pool.query('SELECT p.*,a.id AS approval_id,a.source_reference FROM hr_work_patterns p LEFT JOIN hr_gov_pattern_approvals a ON a.work_pattern_id=p.id ORDER BY p.name LIMIT 100')]);
 res.json({codes:CODES,defaults:DEFAULT_RULES,source_reference:SOURCE,policies:policies.rows,calendars:calendars.rows,patterns:patterns.rows,legacy_submission_enabled:false,submission_activation:'independent_per_employee'});
});
router.post('/policies',central,[reason,reference,body('label').isString().trim().isLength({min:3,max:120}),date('effective_from'),date('effective_to'),body('rules').optional().isObject()],async(req,res)=>{if(!handleValidation(req,res))return;res.status(201).json(await service.createPolicy(pool,data(req)));});
router.post('/policies/:id/publish',central,[id,reason],async(req,res)=>{if(!handleValidation(req,res))return;res.json(await service.publishPolicy(pool,{...data(req),id:req.params.id,reason:req.body.reason}));});
router.post('/calendars',central,[reason,reference,body('label').isString().trim().isLength({min:3,max:120}),date('effective_from'),date('effective_to'),body('supersedes_id').optional({nullable:true}).isUUID(),body('holidays').isArray({max:100}),body('holidays.*.date').custom(value=>{dayNumber(value);return true;}),body('holidays.*.name').isString().trim().isLength({min:1,max:120})],async(req,res)=>{if(!handleValidation(req,res))return;res.status(201).json(await service.createCalendar(pool,data(req)));});
router.post('/patterns/approve',central,[reason,reference,body('work_pattern_id').isUUID(),body('conversion_confirmed').equals('true')],async(req,res)=>{if(!handleValidation(req,res))return;res.status(201).json(await service.addFoundationRecord(pool,{...data(req),kind:'pattern'}));});
router.get('/employees/:id',access,[id],async(req,res)=>{if(!handleValidation(req,res))return;await service.readable(pool,req.user,req.params.id);const context=await service.loadContext(pool,req.params.id);const facts=serviceFacts(context,new Date(Date.now()+12*3600000).toISOString().slice(0,10));res.json({service_summary:{...facts,basis:facts.basis?{id:facts.basis.id}:null,milestone:undefined,ordinary_recreation_eligible:facts.milestone?.(3)||null,temporary_recreation_eligible:facts.milestone?.(12)||null},employee:context.employee,bases:context.bases.map(({reason:_reason,...row})=>row),periods:context.periods.map(({reason:_reason,...row})=>row),exclusions:context.exclusions.map(({reason:_reason,source_reference:_source,...row})=>row),rosters:context.rosters.map(({reason:_reason,...row})=>row),entitlements:context.entitlements});});
router.post('/employees/:id/basis',central,[id,reason,reference,date('effective_from'),date('continuity_start'),body('anniversary_method').isIn(['calendar','pause_exclusions']),body('leap_day_method').isIn(['feb28','mar1']),body('schedule_mode').isIn(['weekly','roster'])],async(req,res)=>{if(!handleValidation(req,res))return;res.status(201).json(await service.addFoundationRecord(pool,{...data(req),kind:'basis'}));});
router.post('/employees/:id/exclusion',central,[id,reason,reference,date('start_date'),date('end_date'),body('kind').isIn(['lwop','other_excluded','continuity_break'])],async(req,res)=>{if(!handleValidation(req,res))return;res.status(201).json(await service.addFoundationRecord(pool,{...data(req),kind:'exclusion'}));});
router.post('/employees/:id/withdraw-exclusion',central,[id,reason,reference,body('exclusion_id').isUUID()],async(req,res)=>{if(!handleValidation(req,res))return;res.status(201).json(await service.addFoundationRecord(pool,{...data(req),kind:'withdraw-exclusion'}));});
router.post('/employees/:id/roster',central,[id,reason,reference,date('day'),body('paid_hours').isFloat({min:0,max:24}),body('policy_days').isDecimal({decimal_digits:'0,6'}),body('supersedes_id').optional({nullable:true}).isUUID()],async(req,res)=>{if(!handleValidation(req,res))return;res.status(201).json(await service.addFoundationRecord(pool,{...data(req),kind:'roster'}));});
router.post('/employees/:id/evaluate',access,[id,date('start_date'),date('end_date'),body('code').isIn(CODES),body('certificate_available').optional().isBoolean(),body('justification_available').optional().isBoolean()],async(req,res)=>{
 if(!handleValidation(req,res))return;await service.readable(pool,req.user,req.params.id);
 const today=new Date(Date.now()+12*3600000).toISOString().slice(0,10);
 res.json(await withTransaction(pool,async client=>{await client.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');return service.evaluate(client,req.params.id,{code:req.body.code,start_date:req.body.start_date,end_date:req.body.end_date,notice_date:today,certificate_available:req.body.certificate_available===true,justification_available:req.body.justification_available===true});}));
});
router.post('/employees/:id/openings',central,[id,reason,reference,body('payroll_reference').isString().trim().isLength({min:5,max:500}),body('policy_version_id').isUUID(),body('code').isIn(COMMON_CODES),date('period_start'),date('period_end'),date('as_of'),body('amount').isDecimal({decimal_digits:'0,6'})],async(req,res)=>{if(!handleValidation(req,res))return;res.status(201).json(await service.prepareOpening(pool,data(req)));});
router.get('/openings',central,[query('page').optional().isInt({min:1,max:100000}),query('employee_id').optional().isUUID()],async(req,res)=>{
 if(!handleValidation(req,res))return;const page=Number(req.query.page)||1,employee=req.query.employee_id||null;
 const {rows}=await pool.query("SELECT o.*,e.display_name,to_char(o.period_start,'YYYY-MM-DD') AS period_start,to_char(o.period_end,'YYYY-MM-DD') AS period_end,to_char(o.as_of,'YYYY-MM-DD') AS as_of FROM hr_gov_openings o JOIN hr_employees e ON e.id=o.employee_id WHERE ($1::uuid IS NULL OR o.employee_id=$1) ORDER BY o.recorded_at DESC,o.id LIMIT 50 OFFSET $2",[employee,(page-1)*50]);const {rows:[count]}=await pool.query('SELECT count(*)::int AS total FROM hr_gov_openings WHERE ($1::uuid IS NULL OR employee_id=$1)',[employee]);res.json({openings:rows,total:count.total,page,page_size:50});
});
router.post('/openings/:id/certify',central,[id,reason],async(req,res)=>{if(!handleValidation(req,res))return;res.json(await service.certifyOpening(pool,{...data(req),id:req.params.id,reason:req.body.reason}));});
router.get('/employees/:id/ledger',access,[id,query('page').optional().isInt({min:1,max:100000})],async(req,res)=>{
 if(!handleValidation(req,res))return;await service.ledgerReadable(pool,req.user,req.params.id);const page=Number(req.query.page)||1;
 const {rows}=await pool.query("SELECT l.*,e.code,to_char(l.effective_date,'YYYY-MM-DD') AS effective_date FROM hr_gov_ledger l JOIN hr_gov_entitlements e ON e.id=l.entitlement_id WHERE e.employee_id=$1 ORDER BY l.recorded_at DESC,l.id LIMIT 50 OFFSET $2",[req.params.id,(page-1)*50]);const {rows:[count]}=await pool.query('SELECT count(*)::int AS total FROM hr_gov_ledger l JOIN hr_gov_entitlements e ON e.id=l.entitlement_id WHERE e.employee_id=$1',[req.params.id]);res.json({movements:rows,total:count.total,page,page_size:50});
});
router.post('/employees/:id/corrections',central,[id,reason,reference,body('entitlement_id').isUUID(),body('event_key').isUUID(),body('amount').isDecimal({decimal_digits:'0,6'}),date('effective_date')],async(req,res)=>{if(!handleValidation(req,res))return;res.status(201).json(await service.correctLedger(pool,data(req)));});
router.post('/employees/:id/movements/:movementId/reverse',central,[id,param('movementId').isUUID(),reason,reference,date('effective_date')],async(req,res)=>{if(!handleValidation(req,res))return;res.json(await service.reverseMovement(pool,{...data(req),id:req.params.movementId}));});
export default router;
