import {describe,test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {writeFile} from 'node:fs/promises';
import {connectTestDatabase,resetLeaveTables,skipWithoutDatabase} from '../test-support/database.js';
import {DEFAULT_RULES} from '../lib/governmentLeaveRules.js';

describe('government event cases, financial commitments and amendments',{skip:skipWithoutDatabase},()=>{
 let pool,w,l,jobs,c,auth,server,base,hr,certifier,owner,employee,department,division,officers,policy;
 const reason='Synthetic verified authority and evidence for local tests.';
 const user=row=>({...row,permissions:row.permissions});
 before(async()=>{
   pool=await connectTestDatabase();w=await import('../services/governmentLeaveWorkflow.js');l=await import('../services/governmentLeave.js');jobs=await import('../services/governmentLeaveJobs.js');c=await import('../services/governmentLeaveCases.js');auth=await import('../services/authService.js');
   const express=(await import('express')).default,errors=await import('../middleware/errors.js');errors.enableAsyncErrors();const app=express();app.use(express.json());app.use('/api/hr',(await import('./hr.js')).default);app.use(errors.notFoundHandler);app.use(errors.errorHandler);server=await new Promise(resolve=>{const running=app.listen(0,'127.0.0.1',()=>resolve(running));});base=`http://127.0.0.1:${server.address().port}`;
 });
 after(async()=>{if(server)await new Promise(resolve=>server.close(resolve));await pool?.end();});
 async function account(permissions,type='staff'){return(await pool.query("INSERT INTO reviewers(email,display_name,role,password_hash,permissions,account_type) VALUES($1,'Synthetic workflow actor','user','x',$2,$3) RETURNING *",[`${randomUUID()}@example.test`,permissions,type])).rows[0];}
 async function opening(code,amount){const o=await l.prepareOpening(pool,{user:user(hr),actor:hr,employeeId:employee.id,data:{code,amount,policy_version_id:policy.id,period_start:'2026-01-01',period_end:'2026-12-31',as_of:'2026-10-01',source_reference:'Synthetic reviewed HR register',payroll_reference:'Synthetic Salary Unit reconciliation',reason}});await l.certifyOpening(pool,{user:user(certifier),actor:certifier,id:o.id,reason});}
 async function configure(codes=['recreation','medical','special'],history=[]){const row=await w.prepareConfiguration(pool,{user:user(hr),actor:hr,employeeId:employee.id,data:{enabled_codes:codes,medical_rule:'single_calendar_date_nonadjacent_scheduled_days',medical_history:history,source_reference:'Synthetic medical rule and cutover history approval',legacy_resolution_reference:'Synthetic legacy leave reconciled register',reason}});await w.publishConfiguration(pool,{user:user(certifier),actor:certifier,id:row.id,reason});return row;}
 const application=(code='recreation',start='2026-11-02',end=start)=>({request_id:randomUUID(),code,start_date:start,end_date:end,reason,medical_mode:code==='medical'?'exemption':'not_applicable'});
 async function submit(data=application(),documents=[]){return w.submitRequest(pool,{user:user(owner),actor:owner,employeeId:employee.id,data,documents});}
 async function decide(id,changes={},actor=null){const view=await w.requestView(pool,user(hr),id),stage=view.stages[view.stage_index];const by=actor||officers[stage.level].account;return w.decideRequest(pool,{user:user(by),actor:by,id,data:{stage_id:stage.id,binding_id:stage.binding?.id||randomUUID(),event_key:randomUUID(),decision:'approved',note:reason,discretion_confirmed:true,evidence_reviewed:true,certificate_reviewed:true,justification_accepted:true,source_reference:'Synthetic registered-practitioner and HR verified source',covers_start:'2026-01-01',covers_end:'2026-12-31',...changes}});}
 async function grant(id){let result;for(let i=0;i<7;i++){const r=await w.getRequest(pool,id);if(r.status!=='pending')return r;result=await decide(id);}return result;}
 async function call(path,data,by=owner,method=data?'POST':'GET'){const session=await auth.createSession(by.id),token=auth.buildTokenPayload(by,session.tokenId,session.expiresAt);const response=await fetch(base+'/api/hr/government/workflow'+path,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});return {status:response.status,body:response.headers.get('content-type')?.includes('json')?await response.json():await response.arrayBuffer(),cache:response.headers.get('cache-control')};}
 beforeEach(async()=>{
  await resetLeaveTables(pool);await pool.query('TRUNCATE hr_gov_policy_versions,hr_gov_calendars,hr_gov_pattern_approvals CASCADE');
  hr=await account({hr_admin:true,hr_access:true,hr_report_read:true,hr_evidence_read:true});certifier=await account({hr_admin:true,hr_access:true});owner=await account({hr_access:true,hr_leave_apply:true},'employee');
  department=(await pool.query("INSERT INTO hr_departments(name) VALUES('Synthetic Government Workflow') RETURNING *")).rows[0];division=(await pool.query("INSERT INTO hr_divisions(name,department_id) VALUES('Synthetic Division',$1) RETURNING *",[department.id])).rows[0];
  employee=(await pool.query("INSERT INTO hr_employees(display_name,reviewer_id,department_id,division_id,department_code,division_code,leave_policy_regime) VALUES('Synthetic Government Applicant',$1,$2,$3,'Synthetic Government Workflow','Synthetic Division','government') RETURNING *",[owner.id,department.id,division.id])).rows[0];
  const pattern=(await pool.query("INSERT INTO hr_work_patterns(name,working_weekdays,hours_per_day) VALUES($1,ARRAY[1,2,3,4,5],7) RETURNING *",[`Synthetic Workflow Pattern ${randomUUID()}`])).rows[0];
  await pool.query("INSERT INTO hr_employee_service_periods(employee_id,start_date,employment_category,counts_for_service,work_pattern_id,reason) VALUES($1,'2026-01-01','permanent',TRUE,$2,$3)",[employee.id,pattern.id,reason]);
  await l.addFoundationRecord(pool,{user:user(hr),actor:hr,kind:'pattern',data:{work_pattern_id:pattern.id,source_reference:'Synthetic one policy day per standard scheduled day',reason}});
  await l.addFoundationRecord(pool,{user:user(hr),actor:hr,employeeId:employee.id,kind:'basis',data:{effective_from:'2026-01-01',continuity_start:'2026-01-01',anniversary_method:'calendar',leap_day_method:'feb28',schedule_mode:'weekly',source_reference:'Synthetic signed continuous service',reason}});
  policy=await l.createPolicy(pool,{user:user(hr),actor:hr,data:{label:'Synthetic common workflow policy',effective_from:'2026-01-01',effective_to:'2027-12-31',rules:DEFAULT_RULES,source_reference:'Synthetic typed policy authority',reason}});await l.publishPolicy(pool,{user:user(hr),actor:hr,id:policy.id,reason});
  await l.createCalendar(pool,{user:user(hr),actor:hr,data:{label:'Synthetic workflow calendar',effective_from:'2026-01-01',effective_to:'2027-12-31',holidays:[],source_reference:'Synthetic holiday Gazette reference',reason}});
  for(const [code,amount] of [['recreation','20'],['medical','10'],['special','3']])await opening(code,amount);
  officers={};
  for(const level of w.routeLevels('recreation')){
    const accountRow=level==='hr_verifier'?certifier:await account({hr_access:true,hr_leave_approve:true});
    const staff=(await pool.query("INSERT INTO hr_employees(display_name,reviewer_id,department_id,division_id) VALUES($1,$2,$3,$4) RETURNING *",[`Synthetic ${level}`,accountRow.id,department.id,division.id])).rows[0];officers[level]={account:accountRow,employee:staff};
    if(['division','department','chief_secretary'].includes(level))await pool.query("INSERT INTO hr_approval_assignments(level,department_id,division_id,approver_employee_id,effective_from,reason) VALUES($1,$2,$3,$4,'2026-01-01',$5)",[level,level==='chief_secretary'?null:department.id,level==='division'?division.id:null,staff.id,reason]);
    else await w.assignConsentOffice(pool,{user:user(hr),actor:hr,data:{level,department_id:level==='relevant_secretary'?department.id:null,approver_employee_id:staff.id,effective_from:'2026-01-01',source_reference:'Synthetic statutory office appointment',reason}});
  }
  await configure();
 });
 const doc={file_name:'synthetic-case.pdf',content_type:'application/pdf',byte_size:12,sha256:'synthetic-only-evidence',file_data:Buffer.from('%PDF-1.7\ntest')};
 const event=(code='official',start='2026-11-02',end=start)=>({request_id:randomUUID(),code,start_date:start,end_date:end,reason,event_reference:`Synthetic personnel event ${randomUUID()}`});
 async function caseSubmit(data=event(),by=owner,documents=[doc]){return c.submitCase(pool,{user:user(by),actor:by,employeeId:employee.id,data,documents});}
 const generic={eligibility_confirmed:true};
 const official={...generic,allowance_amount:'250.00',allowance_reference:'Synthetic signed Minister-rate allowance',outside_republic:true,official_documents_verified:true,gazette_reference:'Synthetic signed official travel Gazette schedule'};
 const parental={...generic,parenthood_verified:true,sex_eligibility:'female',pregnancy_number:1,certificate_complete:true,fitness_certified:true,expected_birth_date:'2026-12-13',late_notice_authority_reference:'Synthetic Chief Secretary notice discretion'};
 async function determine(id,facts,rate='100',pay=null,by=hr){const r=await w.getRequest(pool,id);return c.prepareDetermination(pool,{user:user(by),actor:by,id,data:{reason,source_reference:'Synthetic signed case policy authority',evidence_reference:'Synthetic complete retained evidence verification',facts,pay_segments:pay||[{start_date:r.start_date,end_date:r.end_date,salary_percent:rate}]}});}
 async function oldService(start='2010-01-01',category='permanent'){
  await pool.query('TRUNCATE hr_gov_service_bases CASCADE');await pool.query('UPDATE hr_employee_service_periods SET start_date=$2,employment_category=$3 WHERE employee_id=$1',[employee.id,start,category]);
  await l.addFoundationRecord(pool,{user:user(hr),actor:hr,employeeId:employee.id,kind:'basis',data:{effective_from:start,continuity_start:start,anniversary_method:'pause_exclusions',leap_day_method:'feb28',schedule_mode:'weekly',source_reference:'Synthetic verified long continuity register',reason}});
 }
 const financial=(amount='20',action='encashment')=>({...generic,requested_units:amount,action,duration_unit:'working_days',duration_unit_reference:'Synthetic signed benefit working-day determination',prior_consumed:'0',prior_history_reference:'Synthetic certified pre-portal usage and payout history',prior_history_reconciled:true,transition_resolution_reference:'Synthetic signed LSL to furlough prior-payment treatment',salary_valuation_reference:'Synthetic Salary Unit signed valuation',payable_amount:'1200.00',currency:'AUD'});
 test('event application has no fake balance; evidence and independent determination are mandatory; final PDF is immutable',async()=>{
  const data=event('official','2026-11-02','2026-11-06'),r=await caseSubmit(data);assert.equal((await caseSubmit(data)).id,r.id);const before=(await l.loadContext(pool,employee.id)).entitlements.map(e=>e.balance);
  await decide(r.id);await decide(r.id);await assert.rejects(decide(r.id),/Prepare a sourced/);
  await determine(r.id,official,'100',null,certifier);await assert.rejects(decide(r.id),/different central HR/);await determine(r.id,official);await grant(r.id);
  const saved=await w.getRequest(pool,r.id);assert.equal(saved.charge,'0.000000');assert.equal(saved.reservation_id,null);assert.deepEqual((await l.loadContext(pool,employee.id)).entitlements.map(e=>e.balance),before);assert.equal(saved.grant_snapshot.case_determination.pay_segments[0].salary_percent,'100.000000');assert.ok(saved.final_pdf.subarray(0,5).toString()==='%PDF-');
  await writeFile('/tmp/government-leave-package-4-approved.pdf',saved.final_pdf);await assert.rejects(pool.query('UPDATE hr_gov_case_determinations SET reason=$2 WHERE request_id=$1',[r.id,'attempt rewrite']),/immutable/);await assert.rejects(c.prepareDetermination(pool,{user:user(hr),actor:hr,id:r.id,data:{}}),/pending/);
 });
 test('parental leave uses calendar weeks and Chief Secretary late notice discretion, preserves salary segments and return task',async()=>{
  const r=await caseSubmit(event('maternity','2026-11-01','2027-01-23'));
  await assert.rejects(determine(r.id,{...parental,late_notice_authority_reference:null}),/late notice/);await determine(r.id,parental);
  for(let i=0;i<3;i++)await decide(r.id);await assert.rejects(decide(r.id,{discretion_confirmed:false}),/explicitly confirm/);await decide(r.id);
  const view=await w.requestView(pool,user(owner),r.id);assert.equal(view.tasks[0].kind,'return_confirmation');assert.equal(view.tasks[0].due_date,'2026-12-26');assert.equal(view.determination.pay_segments[0].salary_percent,'100.000000');
  const invalid=await caseSubmit(event('paternity','2027-02-01','2027-02-10'));await assert.rejects(determine(invalid.id,{...generic,sex_eligibility:'male',parenthood_verified:true,certificate_complete:true,event_kind:'birth',event_date:'2027-02-01',late_notice_authority_reference:'Synthetic notice discretion'}),/calendar weeks/);
 });
 test('mid-leave six-month service requires split pay; fifth-pregnancy conflict requires a signed resolution',async()=>{
  await oldService('2026-06-01');const r=await caseSubmit(event('maternity','2026-11-01','2027-01-23')),facts={...parental,pregnancy_number:5};
  await assert.rejects(determine(r.id,facts),/conflict resolution/);const resolved={...facts,conflict_resolution_reference:'Synthetic signed half/full salary reconciliation'};
  await assert.rejects(determine(r.id,resolved),/Split the pay segment/);await assert.rejects(determine(r.id,resolved,'100',[{start_date:'2026-11-01',end_date:'2026-11-30',salary_percent:'100'},{start_date:'2026-12-01',end_date:'2027-01-23',salary_percent:'100'}]),/requires 0/);
  await determine(r.id,resolved,'100',[{start_date:'2026-11-01',end_date:'2026-11-30',salary_percent:'0'},{start_date:'2026-12-01',end_date:'2027-01-23',salary_percent:'100'}]);await grant(r.id);
  assert.equal((await w.getRequest(pool,r.id)).grant_snapshot.case_determination.pay_segments.length,2);
 });
 test('temporary parental and non-permanent LWOP hard-block, while temporary official travel remains available',async()=>{
  await pool.query("UPDATE hr_employee_service_periods SET employment_category='temporary',is_intern=TRUE WHERE employee_id=$1",[employee.id]);await assert.rejects(caseSubmit(event('maternity','2026-11-01','2027-01-23')),/Temporary parental/);await assert.rejects(caseSubmit(event('lwop')),/permanent/);const r=await caseSubmit();await determine(r.id,official);await grant(r.id);
 });
 test('adoption starts at the adoption date, validates under-twelve-month age and excludes spouse/step-child',async()=>{
  const r=await caseSubmit(event('adoption','2026-09-01','2026-09-28'));const facts={...generic,sex_eligibility:'female',parenthood_verified:true,adoption_order_verified:true,event_kind:'adoption',event_date:'2026-09-01',child_birth_date:'2026-01-01',spouse_or_stepchild:false};
  await assert.rejects(determine(r.id,{...facts,child_birth_date:'2025-09-01'}),/under twelve/);await assert.rejects(determine(r.id,{...facts,spouse_or_stepchild:true}),/excludes/);await assert.rejects(determine(r.id,{...facts,event_date:'2026-09-02'}),/start at/);await determine(r.id,facts);await grant(r.id);
 });
 test('LWOP pauses qualifying service only after final grant and retains Secretary consent; unpaid witness is distinct',async()=>{
  const r=await caseSubmit(event('lwop','2026-11-02','2026-11-06'),owner,[]),facts={...generic,genuine_purpose:true,no_other_leave_accessible:true};await assert.rejects(determine(r.id,facts),/0%/);await determine(r.id,facts,'0');
  for(let i=0;i<4;i++)await decide(r.id);assert.equal((await l.loadContext(pool,employee.id)).exclusions.length,0);await decide(r.id);const context=await l.loadContext(pool,employee.id);assert.equal(context.exclusions[0].kind,'lwop');assert.equal(context.exclusions[0].end_date,'2026-11-06');
  const wCase=await caseSubmit(event('witness_other','2026-11-09','2026-11-10'));const witness={...generic,court_evidence_verified:true,hod_notification_reference:'Synthetic prompt HOD court notification'};await assert.rejects(determine(wCase.id,witness,'0'),/conflict resolution/);await determine(wCase.id,{...witness,conflict_resolution_reference:'Synthetic signed witness authority inconsistency resolution',grant_authority_reference:'Synthetic discretionary witness grant authority'},'0');await grant(wCase.id);assert.equal((await l.loadContext(pool,employee.id)).exclusions.length,1);
 });
 test('extended medical stays outside ordinary ten-day balance and Minister tier requires completed three-month grant',async()=>{
  const facts={...generic,certificate_complete:true,ordinary_medical_reconciled:true,certificate_reference:'Synthetic registered practitioner extension coverage'};
  const first=await caseSubmit(event('extended_medical','2026-11-01','2027-02-01'));await assert.rejects(determine(first.id,facts),/calendar-month limit/);await w.cancelRequest(pool,{user:user(owner),actor:owner,id:first.id,reason});
  const r=await caseSubmit(event('extended_medical','2026-11-01','2027-01-31'));await determine(r.id,facts);await grant(r.id);assert.equal((await l.loadContext(pool,employee.id)).entitlements.find(e=>e.code==='medical').balance,'10.000000');
  const ministerAccount=await account({hr_access:true,hr_leave_approve:true}),ministerEmployee=(await pool.query("INSERT INTO hr_employees(display_name,reviewer_id,department_id,division_id) VALUES('Synthetic Minister',$1,$2,$3) RETURNING *",[ministerAccount.id,department.id,division.id])).rows[0];officers.minister={account:ministerAccount,employee:ministerEmployee};await w.assignConsentOffice(pool,{user:user(hr),actor:hr,data:{level:'minister',department_id:department.id,approver_employee_id:ministerEmployee.id,effective_from:'2026-01-01',source_reference:'Synthetic statutory Minister appointment',reason}});
  const extended=await caseSubmit({...event('extended_medical_minister','2027-02-01','2027-02-28'),related_request_id:r.id});await determine(extended.id,{...facts,prior_extended_request_id:r.id},'50');const view=await w.requestView(pool,user(hr),extended.id);assert.equal(view.stages.at(-2).level,'minister');await grant(extended.id);assert.equal((await w.getRequest(pool,extended.id)).status,'approved');
 });
 test('benefit tiers use credited service, commit taking/encashment once, preserve prior payouts and reject duplicate use',async()=>{
  await oldService();const r=await caseSubmit({...event('furlough','2026-10-07'),assisted_reference:'Synthetic employee signed financial request'},hr);await determine(r.id,financial('100'));await grant(r.id);const snap=(await w.getRequest(pool,r.id)).grant_snapshot.case_determination;assert.equal(snap.benefit.gross,'114.000000');
  const second=await caseSubmit({...event('furlough','2026-10-07'),assisted_reference:'Synthetic distinct financial event'},hr);await assert.rejects(determine(second.id,financial('20')),/committed and pending/);await assert.rejects(determine(second.id,{...financial('10'),prior_consumed:'1'}),/baseline changed/);await determine(second.id,financial('10'));await grant(second.id);assert.equal((await pool.query('SELECT sum(units)::text AS n FROM hr_gov_benefit_commitments')).rows[0].n,'110.000000');
  await assert.rejects(caseSubmit({...event('long_service','2026-10-07'),assisted_reference:'Synthetic employee request'},hr).then(x=>determine(x.id,financial('20'))),/service.*tier/);
 });
 test('long service covers contract employees at five/eight tiers and does not blanket-forfeit misconduct benefits',async()=>{
  await oldService('2020-01-01','contract');const r=await caseSubmit({...event('long_service','2026-10-07'),assisted_reference:'Synthetic employee separation request'},hr);await determine(r.id,financial('20','resignation'));await grant(r.id);assert.equal((await w.getRequest(pool,r.id)).grant_snapshot.case_determination.benefit.gross,'20.000000');
  const other=await caseSubmit({...event('long_service','2026-10-07'),assisted_reference:'Synthetic encashment request'},hr);await assert.rejects(determine(other.id,financial('1','misconduct')),/separation benefit/);
 });
 test('recreation encashment holds certified credit against ordinary leave and commits only at final grant',async()=>{
  const account=(await l.loadContext(pool,employee.id)).entitlements.find(e=>e.code==='recreation');const r=await caseSubmit({...event('recreation_encashment','2026-10-07'),assisted_reference:'Synthetic exceptional cash-out request'},hr),facts={...financial('19'),entitlement_id:account.id,chief_direction_reference:'Synthetic Chief Secretary exceptional cash-out direction'};
  await determine(r.id,facts);assert.equal((await l.loadContext(pool,employee.id)).entitlements.find(e=>e.code==='recreation').held,'19.000000');await assert.rejects(submit(application('recreation','2026-11-02','2026-11-03')),/exceeds/);await grant(r.id);assert.equal((await l.loadContext(pool,employee.id)).entitlements.find(e=>e.code==='recreation').balance,'1.000000');
 });
 test('controlled common amendment refunds only released dated units, retains original PDF and removes amended absence dates',async()=>{
  const r=await submit(application('recreation','2026-11-02','2026-11-04'));await grant(r.id);const original=await w.getRequest(pool,r.id),bytes=Buffer.from(original.final_pdf);
  const amendment=await caseSubmit({...event('amendment',original.start_date,'2026-11-02'),related_request_id:r.id,assisted_reference:'Synthetic signed early-return request'},hr,[]);const facts={...generic,original_request_id:r.id,action:'shorten_grant',salary_correction_reference:'Synthetic Salary Unit correction instruction'};await determine(amendment.id,facts);assert.equal((await l.loadContext(pool,employee.id)).entitlements.find(e=>e.code==='recreation').balance,'17.000000');await grant(amendment.id);assert.equal((await l.loadContext(pool,employee.id)).entitlements.find(e=>e.code==='recreation').balance,'19.000000');assert.deepEqual((await w.getRequest(pool,r.id)).final_pdf,bytes);assert.equal((await w.getRequest(pool,r.id)).status,'approved');
  const calendar=await call('/calendar?from=2026-11-01&to=2026-11-10',null,owner);assert.equal(calendar.body.entries.find(e=>e.id===r.id).end_date,'2026-11-02');assert.ok(await submit(application('recreation','2026-11-03')));await assert.rejects(caseSubmit({...event('amendment',original.start_date,original.end_date),related_request_id:r.id,assisted_reference:'Synthetic duplicate amendment'},hr,[]),/amendment is already/);
 });
 test('official non-completion creates five-working-day recovery, financial follow-up requires actual receipt and idempotent events',async()=>{
  const r=await caseSubmit();await determine(r.id,official);await grant(r.id);const view=await w.requestView(pool,user(hr),r.id),task=view.tasks[0],data={event_key:randomUUID(),action:'noncompletion',reference:'Synthetic actual trip cancellation',reason,facts:{paid_amount:'250.00',payment_reference:'Synthetic actual allowance payment reference',trigger_date:'2026-10-07',recovery_amount:'125.50',recovery_determination_reference:'Synthetic signed pro-rata allowance recovery'}};
  await c.recordTaskEvent(pool,{user:user(hr),actor:hr,id:r.id,taskId:task.id,data});await c.recordTaskEvent(pool,{user:user(hr),actor:hr,id:r.id,taskId:task.id,data});const after=await w.requestView(pool,user(hr),r.id),recovery=after.tasks.find(t=>t.kind==='allowance_recovery');assert.equal(recovery.due_date,'2026-10-14');
  await assert.rejects(c.recordTaskEvent(pool,{user:user(hr),actor:hr,id:r.id,taskId:recovery.id,data:{event_key:randomUUID(),action:'completed',reference:'Synthetic future expected receipt',reason,facts:{}}}),/actual receipt/);await c.recordTaskEvent(pool,{user:user(hr),actor:hr,id:r.id,taskId:recovery.id,data:{event_key:randomUUID(),action:'completed',reference:'Synthetic HOD receipt',reason,facts:{receipt_reference:'Synthetic actual Treasury receipt',amount:'125.50'}}});
 });
 test('teacher cases require signed Education handling; attendance is central assisted and does not auto-create discipline',async()=>{
  await assert.rejects(caseSubmit(event('teacher_recreation')),/teacher appointment/);await pool.query('UPDATE hr_employee_service_periods SET is_teacher=TRUE WHERE employee_id=$1',[employee.id]);const teacher=await caseSubmit(event('teacher_recreation','2026-11-02','2026-11-03'));await determine(teacher.id,{...generic,education_processing_reference:'Synthetic approved Education processing order',duration_unit_reference:'Synthetic Chief Secretary discretionary period'});await grant(teacher.id);assert.equal((await w.requestView(pool,user(hr),teacher.id)).tasks[0].kind,'teacher_timesheet');
  await assert.rejects(caseSubmit(event('attendance')),e=>e.status===403);const attendance=await caseSubmit({...event('attendance','2026-10-07'),assisted_reference:'Synthetic reviewed employee attendance response'},hr,[]);await determine(attendance.id,{...generic,outcome:'reviewed_unpaid',due_process_reference:'Synthetic evidence and employee response determination'},'0');await grant(attendance.id);assert.equal((await w.requestView(pool,user(hr),attendance.id)).tasks.length,0);
 });
 test('assisted continuation atomically releases old hold, preserves decisions and reroutes with every approval required again',async()=>{
  const r=await submit();await decide(r.id);const continued=await c.continueRequest(pool,{user:user(hr),actor:hr,id:r.id,data:{request_id:randomUUID(),source_reference:'Synthetic employee-authorised route correction',reason}});assert.equal((await w.getRequest(pool,r.id)).status,'cancelled');const next=await w.requestView(pool,user(hr),continued.id);assert.equal(next.stage_index,0);assert.ok(next.stages.every(s=>!s.decision));assert.equal(next.assisted_entry,true);assert.equal((await l.loadContext(pool,employee.id)).entitlements.find(e=>e.code==='recreation').held,'1.000000');await grant(continued.id);
 });
 test('case privacy, route authority revocation, evidence changes and transaction audit failure fail closed',async()=>{
  const r=await caseSubmit();await determine(r.id,official);const divisionView=await w.requestView(pool,user(officers.division.account),r.id);assert.equal(divisionView.reason,null);assert.equal(divisionView.determination.facts,undefined);assert.deepEqual(divisionView.documents,[]);assert.equal((await call(`/requests/${r.id}/pdf`,null,officers.division.account)).status,404);
  await c.addCaseDocuments(pool,{user:user(hr),actor:hr,id:r.id,documents:[{...doc,sha256:'synthetic second source'}]});await decide(r.id);await decide(r.id);await assert.rejects(decide(r.id),/evidence changed/);await determine(r.id,official);await decide(r.id);
  await pool.query("CREATE FUNCTION synthetic_case_audit_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='hr.gov.case.effects_posted' THEN RAISE EXCEPTION 'Synthetic audit unavailable'; END IF; RETURN NEW; END $$;CREATE TRIGGER synthetic_case_audit_fail BEFORE INSERT ON audit_log FOR EACH ROW EXECUTE FUNCTION synthetic_case_audit_fail()");try{await assert.rejects(decide(r.id),/Synthetic audit unavailable/);assert.equal((await w.getRequest(pool,r.id)).status,'pending');assert.equal((await pool.query('SELECT 1 FROM hr_gov_case_effects WHERE request_id=$1',[r.id])).rowCount,0);}finally{await pool.query('DROP TRIGGER synthetic_case_audit_fail ON audit_log;DROP FUNCTION synthetic_case_audit_fail()');}await decide(r.id);
 });

 test('inactive separation records retain the employee, actual cessation reason and exact Recreation credit; no blanket misconduct forfeiture',async()=>{
  await pool.query("UPDATE hr_employees SET status='inactive' WHERE id=$1",[employee.id]);await pool.query("UPDATE hr_employee_service_periods SET end_date='2026-10-07' WHERE employee_id=$1",[employee.id]);const account=(await l.loadContext(pool,employee.id)).entitlements.find(e=>e.code==='recreation');
  const r=await caseSubmit({...event('recreation_separation','2026-10-07'),assisted_reference:'Synthetic signed cessation determination'},hr);await determine(r.id,{...financial('20','termination_misconduct'),entitlement_id:account.id,separation_valuation_reference:'Synthetic signed pro-rata exit payout and payable amount'});await grant(r.id);assert.equal((await w.getRequest(pool,r.id)).status,'approved');assert.equal((await l.loadContext(pool,employee.id)).entitlements.find(e=>e.code==='recreation').balance,'0.000000');
 });
 test('LWOP cancellation withdraws the service pause only at approved amendment and records Salary Unit correction',async()=>{
  const r=await caseSubmit(event('lwop','2026-11-02','2026-11-06'),owner,[]);await determine(r.id,{...generic,genuine_purpose:true,no_other_leave_accessible:true},'0');await grant(r.id);
  const amendment=await caseSubmit({...event('amendment','2026-11-02','2026-11-06'),related_request_id:r.id,assisted_reference:'Synthetic employee LWOP cancellation'},hr,[]);await determine(amendment.id,{...generic,original_request_id:r.id,action:'cancel_grant',salary_correction_reference:'Synthetic Salary Unit reversal instruction'});await grant(amendment.id);assert.equal((await l.loadContext(pool,employee.id)).exclusions.length,0);const entries=(await call('/calendar?from=2026-11-01&to=2026-11-10',null,owner)).body.entries;assert.equal(entries.some(e=>e.id===r.id),false);
 });
 test('benefit cancellation frees committed units through a new approved amendment while preserving the original valuation',async()=>{
  await oldService();const r=await caseSubmit({...event('furlough','2026-10-07'),assisted_reference:'Synthetic financial request'},hr);await determine(r.id,financial('100'));await grant(r.id);const bytes=Buffer.from((await w.getRequest(pool,r.id)).final_pdf);
  const a=await caseSubmit({...event('amendment','2026-10-07'),related_request_id:r.id,assisted_reference:'Synthetic cancel financial commitment'},hr,[]);await determine(a.id,{...generic,original_request_id:r.id,action:'cancel_grant',salary_correction_reference:'Synthetic actual Salary Unit commitment cancellation'});await grant(a.id);assert.deepEqual((await w.getRequest(pool,r.id)).final_pdf,bytes);
  const next=await caseSubmit({...event('furlough','2026-10-07'),assisted_reference:'Synthetic replacement benefit request'},hr);await determine(next.id,financial('100'));await grant(next.id);
 });
 test('actual HTTP case routes enforce applicant ownership and central determinations without trusting injected pay or charges',async()=>{
  const session=await auth.createSession(owner.id),token=auth.buildTokenPayload(owner,session.tokenId,session.expiresAt),f=new FormData(),data=event();for(const [key,val] of Object.entries(data))f.set(key,val);f.set('employee_id',officers.division.employee.id);f.set('charge','999');f.set('salary_percent','999');f.append('documents',new Blob([doc.file_data],{type:'application/pdf'}),'synthetic-case.pdf');
  const response=await fetch(base+'/api/hr/government/workflow/cases',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:f});assert.equal(response.status,201);const r=await response.json();assert.equal((await w.getRequest(pool,r.id)).employee_id,employee.id);assert.equal((await w.getRequest(pool,r.id)).charge,'0.000000');assert.equal((await call(`/requests/${r.id}/determinations`,{facts:official},owner)).status,403);assert.equal((await call(`/requests/${r.id}/tasks/${randomUUID()}/events`,{},owner)).status,403);
 });

 test('case and continuation retries remain stable across an overnight boundary and changed facts cannot reuse the key',async()=>{
  const data=event(),r=await caseSubmit(data),now=Date.now;try{Date.now=()=>now()+86400000;assert.equal((await caseSubmit(data)).id,r.id);await assert.rejects(caseSubmit({...data,reason:'Different submitted explanation after midnight'}),/different facts/);}finally{Date.now=now;}
  const common=await submit(application('recreation','2026-11-09')),continuation={request_id:randomUUID(),source_reference:'Synthetic sourced route continuation authority',reason};const next=await c.continueRequest(pool,{user:user(hr),actor:hr,id:common.id,data:continuation});assert.equal((await c.continueRequest(pool,{user:user(hr),actor:hr,id:common.id,data:continuation})).id,next.id);await assert.rejects(c.continueRequest(pool,{user:user(hr),actor:hr,id:common.id,data:{...continuation,request_id:randomUUID()}}),/different continuation/);
 });
 test('bounded central follow-up register withholds actual receipt details from ordinary approvers',async()=>{
  const r=await caseSubmit();await determine(r.id,official);await grant(r.id);const centralView=await w.requestView(pool,user(hr),r.id),task=centralView.tasks[0];await c.recordTaskEvent(pool,{user:user(hr),actor:hr,id:r.id,taskId:task.id,data:{event_key:randomUUID(),action:'completed',reference:'Synthetic confidential personnel follow-up reference',reason,facts:{}}});
  assert.equal((await call('/case-tasks?status=open',null,hr)).body.total,0);const all=await call('/case-tasks?status=all',null,hr);assert.equal(all.status,200);assert.equal(all.body.page_size,50);assert.equal(all.body.tasks[0].request_id,r.id);assert.equal((await call('/case-tasks',null,owner)).status,403);const officer=await w.requestView(pool,user(officers.division.account),r.id);assert.equal(officer.tasks[0].reference,null);assert.equal(officer.tasks[0].description,'Personnel follow-up is recorded by authorised HR.');
 });
});
