import express from 'express';
import {pool} from '../db.js';
import {body,param,query,handleValidation} from '../middleware/validation.js';
import {requirePermission} from '../services/authService.js';
import {PERMISSIONS} from '../config.js';
import {linkedEmployee} from '../services/employeeDirectory.js';
import {governmentEvidenceUpload} from '../services/governmentLeaveUpload.js';
import {CASE_CODES} from '../lib/governmentLeaveCaseRules.js';
import {dayNumber} from '../lib/governmentLeaveRules.js';
import * as cases from '../services/governmentLeaveCases.js';
import * as workflow from '../services/governmentLeaveWorkflow.js';
const router=express.Router(),central=requirePermission(PERMISSIONS.HR_ADMIN),apply=requirePermission(PERMISSIONS.HR_LEAVE_APPLY);
const actor=req=>({id:req.user.id,email:req.user.email,ip:req.ip});
const args=req=>({user:req.user,actor:actor(req),id:req.params.id,data:req.body});
const id=param('id').isUUID(),reason=body('reason').isString().trim().isLength({min:10,max:1000}),ref=body('source_reference').isString().trim().isLength({min:5,max:500});
const caseFields=[body('request_id').isUUID(),body('code').isIn(CASE_CODES),...['start_date','end_date'].map(n=>body(n).custom(v=>{dayNumber(v);return true;})),body('reason').isString().trim().isLength({min:10,max:4000}),body('event_reference').isString().trim().isLength({min:5,max:500}),body('related_request_id').optional({nullable:true,checkFalsy:true}).isUUID()];
router.get('/case-tasks',central,[query('employee_id').optional().isUUID(),query('page').optional().isInt({min:1,max:100000}),query('status').optional().isIn(['open','completed','reopened','noncompletion','all'])],async(req,res)=>{
 if(!handleValidation(req,res))return;const page=Number(req.query.page)||1,status=req.query.status||'open',employeeId=req.query.employee_id||null;
 const from=`FROM hr_gov_case_tasks t JOIN hr_gov_requests r ON r.id=t.request_id JOIN hr_employees e ON e.id=r.employee_id LEFT JOIN LATERAL(SELECT action,reference FROM hr_gov_task_events ev WHERE ev.task_id=t.id ORDER BY recorded_at DESC,id DESC LIMIT 1)ev ON TRUE`;
 const where=`($1::uuid IS NULL OR r.employee_id=$1) AND ($2='all' OR ($2='open' AND COALESCE(ev.action,'open') IN ('open','reopened','noncompletion')) OR COALESCE(ev.action,'open')=$2)`;
 const {rows}=await pool.query(`SELECT t.id,t.request_id,t.kind,t.description,to_char(t.due_date,'YYYY-MM-DD') AS due_date,r.employee_id,e.display_name,r.code,COALESCE(ev.action,'open') AS status,ev.reference ${from} WHERE ${where} ORDER BY t.due_date NULLS LAST,t.id LIMIT 50 OFFSET $3`,[employeeId,status,(page-1)*50]);
 const total=(await pool.query(`SELECT count(*)::int AS total ${from} WHERE ${where}`,[employeeId,status])).rows[0].total;res.json({tasks:rows,total,page,page_size:50,today:workflow.today()});
});
router.post('/cases',apply,governmentEvidenceUpload,caseFields,async(req,res)=>{if(!handleValidation(req,res))return;const employee=await linkedEmployee(pool,req.user.id);res.status(201).json(await cases.submitCase(pool,{...args(req),employeeId:employee.id,documents:req.governmentDocuments||[]}));});
router.post('/employees/:id/cases',central,governmentEvidenceUpload,[id,...caseFields,body('assisted_reference').isString().trim().isLength({min:5,max:500})],async(req,res)=>{if(!handleValidation(req,res))return;res.status(201).json(await cases.submitCase(pool,{...args(req),employeeId:req.params.id,documents:req.governmentDocuments||[]}));});
router.post('/requests/:id/determinations',central,[id,reason,ref,body('evidence_reference').isString().trim().isLength({min:5,max:500}),body('facts').isObject(),body('pay_segments').isArray({min:1,max:24})],async(req,res)=>{if(!handleValidation(req,res))return;res.status(201).json(await cases.prepareDetermination(pool,args(req)));});
router.post('/requests/:id/evidence',central,governmentEvidenceUpload,[id],async(req,res)=>{if(!handleValidation(req,res))return;await cases.addCaseDocuments(pool,{...args(req),documents:req.governmentDocuments||[]});res.json({recorded:true});});
router.post('/requests/:id/tasks/:taskId/events',central,[id,param('taskId').isUUID(),reason,body('event_key').isUUID(),body('reference').isString().trim().isLength({min:5,max:500}),body('action').isIn(['completed','reopened','noncompletion']),body('facts').isObject()],async(req,res)=>{if(!handleValidation(req,res))return;res.status(201).json(await cases.recordTaskEvent(pool,{...args(req),taskId:req.params.taskId}));});
router.post('/requests/:id/continue',central,[id,reason,ref,body('request_id').isUUID()],async(req,res)=>{if(!handleValidation(req,res))return;res.status(201).json(await cases.continueRequest(pool,args(req)));});
router.post('/employees/:id/assisted-requests',central,governmentEvidenceUpload,[id,body('request_id').isUUID(),body('code').isIn(['recreation','medical','special']),...['start_date','end_date'].map(n=>body(n).custom(v=>{dayNumber(v);return true;})),body('reason').isString().trim().isLength({min:10,max:4000}),body('assisted_reference').isString().trim().isLength({min:5,max:500}),body('medical_mode').custom((v,{req})=>req.body.code==='medical'?['certificate','exemption'].includes(v):v==null||v==='not_applicable')],async(req,res)=>{if(!handleValidation(req,res))return;res.status(201).json(await workflow.submitRequest(pool,{...args(req),employeeId:req.params.id,documents:req.governmentDocuments||[]}));});
export default router;
