import {describe,test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {connectTestDatabase,resetLeaveTables,skipWithoutDatabase} from '../test-support/database.js';
import {DEFAULT_RULES,fingerprint} from '../lib/governmentLeaveRules.js';
import {payrollCsv} from '../lib/governmentLeavePayrollRules.js';

describe('government Payroll registers and migration rehearsal',{skip:skipWithoutDatabase},()=>{
 let pool,p,l,w,hr,certifier,owner,employee,department,division,policy,auth,server,base;
 const reason='Synthetic signed local Salary Unit and HR reconciliation.';
 const actor=row=>({id:row.id}),user=row=>({...row,permissions:row.permissions});
 const args=(data,by=hr)=>({user:user(by),actor:actor(by),data});
 before(async()=>{
  pool=await connectTestDatabase();p=await import('../services/governmentLeavePayroll.js');l=await import('../services/governmentLeave.js');w=await import('../services/governmentLeaveWorkflow.js');auth=await import('../services/authService.js');
  const express=(await import('express')).default,errors=await import('../middleware/errors.js');errors.enableAsyncErrors();const app=express();app.use(express.json());app.use('/api/hr',(await import('./hr.js')).default);app.use(errors.errorHandler);server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});base=`http://127.0.0.1:${server.address().port}/api/hr/government/payroll`;
 });
 after(async()=>{await new Promise(resolve=>server.close(resolve));await pool.end();});
 async function account(permissions){return(await pool.query("INSERT INTO reviewers(email,display_name,role,password_hash,permissions) VALUES($1,'Synthetic Payroll reviewer','user','x',$2) RETURNING *",[`${randomUUID()}@example.test`,permissions])).rows[0];}
 async function opening(code,amount){const row=await l.prepareOpening(pool,{...args({code,amount,policy_version_id:policy.id,period_start:'2026-01-01',period_end:'2026-12-31',as_of:'2026-10-01',source_reference:'Synthetic opening source',payroll_reference:'Synthetic Salary Unit opening source',reason}),employeeId:employee.id});await l.certifyOpening(pool,{...args({},certifier),id:row.id,reason});}
 beforeEach(async()=>{
  await resetLeaveTables(pool);await pool.query('TRUNCATE hr_gov_payroll_batches,hr_gov_handovers,hr_gov_policy_versions,hr_gov_calendars,hr_gov_pattern_approvals CASCADE');
  hr=await account({hr_admin:true,hr_access:true});certifier=await account({hr_admin:true,hr_access:true});owner=await account({hr_access:true,hr_leave_apply:true});
  department=(await pool.query("INSERT INTO hr_departments(name) VALUES('Synthetic Payroll Department') RETURNING *")).rows[0];division=(await pool.query("INSERT INTO hr_divisions(name,department_id) VALUES('Synthetic Payroll Division',$1) RETURNING *",[department.id])).rows[0];
  employee=(await pool.query("INSERT INTO hr_employees(display_name,reviewer_id,department_id,division_id,leave_policy_regime) VALUES('Synthetic Payroll Employee',$1,$2,$3,'government') RETURNING *",[owner.id,department.id,division.id])).rows[0];
  await pool.query("INSERT INTO hr_employee_external_ids(employee_id,source,external_id,verified_by,reason) VALUES($1,'techone_payroll','00001-A',$2,$3)",[employee.id,hr.id,reason]);
  const pattern=(await pool.query("INSERT INTO hr_work_patterns(name,working_weekdays,hours_per_day) VALUES($1,ARRAY[1,2,3,4,5],7) RETURNING *",[`Synthetic Payroll ${randomUUID()}`])).rows[0];
  await pool.query("INSERT INTO hr_employee_service_periods(employee_id,start_date,employment_category,counts_for_service,work_pattern_id,reason) VALUES($1,'2026-01-01','permanent',TRUE,$2,$3)",[employee.id,pattern.id,reason]);
  await l.addFoundationRecord(pool,{...args({work_pattern_id:pattern.id,source_reference:'Synthetic work pattern authority',reason}),kind:'pattern'});
  await l.addFoundationRecord(pool,{...args({effective_from:'2026-01-01',continuity_start:'2026-01-01',anniversary_method:'calendar',leap_day_method:'feb28',schedule_mode:'weekly',source_reference:'Synthetic service basis authority',reason}),employeeId:employee.id,kind:'basis'});
  policy=await l.createPolicy(pool,args({label:'Synthetic Payroll policy',effective_from:'2026-01-01',effective_to:'2027-12-31',rules:DEFAULT_RULES,source_reference:'Synthetic published policy',reason}));await l.publishPolicy(pool,{...args({}),id:policy.id,reason});
  await l.createCalendar(pool,args({label:'Synthetic Payroll calendar',effective_from:'2026-01-01',effective_to:'2027-12-31',holidays:[],source_reference:'Synthetic Gazette calendar',reason}));
  for(const [code,amount] of [['recreation','20'],['medical','10'],['special','3']])await opening(code,amount);
 });
 // Seed a completed, immutable workflow fact to isolate the exchange contract.
 // Actual staged approvals and final atomic grant are covered by workflow/case suites.
 async function granted({code='official',salary='100.000000',payable=null,id:providedId=null}={}){
  const id=providedId||randomUUID(),evaluation={segments:[{date:'2026-11-02',charge:'1.000000',scheduled_hours:7,policy_version_id:policy.id},{date:'2026-11-03',charge:'1.000000',scheduled_hours:7,policy_version_id:policy.id}]};
  const grant={employee:{id:employee.id,name:'Synthetic Payroll Employee',department_id:department.id,division_id:division.id},evaluation,effect:{absence:payable===null},case_determination:{evaluation,pay_segments:[{start_date:'2026-11-02',end_date:'2026-11-03',salary_percent:salary}],facts:payable===null?{}:{action:'encashment',payable_amount:payable},...(payable===null?{}:{benefit:{requested:'20.000000'}})}};
  await pool.query("INSERT INTO hr_gov_requests(id,employee_id,code,start_date,end_date,reason,medical_mode,payload_hash,application_snapshot,department_id,division_id,charge,submitted_by,status,grant_snapshot,final_pdf) VALUES($1,$2,$3,'2026-11-02','2026-11-03',$4,'not_applicable','synthetic',$5,$6,$7,0,$8,'approved',$5,$9)",[id,employee.id,code,'Private clinical/parental reason must not enter exchange lines',grant,department.id,division.id,hr.id,Buffer.from('%PDF-1.7 synthetic immutable grant')]);return id;
 }
 const period=(changes={})=>({batch_id:randomUUID(),period_start:'2026-11-01',period_end:'2026-11-14',source_reference:'Synthetic approved Salary Unit contract',reason,...changes});
 const migration=(changes={})=>({review_id:randomUUID(),cutover_date:'2026-10-07',targets:[{code:'recreation',amount:'19'},{code:'medical',amount:'9'},{code:'special',amount:'2'}],dispositions:[],source_reference:'Synthetic certified opening register',payroll_reference:'Synthetic Salary Unit reconciliation',transition_reference:'Synthetic signed medical-pool/Special transition',history_reference:'Synthetic verified service and prior payout history',reason,...changes});
 const prepare=data=>p.prepareMigration(pool,{...args(data),employeeId:employee.id});
 async function certify(review,by=certifier){return p.certifyMigration(pool,{...args({context_hash:review.context_hash,reason},by),id:review.id});}
 async function http(path,by=owner,data=null){const session=await auth.createSession(by.id),token=auth.buildTokenPayload(by,session.tokenId,session.expiresAt);const r=await fetch(base+path,{method:data?'POST':'GET',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});return {status:r.status,body:r.headers.get('content-type')?.includes('json')?await r.json():await r.text()};}
 test('register freezes salary instructions, retains text ID, omits clinical reasons and repeats exact exports',async()=>{await granted({salary:'50.000000'});const data=period(),b=await p.preparePayroll(pool,args(data));assert.equal((await p.preparePayroll(pool,args(data))).id,b.id);assert.equal(b.snapshot.lines[0].payroll_id,'00001-A');assert.equal(b.snapshot.lines[0].salary_percent,'50.000000');assert.equal(fingerprint(b.snapshot),b.snapshot_hash);assert.ok(!JSON.stringify(b.snapshot).includes('Private clinical'));assert.equal(payrollCsv(b),payrollCsv(await p.payrollView(pool,user(hr),b.id)));await assert.rejects(p.preparePayroll(pool,args(period())),/No register changes/);await assert.rejects(pool.query('UPDATE hr_gov_payroll_batches SET reason=$2 WHERE id=$1',[b.id,'rewrite']),/immutable/);});
 test('approved amendment creates versioned reversals without editing original batch',async()=>{const r=await granted(),b=await p.preparePayroll(pool,args(period()));await pool.query('INSERT INTO hr_gov_case_effects(request_id,original_request_id,effect,recorded_by) VALUES($1,$1,$2,$3)',[r,{action:'shorten_grant',effective_end:'2026-11-02'},hr.id]);const next=await p.preparePayroll(pool,args(period()));assert.equal(next.version,2);assert.equal(next.supersedes_id,b.id);assert.equal(next.snapshot.lines.length,1);assert.ok(next.snapshot.changes.some(c=>c.action==='remove'));assert.equal((await p.payrollView(pool,user(hr),b.id)).snapshot.lines.length,2);assert.match(payrollCsv(next,true),/reverse_previous_instruction/);});
 test('overlapping different Payroll windows are rejected; adjacent windows and zero salary work',async()=>{await granted({salary:'0.000000'});await p.preparePayroll(pool,args(period()));await assert.rejects(p.preparePayroll(pool,args(period({period_start:'2026-11-10',period_end:'2026-11-20'}))),/overlap/);const adjacent=await p.preparePayroll(pool,args(period({period_start:'2026-11-15',period_end:'2026-11-28'})));assert.equal(adjacent.snapshot.lines.length,0);});
 test('concurrent same key produces one period version; changed nonce payload rejects',async()=>{await granted();const data=period(),rows=await Promise.all([p.preparePayroll(pool,args(data)),p.preparePayroll(pool,args(data))]);assert.equal(rows[0].id,rows[1].id);assert.equal((await pool.query('SELECT count(*)::int AS n FROM hr_gov_payroll_batches')).rows[0].n,1);await assert.rejects(p.preparePayroll(pool,args({...data,reason:reason+' changed'})),/key/);});
 test('Payroll receipt checks independent authority, exact hash, current grant set and correction confirmation',async()=>{const r=await granted(),b=await p.preparePayroll(pool,args(period())),receipt={reference:'Synthetic actual Salary Unit receipt',snapshot_hash:b.snapshot_hash,reason};await assert.rejects(p.acknowledgePayroll(pool,{...args(receipt),id:b.id}),/different/);await assert.rejects(p.acknowledgePayroll(pool,{...args({...receipt,snapshot_hash:'a'.repeat(64)},certifier),id:b.id}),/checksum/);await pool.query('INSERT INTO hr_gov_case_effects(request_id,original_request_id,effect,recorded_by) VALUES($1,$1,$2,$3)',[r,{action:'cancel_grant'},hr.id]);await assert.rejects(p.acknowledgePayroll(pool,{...args(receipt,certifier),id:b.id}),/changed/);const next=await p.preparePayroll(pool,args(period()));await assert.rejects(p.acknowledgePayroll(pool,{...args(receipt,certifier),id:b.id}),/superseded/);await assert.rejects(p.acknowledgePayroll(pool,{...args({...receipt,snapshot_hash:next.snapshot_hash},certifier),id:next.id}),/correction/);const a=await p.acknowledgePayroll(pool,{...args({...receipt,snapshot_hash:next.snapshot_hash,corrections_reconciled:true},certifier),id:next.id});assert.equal((await p.acknowledgePayroll(pool,{...args({...receipt,snapshot_hash:next.snapshot_hash,corrections_reconciled:true},certifier),id:next.id})).batch_id,a.batch_id);});
 test('ambiguous Payroll IDs block automatic register preparation; explicit verified selection is retained',async()=>{await granted();await pool.query("INSERT INTO hr_employee_external_ids(employee_id,source,external_id,verified_by,reason) VALUES($1,'techone_payroll','00001-B',$3,$2)",[employee.id,reason,hr.id]);await assert.rejects(p.preparePayroll(pool,args(period())),/Payroll ID/);const b=await p.preparePayroll(pool,args(period({payroll_ids:{[employee.id]:'00001-B'}})));assert.equal(b.snapshot.lines[0].payroll_id,'00001-B');});
 test('financial instructions are one signed amount per event date, no payment or extra ledger posting',async()=>{await granted({code:'long_service',payable:'1200.50'});const before=(await pool.query('SELECT count(*)::int AS n FROM hr_gov_ledger')).rows[0].n,b=await p.preparePayroll(pool,args(period()));assert.equal(b.snapshot.lines.length,1);assert.equal(b.snapshot.lines[0].payable_aud,'1200.50');assert.equal((await pool.query('SELECT count(*)::int AS n FROM hr_gov_ledger')).rows[0].n,before);});
 test('HTTP owner/scoped officers cannot read or write Salary Unit and personnel handover records',async()=>{const scoped=await account({hr_access:true,hr_report_read:true,hr_staff_manage:true});for(const by of [owner,scoped])for(const path of ['/registers','/migrations','/handovers',`/employees/${employee.id}/migration-state?cutover_date=2026-10-07`])assert.equal((await http(path,by)).status,403);assert.equal((await http('/registers',owner,period())).status,403);assert.equal((await http('/registers',hr)).status,200);});
 test('fresh account revocation rejects both write and download despite stale caller permissions',async()=>{await granted();const b=await p.preparePayroll(pool,args(period()));await pool.query("UPDATE reviewers SET status='inactive' WHERE id=$1",[hr.id]);await assert.rejects(p.payrollView(pool,user(hr),b.id),/Current central/);await assert.rejects(p.preparePayroll(pool,args(period())),/Current central/);});
 test('migration preview does not mutate; independent certification posts exact deltas once and retains historical five-day Special',async()=>{const type=(await pool.query("INSERT INTO hr_leave_types(name,default_days) VALUES($1,5) RETURNING *",[`Synthetic legacy Special ${randomUUID()}`])).rows[0];await pool.query('INSERT INTO hr_leave_balances(employee_id,leave_type_id,year,balance,pending) VALUES($1,$2,2026,5,0)',[employee.id,type.id]);const data=migration(),review=await prepare(data);assert.equal((await l.loadContext(pool,employee.id)).entitlements.find(e=>e.code==='special').balance,'3.000000');await assert.rejects(certify(review,hr),/different/);await Promise.all([certify(review),certify(review)]);assert.equal((await l.loadContext(pool,employee.id)).entitlements.find(e=>e.code==='special').balance,'2.000000');assert.equal((await pool.query('SELECT balance FROM hr_leave_balances WHERE employee_id=$1',[employee.id])).rows[0].balance,'5.00');assert.equal((await pool.query("SELECT count(*)::int AS n FROM hr_gov_ledger WHERE event_key LIKE 'migration:%'")).rows[0].n,3);});
 test('changed balance or new future application invalidates a prepared migration before posting',async()=>{const review=await prepare(migration());const e=(await l.loadContext(pool,employee.id)).entitlements.find(e=>e.code==='recreation');await l.correctLedger(pool,{...args({entitlement_id:e.id,amount:'1',effective_date:'2026-10-07',event_key:randomUUID(),source_reference:'Synthetic correction authority',reason}),employeeId:employee.id});await assert.rejects(certify(review),/changed/);assert.equal((await pool.query('SELECT count(*)::int AS n FROM hr_gov_migration_certifications')).rows[0].n,0);});
 test('targets cannot spend pending holds or exceed a single annual pool',async()=>{const account=(await l.loadContext(pool,employee.id)).entitlements.find(e=>e.code==='recreation'),id=randomUUID();await pool.query("INSERT INTO hr_gov_reservation_requests(id,employee_id,payload_hash,evaluation_snapshot) VALUES($1,$2,'test','{}')",[id,employee.id]);await pool.query('INSERT INTO hr_gov_reservations(request_id,entitlement_id,amount) VALUES($1,$2,20)',[id,account.id]);await assert.rejects(prepare(migration()),/held/);await assert.rejects(prepare(migration({targets:[{code:'recreation',amount:'20'},{code:'medical',amount:'11'},{code:'special',amount:'3'}]})),/pool or cap/);});
 test('all retained pending/future leave needs a disposition; external retention blocks jobs/activation and preserves history',async()=>{const type=(await pool.query("SELECT id FROM hr_leave_types LIMIT 1")).rows[0],legacy=(await pool.query("INSERT INTO hr_leave_applications(employee_id,leave_type_id,start_date,end_date,days) VALUES($1,$2,'2026-11-02','2026-11-03',2) RETURNING *",[employee.id,type.id])).rows[0];await assert.rejects(prepare(migration()),/every pending/);const review=await prepare(migration({dispositions:[{legacy_request_id:legacy.id,action:'retain_external',reference:'Synthetic retained future/pending authority'}]}));await certify(review);const guard=await import('../services/governmentLeaveCutover.js');await assert.rejects(guard.assertCutoverResolved(pool,employee.id),/retained external/);assert.equal((await pool.query('SELECT status FROM hr_leave_applications WHERE id=$1',[legacy.id])).rows[0].status,'pending');});
 test('certification creates missing openings atomically under the original preparer and independent certifier',async()=>{await pool.query('TRUNCATE hr_gov_openings CASCADE');const review=await prepare(migration());await certify(review);const context=await l.loadContext(pool,employee.id);assert.equal(context.entitlements.length,3);assert.equal(context.entitlements.find(e=>e.code==='medical').balance,'9.000000');const openings=(await pool.query('SELECT prepared_by,certified_by FROM hr_gov_openings')).rows;assert.ok(openings.every(o=>o.prepared_by===hr.id&&o.certified_by===certifier.id));});
 test('portable handover keeps frozen documents, pending reservations, original grants and precise IDs without login secrets',async()=>{const request=await granted();await pool.query("INSERT INTO hr_gov_request_documents(request_id,file_name,content_type,byte_size,sha256,file_data) VALUES($1,'synthetic.pdf','application/pdf',8,$2,$3)",[request,createHash('sha256').update('%PDF-1.7').digest('hex'),Buffer.from('%PDF-1.7')]);const data={handover_id:randomUUID(),employee_ids:[employee.id],include_documents:true,source_reference:'Synthetic approved handover rehearsal',reason},h=await p.prepareHandover(pool,args(data));assert.equal(h.snapshot.employees[0].external_ids[0].external_id,'00001-A');assert.match(Buffer.from(h.snapshot.employees[0].requests[0].final_pdf_base64,'base64').toString(),/%PDF/);assert.equal(h.snapshot.employees[0].documents[0].file_data_base64,Buffer.from('%PDF-1.7').toString('base64'));assert.ok(!JSON.stringify(h.snapshot).includes('password_hash'));assert.equal(h.snapshot.receiving_controls.enable_receiving_accrual,false);assert.equal(fingerprint(h.snapshot),h.snapshot_hash);assert.equal((await p.prepareHandover(pool,args(data))).id,h.id);await assert.rejects(pool.query('DELETE FROM hr_gov_handovers WHERE id=$1',[h.id]),/immutable/);});
 test('handover parts redact other employees exchange rows and require independent hash-matched receipt',async()=>{await granted();await p.preparePayroll(pool,args(period()));const other=(await pool.query("INSERT INTO hr_employees(display_name) VALUES('Synthetic outside cohort') RETURNING *")).rows[0],h=await p.prepareHandover(pool,args({handover_id:randomUUID(),employee_ids:[other.id],include_documents:false,source_reference:'Synthetic subset handover',reason}));assert.equal(h.snapshot.payroll_registers[0].snapshot.lines.length,0);assert.ok(!JSON.stringify(h.snapshot).includes('00001-A'));const receipt={reference:'Synthetic actual receiving rehearsal receipt',snapshot_hash:h.snapshot_hash,reason};await assert.rejects(p.acknowledgeHandover(pool,{...args(receipt),id:h.id}),/different/);await p.acknowledgeHandover(pool,{...args(receipt,certifier),id:h.id});assert.equal((await p.handoverView(pool,user(hr),h.id)).receipt_reference,receipt.reference);});
 test('certified retained pending leave can link an exact portal request and permits reviewed continuation',async()=>{const type=(await pool.query('SELECT id FROM hr_leave_types LIMIT 1')).rows[0],legacy=(await pool.query("INSERT INTO hr_leave_applications(employee_id,leave_type_id,start_date,end_date,days,status) VALUES($1,$2,'2026-11-02','2026-11-03',2,'approved') RETURNING *",[employee.id,type.id])).rows[0];const request=await granted();await assert.rejects(prepare(migration({dispositions:[{legacy_request_id:legacy.id,action:'portal_link',portal_request_id:randomUUID(),reference:'Synthetic incorrect link authority'}]})),/same employee/);const review=await prepare(migration({dispositions:[{legacy_request_id:legacy.id,action:'portal_link',portal_request_id:request,reference:'Synthetic exact approved grant reconciliation'}]}));await certify(review);await (await import('../services/governmentLeaveCutover.js')).assertCutoverResolved(pool,employee.id);});
 test('migration rejects targets that reuse Medical credit already consumed or recorded before cutover',async()=>{const account=(await l.loadContext(pool,employee.id)).entitlements.find(e=>e.code==='medical');await l.postMovement(pool,{entitlementId:account.id,kind:'use',amount:'-2',effectiveDate:'2026-10-02',eventKey:'synthetic-medical-use',sourceReference:'Synthetic historical posted Medical use',actor:actor(hr),reason});await assert.rejects(prepare(migration({targets:[{code:'recreation',amount:'19'},{code:'medical',amount:'9'},{code:'special',amount:'2'}]})),/single annual pool/);});
 test('audit failure rolls back all migration corrections and certification together',async()=>{const review=await prepare(migration());await pool.query("CREATE FUNCTION synthetic_payroll_audit_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='hr.gov.migration.certified' THEN RAISE EXCEPTION 'synthetic audit failure'; END IF; RETURN NEW; END $$; CREATE TRIGGER synthetic_payroll_audit_failure BEFORE INSERT ON audit_log FOR EACH ROW EXECUTE FUNCTION synthetic_payroll_audit_failure()");try{await assert.rejects(certify(review),/synthetic audit failure/);assert.equal((await l.loadContext(pool,employee.id)).entitlements.find(e=>e.code==='special').balance,'3.000000');assert.equal((await pool.query('SELECT count(*)::int AS n FROM hr_gov_migration_certifications')).rows[0].n,0);}finally{await pool.query('DROP TRIGGER synthetic_payroll_audit_failure ON audit_log; DROP FUNCTION synthetic_payroll_audit_failure()');}});
 test('certified legacy transfer submits a fresh event with retained original and rejects employee bypass',async()=>{
  const type=(await pool.query('SELECT id FROM hr_leave_types LIMIT 1')).rows[0],legacy=(await pool.query("INSERT INTO hr_leave_applications(employee_id,leave_type_id,start_date,end_date,days,status) VALUES($1,$2,'2026-11-02','2026-11-03',2,'approved') RETURNING *",[employee.id,type.id])).rows[0],requestId=randomUUID();
  const review=await prepare(migration({dispositions:[{legacy_request_id:legacy.id,action:'transfer_with_fresh_approval',portal_request_id:requestId,code:'official',reference:'Synthetic signed transferred official legacy reconciliation'}]}));await certify(review);
  const guard=await import('../services/governmentLeaveCutover.js');await assert.rejects(guard.assertCutoverResolved(pool,employee.id),/linked cutover/);await guard.assertCutoverResolved(pool,employee.id,{activation:true});
  await assert.rejects(p.submitLegacyTransfer(pool,{...args({reason},owner),id:legacy.id}),/central/);
  const submitted=await p.submitLegacyTransfer(pool,{...args({reason}),id:legacy.id});assert.equal(submitted.id,requestId);assert.equal(submitted.status,'pending');assert.equal((await p.submitLegacyTransfer(pool,{...args({reason}),id:legacy.id})).id,requestId);
  await guard.assertCutoverResolved(pool,employee.id);assert.equal((await pool.query('SELECT status FROM hr_leave_applications WHERE id=$1',[legacy.id])).rows[0].status,'approved');assert.ok((await w.stagesFor(pool,requestId)).length>=4);const r=await w.getRequest(pool,requestId);assert.equal(r.final_pdf,null);assert.equal(r.grant_snapshot,null);
  const cases=await import('../services/governmentLeaveCases.js');await assert.rejects(cases.submitCase(pool,{...args({request_id:randomUUID(),code:'official',start_date:'2026-11-02',end_date:'2026-11-03',reason,event_reference:'Synthetic ordinary overlapping event',assisted_reference:'Synthetic other authority'}),employeeId:employee.id}),/overlap/);
 });
 test('changed legacy dates invalidate a certified transfer and do not create a new request',async()=>{
  const type=(await pool.query('SELECT id FROM hr_leave_types LIMIT 1')).rows[0],legacy=(await pool.query("INSERT INTO hr_leave_applications(employee_id,leave_type_id,start_date,end_date,days) VALUES($1,$2,'2026-11-02','2026-11-03',2) RETURNING *",[employee.id,type.id])).rows[0];
  const review=await prepare(migration({dispositions:[{legacy_request_id:legacy.id,action:'transfer_with_fresh_approval',portal_request_id:randomUUID(),code:'official',reference:'Synthetic signed transfer source'}]}));await certify(review);await pool.query("UPDATE hr_leave_applications SET end_date='2026-11-04' WHERE id=$1",[legacy.id]);await assert.rejects(p.submitLegacyTransfer(pool,{...args({reason}),id:legacy.id}),/certified legacy transfer changed/);assert.equal((await pool.query('SELECT count(*)::int AS n FROM hr_gov_requests')).rows[0].n,0);
 });
 test('central migration source export works and owner cannot download the review',async()=>{const review=await prepare(migration());assert.equal((await http(`/migrations/${review.id}/export`,owner)).status,403);const r=await http(`/migrations/${review.id}/export`,hr);assert.equal(r.status,200);assert.equal(r.body.context_hash,review.context_hash);assert.equal(r.body.snapshot.identity.payroll_id,'00001-A');});
 test('calendar uses the approved transfer once and an approved cancellation cannot resurrect the legacy absence',async()=>{
  const type=(await pool.query('SELECT id FROM hr_leave_types LIMIT 1')).rows[0],legacy=(await pool.query("INSERT INTO hr_leave_applications(employee_id,leave_type_id,start_date,end_date,days,status) VALUES($1,$2,'2026-11-02','2026-11-03',2,'approved') RETURNING *",[employee.id,type.id])).rows[0],requestId=randomUUID();
  const review=await prepare(migration({dispositions:[{legacy_request_id:legacy.id,action:'transfer_with_fresh_approval',portal_request_id:requestId,code:'official',reference:'Synthetic calendar transfer reference'}]}));await certify(review);await granted({id:requestId});
  const session=await auth.createSession(hr.id),token=auth.buildTokenPayload(hr,session.tokenId,session.expiresAt),headers={Authorization:`Bearer ${token}`};
  const legacyUrl=base.replace('/government/payroll','/calendar?from=2026-11-01&to=2026-11-14'),governmentUrl=base.replace('/payroll','/workflow/calendar?from=2026-11-01&to=2026-11-14');
  assert.equal((await(await fetch(legacyUrl,{headers})).json()).length,0);assert.equal((await(await fetch(governmentUrl,{headers})).json()).entries.length,1);
  await pool.query('INSERT INTO hr_gov_case_effects(request_id,original_request_id,effect,recorded_by) VALUES($1,$1,$2,$3)',[requestId,{action:'cancel_grant'},hr.id]);assert.equal((await(await fetch(legacyUrl,{headers})).json()).length,0);assert.equal((await(await fetch(governmentUrl,{headers})).json()).entries.length,0);assert.equal((await pool.query('SELECT status FROM hr_leave_applications WHERE id=$1',[legacy.id])).rows[0].status,'approved');
 });
 test('repeated schema bootstrap keeps Payroll immutable constraints and existing versions',async()=>{await granted();const b=await p.preparePayroll(pool,args(period()));await (await import('../db.js')).initSchema();assert.equal((await p.payrollView(pool,user(hr),b.id)).version,1);await assert.rejects(pool.query('UPDATE hr_gov_payroll_batches SET version=2 WHERE id=$1',[b.id]),/immutable/);});
});
